Namespace XMLResources
    Public Class SL_MessageName
        Public Const XMLText As String = _
        "<MessageNames>" & _
        "	<!-- Single Loader  -->" & _
        "	<!--KepServer-->" & _
        "	<MessageName>" & _
        "		<Name>ChangeArmUpDownStatusInSLProcessScreenTo</Name>" & _
        "		<Code>SL_ProcessPanel.slArmUpStatus</Code>" & _
        "	</MessageName>" & _
        "  <MessageName>" & _
        "		<Name>LoaderSetArmExtendRetractStatusInProcessScreenTo</Name>" & _
        "		<Code>SL_ProcessPanel.slArmExtendStatus</Code>" & _
        "	</MessageName>" & _
        "	<MessageName>" & _
        "		<Name>ChangeAutoLoadStatusInSLProcessScreenTo</Name>" & _
        "		<Code>SL_ProcessPanel.btnAutoLoad</Code>" & _
        "	</MessageName>" & _
        "	<MessageName>" & _
        "		<Name>ChangeAutoUnloadStatusInSLProcessScreenTo</Name>" & _
        "		<Code>SL_ProcessPanel.btnAutoUnload</Code>" & _
        "	</MessageName>" & _
        "	<MessageName>" & _
        "		<Name>LoaderSetIsolationValveStatusInProcessScreenTo</Name>" & _
        "		<Code>SL_ProcessPanel.slOpenIsoValveStatus</Code>" & _
        "	</MessageName>" & _
        "	<MessageName>" & _
        "		<Name>LoaderSetDoorStatusInProcessScreenTo</Name>" & _
        "		<Code>SL_ProcessPanel.SLDoorClose</Code>" & _
        "	</MessageName>" & _
        "	<MessageName>" & _
        "		<Name>LoaderSetVentValveStatusInProcessScreenTo</Name>" & _
        "		<Code>SL_ProcessPanel.slOpenVentValveStatus</Code>" & _
        "	</MessageName>" & _
        "	<MessageName>" & _
        "		<Name>LoaderSetRoughValveStatusInProcessScreenTo</Name>" & _
        "		<Code>SL_ProcessPanel.slOpenRoughValveStatus</Code>" & _
        "	</MessageName>" & _
        "	<MessageName>" & _
        "		<Name>SetLoaderArmPressureStatusTo</Name>" & _
        "		<Code>SL_ProcessPanel.SLArm.txtInformation</Code>" & _
        "	</MessageName>" & _
        "	<MessageName>" & _
        "		<Name>SetDataOutputStatusTo</Name>" & _
        "		<Code>SL_ProcessPanel.SLDataOutput.txtInformation</Code>" & _
        "	</MessageName>" & _
        "	<MessageName>" & _
        "		<Name>SetLoaderAutoPumpDownStatusTo</Name>" & _
        "		<Code>SL_ProcessPanel.slAutoPumpDownStatus</Code>" & _
        "	</MessageName>" & _
        "	<MessageName>" & _
        "		<Name>SetLoaderAutoVentStatusTo</Name>" & _
        "		<Code>SL_ProcessPanel.slAutoVentStatus</Code>" & _
        "	</MessageName>" & _
        " 	<MessageName>" & _
        "		<Name>SetLoaderAutoLoadStatusTo</Name>" & _
        "		<Code>SL_ProcessPanel.slAutoLoadStatus</Code>" & _
        "	</MessageName>" & _
        "	<MessageName>" & _
        "		<Name>SetLoaderAutoUnloadStatusTo</Name>" & _
        "		<Code>SL_ProcessPanel.slAutoUnloadStatus</Code>" & _
        "	</MessageName> " & _
        "	<MessageName>" & _
        "		<Name>SetLoaderLoadStatusTo</Name>" & _
        "		<Code>SL_ProcessPanel.slLoadStatus</Code>" & _
        "	</MessageName> " & _
        "	<!--Process Panel-->" & _
        "	<MessageName>" & _
        "    <Name>TotalWaferCountOfLoader</Name>" & _
        "    <Code>SL_ProcessPanel.wccWaferCount.txtTotal</Code>" & _
        "  </MessageName>" & _
        "	<MessageName>" & _
        "    <Name>SetIBEFixtureOnClamp</Name>" & _
        "    <Code>SL_ProcessModule.SLFixture.btnClampDown</Code>" & _
        "  </MessageName>" & _
        "	<MessageName>" & _
        "    <Name>SetRunStatusInProcessScreen</Name>" & _
        "    <Code>SL_ProcessPanel.SLProcessControl.txtRunningStatus</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetStopStatusInProcessScreen</Name>" & _
        "    <Code>SL_ProcessPanel.SLProcessControl.txtStopStatus</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetStatusOfIBEInProcessScreenTo</Name>" & _
        "    <Code>SL_ProcessPanel.SLProcessControl.txtAbortStatus</Code>" & _
        "  </MessageName>" & _
        "	<MessageName>" & _
        "    <Name>SetIGOfIBETo</Name>" & _
        "    <Code>SL_ProcessPanel.txtIG</Code>" & _
        "    <OutputType>Scientific</OutputType>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIGInProcessPanelTo</Name>" & _
        "    <Code>SL_ProcessPanel.SLPM.txtInformation</Code>" & _
        "    <OutputType>Scientific</OutputType>" & _
        "  </MessageName>" & _
        "	<MessageName>" & _
        "    <Name>SetInitializeMotionIBEInProcessPanelTo</Name>" & _
        "    <Code>SL_ProcessPanel.SLFixture.btnMotionInitialized</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetFlowcoolGasIBEInProcessPanelTo</Name>" & _
        "    <Code>SL_ProcessPanel.SLFixture.btnFlowCoolGas</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetProcessGasIBEInProcessPanelTo</Name>" & _
        "    <Code>SL_ProcessPanel.SLFixture.btnProcessGas</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIonBeamIBEInProcessPanelTo</Name>" & _
        "    <Code>SL_ProcessPanel.SLFixture.btnIonBeam</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetPBNOKIBEInProcessPanelTo</Name>" & _
        "    <Code>SL_ProcessPanel.SLFixture.btnNeutralizer</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBERFPowerSupply_SetForwardPowerInProcessPanelTo</Name>" & _
        "    <Code>SL_ProcessPanel.txtForwardRFPower</Code>" & _
        "    <OutputType>Decimal</OutputType>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEBeamPowerSupply_SetCurrentInProcessPanelTo</Name>" & _
        "    <Code>SL_ProcessPanel.txtBeamCurrent</Code>" & _
        "    <OutputType>Decimal</OutputType>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBESuppressorPowerSupply_SetVoltageInProcessPanelTo</Name>" & _
        "    <Code>SL_ProcessPanel.txtSuppressorVoltage</Code>" & _
        "    <OutputType>Decimal</OutputType>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEBeamPowerSupply_SetVoltageInProcessPanelTo</Name>" & _
        "    <Code>SL_ProcessPanel.txtBeamVoltage</Code>" & _
        "    <OutputType>Decimal</OutputType>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEBodyPowerSupply_SetCurrentInProcessPanelTo</Name>" & _
        "    <Code>SL_ProcessPanel.txtPBNBody</Code>" & _
        "    <OutputType>Decimal</OutputType>" & _
        "  </MessageName>" & _
        "   <MessageName>" & _
        "    <Name>SetIBEDischargePowerSupply_SetCurrentInProcessPanelTo</Name>" & _
        "    <Code>SL_ProcessPanel.txtPBNCurrent</Code>" & _
        "    <OutputType>Decimal</OutputType>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEProcessMonitorInProcessPanel_RecipeTo</Name>" & _
        "    <Code>SL_ProcessPanel.txtRecipe</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBETempertureInProcessPanelTo</Name>" & _
        "    <Code>SL_ProcessPanel.txtCryoTemp</Code>" & _
        "    <OutputType>Scientific</OutputType>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEShutterPositionInProcessPanel</Name>" & _
        "    <Code>SL_ProcessPanel.PMControl.bicShutter</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEChangeInterlocksFixureWaterInProcessPanelTo</Name>" & _
        "    <Code>SL_ProcessPanel.SLInterlocks.btnFixtureWater</Code>" & _
        "  </MessageName>" & _
        "   <MessageName>" & _
        "    <Name>SetIBEChangeInterlocksTurboWaterInProcessPanelTo</Name>" & _
        "    <Code>SL_ProcessPanel.SLInterlocks.btnTurboWater</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEChangeInterlocksAirPressureInProcessPanelTo</Name>" & _
        "    <Code>SL_ProcessPanel.SLInterlocks.btnAirPressure</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEChangeInterlocksChamberPressInProcessPanelTo</Name>" & _
        "    <Code>SL_ProcessPanel.SLInterlocks.btnChamPress</Code>" & _
        "  </MessageName>" & _
        "   <MessageName>" & _
        "    <Name>SetIBEChangeInterlocksPanelInProcessPanelTo</Name>" & _
        "    <Code>SL_ProcessPanel.SLInterlocks.btnPanels</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEChangeInterlocksSourceWaterInProcessPanelTo</Name>" & _
        "    <Code>SL_ProcessPanel.SLInterlocks.btnSource</Code>" & _
        "  </MessageName>" & _
        "   <MessageName>" & _
        "    <Name>SetIBEChangeInterlocksForelineInProcessPanelTo</Name>" & _
        "    <Code>SL_ProcessPanel.SLInterlocks.btnForelinePress</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEChangeInterlocksFixtureRotationInProcessPanelTo</Name>" & _
        "    <Code>SL_ProcessPanel.SLInterlocks.btnFixtureRotation</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetMnuRoughPumpIBEInProcessPanelTo</Name>" & _
        "    <Code>SL_ProcessPanel.RoughPumpControl</Code>" & _
        "  </MessageName>" & _
        "   <MessageName>" & _
        "    <Name>SetWaferInsideChamberInSLProcessScreenTo</Name>" & _
        "    <Code>SL_ProcessPanel.PMControl.WFControl</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBE_WaferStatusInSLProcessScreenTo</Name>" & _
        "    <Code>SL_ProcessPanel.PMControl.WFControl</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetAnimateRobotInSLProcessScreen</Name>" & _
        "    <Code>SL_ProcessPanel.LoaderRobot</Code>" & _
        "  </MessageName>" & _
        "   <MessageName>" & _
        "    <Name>SetIBEProcessMonitor_ProcessStepInProcessPanelTo</Name>" & _
        "    <Code>SL_ProcessPanel.txtStepNumber</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetCGOfIBETo</Name>" & _
        "    <Code>SL_ProcessPanel.txtCG</Code>" & _
        "    <OutputType>Scientific</OutputType>" & _
        "  </MessageName>" & _
        "   <MessageName>" & _
        "    <Name>ChangeMachineOnlineInIBETo</Name>" & _
        "    <Code>SL_ProcessPanel.SLSystemControl.btnOnline</Code>" & _
        "  </MessageName>" & _
        "   <MessageName>" & _
        "    <Name>SetIBE_ConnectionStatusTo</Name>" & _
        "    <Code>SL_ProcessPanel.btnReConnect</Code>" & _
        "  </MessageName>" & _
        "  <!--Process Module-->" & _
        " <MessageName>" & _
        "    <Name>SetMnuCryoPumpRegenIBETo</Name>" & _
        "    <Code>SL_PopUpPanel.btnCryoRegenValve</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetMnuCryoAutoRegenIBETo</Name>" & _
        "    <Code>SL_PopUpPanel.btnAutoRegen</Code>" & _
        "  </MessageName>" & _
        "   <MessageName>" & _
        "    <Name>SetMnuCryoAutoPowerDownIBETo</Name>" & _
        "    <Code>SL_PopUpPanel.btnAutoPowerDown</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetMnuCryoPumpPurgeIBETo</Name>" & _
        "    <Code>SL_PopUpPanel.btnCryoPurge</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetMnuCryoRateOfRiseIBETo</Name>" & _
        "    <Code>SL_PopUpPanel.btnRateOfRise</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetMnuWaterPumpTo</Name>" & _
        "    <Code>SL_PopUpPanel.btnWaterPumpOnOff</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetMnuWaterPumpRegenTo</Name>" & _
        "    <Code>SL_PopUpPanel.btnWaterPumpRegen</Code>" & _
        "  </MessageName>" & _
        "   <MessageName>" & _
        "    <Name>SetMnuPumpDownIBETo</Name>" & _
        "    <Code>SL_PopUpPanel.btnAutoPumpDownGeneral</Code>" & _
        "  </MessageName>" & _
        "      <MessageName>" & _
        "    <Name>SetIBEMenuValveWaterPump</Name>" & _
        "    <Code>SL_PopUpPanel.btnWaterPumpOnOff</Code>" & _
        "  </MessageName>" & _
        "   <MessageName>" & _
        "    <Name>SetIBEWaterPumpRegen</Name>" & _
        "    <Code>SL_PopUpPanel.btnWaterPumpRegen</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetMnuCryoIBETo</Name>" & _
        "    <Code>SL_PopUpPanel.btnCryoOnOff</Code>" & _
        "  </MessageName>" & _
        "   <MessageName>" & _
        "    <Name>SetMnuVentIBETo</Name>" & _
        "    <Code>SL_PopUpPanel.btnAutoVentGeneral</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEChangeInterlocksFixureWaterInProcessModuleTo</Name>" & _
        "    <Code>SL_ProcessModule.SLInterlocks.btnFixtureWater</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEChangeInterlocksTurboWaterInProcessModuleTo</Name>" & _
        "    <Code>SL_ProcessModule.SLInterlocks.btnTurboWater</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEChangeInterlocksAirPressureInProcessModuleTo</Name>" & _
        "    <Code>SL_ProcessModule.SLInterlocks.btnAirPressure</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEChangeInterlocksChamberPressInProcessModuleTo</Name>" & _
        "    <Code>SL_ProcessModule.SLInterlocks.btnChamPress</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEChangeInterlocksPanelInProcessModuleTo</Name>" & _
        "    <Code>SL_ProcessModule.SLInterlocks.btnPanels</Code>" & _
        "  </MessageName>" & _
        "   <MessageName>" & _
        "    <Name>SetIBEChangeInterlocksSourceWaterInProcessModuleTo</Name>" & _
        "    <Code>SL_ProcessModule.SLInterlocks.btnSource</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEChangeInterlocksForelineInProcessModuleTo</Name>" & _
        "    <Code>SL_ProcessModule.SLInterlocks.btnForelinePress</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEChangeInterlocksFixtureRotationInProcessModuleTo</Name>" & _
        "    <Code>SL_ProcessModule.SLInterlocks.btnFixtureRotation</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetACPowerIBETo</Name>" & _
        "    <Code>SL_ProcessModule.SLPowerPanel.btnACPower</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetRFPowerIBETo</Name>" & _
        "    <Code>SL_ProcessModule.SLPowerPanel.btnRFPower</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetGridPowerIBETo</Name>" & _
        "    <Code>SL_ProcessModule.SLPowerPanel.btnGrid</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetPBNPowerIBETo</Name>" & _
        "    <Code>SL_ProcessModule.SLPowerPanel.btnPBN</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetSourceManualIBETo</Name>" & _
        "    <Code>SL_ProcessModule.btnSourceManual</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetSourceAutoIBETo</Name>" & _
        "    <Code>SL_ProcessModule.btnSourceAuto</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetInitializeMotionIBEInProcessModuleTo</Name>" & _
        "    <Code>SL_ProcessModule.SLStatusPanel.btnMotionInitialized</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetFlowcoolGasIBEInProcessModuleTo</Name>" & _
        "    <Code>SL_ProcessModule.SLStatusPanel.btnFlowCoolGas</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetProcessGasIBEInProcessModuleTo</Name>" & _
        "    <Code>SL_ProcessModule.SLStatusPanel.btnProcessGas</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIonBeamIBEInProcessModuleTo</Name>" & _
        "    <Code>SL_ProcessModule.SLStatusPanel.btnIonBeam</Code>" & _
        "  </MessageName>" & _
        "   <MessageName>" & _
        "    <Name>SetPlasmaInProcessModuleTo</Name>" & _
        "    <Code>SL_ProcessModule.SLContainerBox.SourcePlasma</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetPBNOKIBEInProcessModuleTo</Name>" & _
        "    <Code>SL_ProcessModule.SLStatusPanel.btnNeutralizer</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBERFPowerSupply_SetForwardPowerInProcessModuleTo</Name>" & _
        "    <Code>SL_ProcessModule.txtRFPower</Code>" & _
        "    <OutputType>Decimal</OutputType>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBERFPowerSupply_SetReflectedPowerInProcessModuleTo</Name>" & _
        "    <Code>SL_ProcessModule.txtRFReflected</Code>" & _
        "    <OutputType>Decimal</OutputType>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBERFPowerSupply_SetReflectedPowerRightTo</Name>" & _
        "    <Code>SL_ProcessModule.txtRFReflectedRight</Code>" & _
        "    <OutputType>Decimal</OutputType>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBERFPowerSupply_ForwardPowerRight</Name>" & _
        "    <Code>SL_ProcessModule.txtRFPowerRight</Code>" & _
        "    <OutputType>Decimal</OutputType>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEBeamPowerSupply_SetCurrentInProcessModuleTo</Name>" & _
        "    <Code>SL_ProcessModule.txtBeamCurrent</Code>" & _
        "    <OutputType>Decimal</OutputType>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEBeamPowerSupply_SetCurrentRightTo</Name>" & _
        "    <Code>SL_ProcessModule.txtBeamCurrentRight</Code>" & _
        "    <OutputType>Decimal</OutputType>" & _
        "  </MessageName> " & _
        "  <MessageName>" & _
        "    <Name>SetIBEBeamPowerSupply_SetVoltageInProcessModuleTo</Name>" & _
        "    <Code>SL_ProcessModule.txtBeamVoltage</Code>" & _
        "    <OutputType>Decimal</OutputType>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEBeamPowerSupply_VoltageRight</Name>" & _
        "    <Code>SL_ProcessModule.txtBeamVoltageRight</Code>" & _
        "    <OutputType>Decimal</OutputType>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBESuppressorPowerSupply_SetVoltageInProcessModuleTo</Name>" & _
        "    <Code>SL_ProcessModule.txtSuppressorVoltage</Code>" & _
        "    <OutputType>Decimal</OutputType>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBESuppressorPowerSupply_VoltageRight</Name>" & _
        "    <Code>SL_ProcessModule.txtSuppressorVoltageRight</Code>" & _
        "    <OutputType>Decimal</OutputType>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBESuppressorPowerSupply_SetCurrentInProcessModuleTo</Name>" & _
        "    <Code>SL_ProcessModule.txtSuppressorCurrent</Code>" & _
        "    <OutputType>Decimal</OutputType>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBESuppressorPowerSupply_SetCurrentRightTo</Name>" & _
        "    <Code>SL_ProcessModule.txtSuppressorCurrentRight</Code>" & _
        "    <OutputType>Decimal</OutputType>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEBodyPowerSupply_SetCurrentInProcessModuleTo</Name>" & _
        "    <Code>SL_ProcessModule.txtPBNBody</Code>" & _
        "    <OutputType>Decimal</OutputType>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEBodyPowerSupply_SetKFactorTo</Name>" & _
        "    <Code>SL_ProcessModule.txtKFactor</Code>" & _
        "    <OutputType>Decimal</OutputType>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEBodyPowerSupply_SetKFactorRightTo</Name>" & _
        "    <Code>SL_ProcessModule.txtKFactorRight</Code>" & _
        "    <OutputType>Decimal</OutputType>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEDischargePowerSupply_SetCurrentInProcessModuleTo</Name>" & _
        "    <Code>SL_ProcessModule.txtPBNDisch</Code>" & _
        "    <OutputType>Decimal</OutputType>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBECGCFLCG_SetInformationTo</Name>" & _
        "    <Code>SL_ProcessModule.txtForelineCG</Code>" & _
        "    <OutputType>Scientific</OutputType>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBECGCRLCG_SetInformationTo</Name>" & _
        "    <Code>SL_ProcessModule.txtRoughlineCG</Code>" & _
        "    <OutputType>Scientific</OutputType>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBECGCMG_SetInformationTo</Name>" & _
        "    <Code>SL_ProcessModule.txtMG</Code>" & _
        "    <OutputType>Scientific</OutputType>" & _
        "  </MessageName>" & _
        "   <MessageName>" & _
        "    <Name>SetIBETempertureInProcessModuleTo</Name>" & _
        "    <Code>SL_ProcessModule.SLContainerBox.txtT1</Code>" & _
        "    <OutputType>Scientific</OutputType>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBETempertureT2To</Name>" & _
        "    <Code>SL_ProcessModule.SLContainerBox.txtT2</Code>" & _
        "    <OutputType>Scientific</OutputType>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEFixtureControlContinuous_SetTiltAngleTo</Name>" & _
        "    <Code>SL_ProcessModule.SLFixture.txtTiltAngleContinuousLeft</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEFixtureControlContinuous_SetRotationTo</Name>" & _
        "    <Code>SL_ProcessModule.SLFixture.txtRotationContinuousLeft</Code>" & _
        "  </MessageName>  " & _
        "     <MessageName>" & _
        "    <Name>SetIBEFixture_HomeTiltStatusTo</Name>" & _
        "    <Code>SL_ProcessModule.SLFixture.stHomeTilt</Code>" & _
        "  </MessageName>" & _
        "     <MessageName>" & _
        "    <Name>SetIBEFixture_HomeRotationStatusTo</Name>" & _
        "    <Code>SL_ProcessModule.SLFixture.stHomeRotation</Code>" & _
        "  </MessageName>" & _
        "     <MessageName>" & _
        "    <Name>SetIBEFixture_StartRotationStatusTo</Name>" & _
        "    <Code>SL_ProcessModule.SLFixture.stStartRotation</Code>" & _
        "  </MessageName>" & _
        "   <MessageName>" & _
        "    <Name>SetIBE_FixtureStartRotationForMenuTo</Name>" & _
        "    <Code>SL_ProcessModule.SLFixture.btnRotate</Code>" & _
        "  </MessageName>" & _
        "     <MessageName>" & _
        "    <Name>SetIBEFixture_InitializeMotionStatusTo</Name>" & _
        "    <Code>SL_ProcessModule.SLFixture.btnMotionInitialized</Code>" & _
        "  </MessageName>  " & _
        "  <MessageName>" & _
        "    <Name>SetIBEGasController_PBNRight</Name>" & _
        "    <Code>SL_ProcessModule.txtPBNGasRight</Code>" & _
        "    <OutputType>Decimal</OutputType>" & _
        "  </MessageName>" & _
        "   <MessageName>" & _
        "    <Name>SetIBEGasController_PBNRight_SourceTab</Name>" & _
        "    <Code>SL_ProcessModule.txtPBNGasRight_SourceTab</Code>" & _
        "    <OutputType>Decimal</OutputType>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEGasController_FlowCoolHeRight</Name>" & _
        "    <Code>SL_ProcessModule.SLFixture.txtFlowCoolGasRight</Code>" & _
        "    <OutputType>Decimal</OutputType>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEGas1ProgramTo</Name>" & _
        "    <Code>SL_ProcessModule.txtGas1Right</Code>" & _
        "    <OutputType>Decimal</OutputType>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEGas2ProgramTo</Name>" & _
        "    <Code>SL_ProcessModule.txtGas2Right</Code>" & _
        "    <OutputType>Decimal</OutputType>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEGas3ProgramTo</Name>" & _
        "    <Code>SL_ProcessModule.txtGas3Right</Code>" & _
        "    <OutputType>Decimal</OutputType>" & _
        "  </MessageName>" & _
        "   <MessageName>" & _
        "    <Name>SetIBEGas1ReadbackTo</Name>" & _
        "    <Code>SL_ProcessModule.txtGas1</Code>" & _
        "    <OutputType>Decimal</OutputType>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEGas2ReadbackTo</Name>" & _
        "    <Code>SL_ProcessModule.txtGas2</Code>" & _
        "    <OutputType>Decimal</OutputType>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEGas3ReadbackTo</Name>" & _
        "    <Code>SL_ProcessModule.txtGas3</Code>" & _
        "    <OutputType>Decimal</OutputType>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEGas1ProgramSourceTabTo</Name>" & _
        "    <Code>SL_ProcessModule.txtGas1Right_SourceTab</Code>" & _
        "    <OutputType>Decimal</OutputType>" & _
        "  </MessageName>" & _
        "   <MessageName>" & _
        "    <Name>SetIBEGas2ProgramSourceTabTo</Name>" & _
        "    <Code>SL_ProcessModule.txtGas2Right_SourceTab</Code>" & _
        "    <OutputType>Decimal</OutputType>" & _
        "  </MessageName>" & _
        "   <MessageName>" & _
        "    <Name>SetIBEGas1ReadbackSourceTabTo</Name>" & _
        "    <Code>SL_ProcessModule.txtGas1_SourceTab</Code>" & _
        "    <OutputType>Decimal</OutputType>" & _
        "  </MessageName>" & _
        "   <MessageName>" & _
        "    <Name>SetIBEGas2ReadbackSourceTabTo</Name>" & _
        "    <Code>SL_ProcessModule.txtGas2_SourceTab</Code>" & _
        "    <OutputType>Decimal</OutputType>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetProcessPanel_Gas1ReadbackSourceTabTo</Name>" & _
        "    <Code>SL_ProcessPanel.txtGas1_SourceTab</Code>" & _
        "    <OutputType>Decimal</OutputType>" & _
        "  </MessageName>" & _
        "   <MessageName>" & _
        "    <Name>SetProcessPanel_Gas2ReadbackSourceTabTo</Name>" & _
        "    <Code>SL_ProcessPanel.txtGas2_SourceTab</Code>" & _
        "    <OutputType>Decimal</OutputType>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEGasController_SetPBNTo</Name>" & _
        "    <Code>SL_ProcessModule.txtPBNGas</Code>" & _
        "    <OutputType>Decimal</OutputType>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEGasController_SetPBNTo_SourceTab</Name>" & _
        "    <Code>SL_ProcessModule.txtPBNGas_SourceTab</Code>" & _
        "    <OutputType>Decimal</OutputType>" & _
        "  </MessageName>" & _
        "   <MessageName>" & _
        "    <Name>SetProcessScreen_SetPBNTo</Name>" & _
        "    <Code>SL_ProcessPanel.txtPBNGas_SourceTab</Code>" & _
        "    <OutputType>Decimal</OutputType>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEGasController_SetFlowCoolHeTo</Name>" & _
        "    <Code>SL_ProcessModule.SLFixture.txtFlowCoolGas</Code>" & _
        "    <OutputType>Decimal</OutputType>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEFixtureControlStatic_SetRotationTo</Name>" & _
        "    <Code>SL_ProcessModule.SLFixture.txtRotationStaticLeft</Code>" & _
        "  </MessageName>" & _
        "   <MessageName>" & _
        "    <Name>SetIBEProcessMonitorInProcessModule_RecipeTo</Name>" & _
        "    <Code>SL_ProcessModule.txtRecipe</Code>" & _
        "  </MessageName>" & _
        "   <MessageName>" & _
        "    <Name>SetIBEProcessMonitor_RemainingTimeTo</Name>" & _
        "    <Code>SL_ProcessModule.txtRemainingTime</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEProcessMonitor_ElapsedTimeTo</Name>" & _
        "    <Code>SL_ProcessModule.txtElapsedTime</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetProcessScreen_RemainingTimeTo</Name>" & _
        "    <Code>SL_ProcessPanel.txtRemainingTime</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetProcessScreen_ElapsedTimeTo</Name>" & _
        "    <Code>SL_ProcessPanel.txtElapsedTime</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEProcessMonitor_ProcessStepInProcessModuleTo</Name>" & _
        "    <Code>SL_ProcessModule.txtProcessStep</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEProcessMonitor_WaferID</Name>" & _
        "    <Code>SL_ProcessModule.txtWaferID</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBERemainingTimeTo</Name>" & _
        "    <Code>SL_ProcessModule.txtRemainingTime</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEValveSupplyPBN</Name>" & _
        "    <Code>SL_ProcessModule.ValveSupplyPBNGas</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEValveSupplyFlowCoolHe</Name>" & _
        "    <Code>SL_ProcessModule.SLFixture.ValveSupplyFlowCoolGas</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEMenuValveCryoPump</Name>" & _
        "    <Code>SL_PopUpPanel.mnuCryoGate</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEValveCryoPump</Name>" & _
        "    <Code>SL_ProcessModule.SLContainerBox.ValveCryoHivac</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEShutterPositionInProcessModule</Name>" & _
        "    <Code>SL_ProcessModule.SLContainerBox.Shutter</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEShutterInFixture</Name>" & _
        "    <Code>SL_ProcessModule.SLFixture.btnShutterOpen</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEValveWaterPump</Name>" & _
        "    <Code>SL_ProcessModule.SLContainerBox.btnWaterPumpOn</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEHiVacValveStatus</Name>" & _
        "    <Code>SL_ProcessModule.SLContainerBox.ValveTurboHivac</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEVentValveStatus</Name>" & _
        "    <Code>SL_ProcessModule.ValveVent</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBERoughValveStatus</Name>" & _
        "    <Code>SL_ProcessModule.ValveRough</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEPBNValveStatus</Name>" & _
        "    <Code>SL_ProcessModule.ValveShutoffPBNGas</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEForelineValveStatus</Name>" & _
        "    <Code>SL_ProcessModule.ValveForeline</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEFlowCoolHeValveStatus</Name>" & _
        "    <Code>SL_ProcessModule.SLFixture.ValveShutoffFlowCoolGas</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEMenuFixtureOpenWaterValve</Name>" & _
        "    <Code>SL_ProcessModule.mnuCoolingWater</Code>" & _
        "  </MessageName>" & _
        "   <MessageName>" & _
        "    <Name>SetIBEFixtureOpenWaterValve</Name>" & _
        "    <Code>SL_ProcessModule.ValveFixtureWater</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEFixtureOpenFlowCool</Name>" & _
        "    <Code>SL_ProcessModule.SLFixture.btnFlowCoolPump</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEFixtureUnProtected</Name>" & _
        "    <Code>SL_ProcessModule.mnuUnProtected</Code>" & _
        "  </MessageName>" & _
        "   <MessageName>" & _
        "    <Name>SetButtonCryoIBETo</Name>" & _
        "    <Code>SL_ProcessModule.SLContainerBox.btnCryoOn</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetMnuRoughPumpIBEInProcessModuleTo</Name>" & _
        "    <Code>SL_ProcessModule.RoughPump</Code>" & _
        "  </MessageName>" & _
        "	<MessageName>" & _
        "    <Name>ShowStatusMessage</Name>" & _
        "    <Code>SL_ProcessModule.lblStatusText</Code>" & _
        "  </MessageName>" & _
        "  	<MessageName>" & _
        "    <Name>ShowStatusMessageInSLProcessScreen</Name>" & _
        "    <Code>SL_ProcessPanel.lblStatusText</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEGas1SupplyValveStatus</Name>" & _
        "    <Code>SL_ProcessModule.ValveSupplyGas1</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEGas2SupplyValveStatus</Name>" & _
        "    <Code>SL_ProcessModule.ValveSupplyGas2</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEGas3SupplyValveStatus</Name>" & _
        "    <Code>SL_ProcessModule.ValveSupplyGas3</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEGas1ShutOffValveStatus</Name>" & _
        "    <Code>SL_ProcessModule.ValveShutoffGas1</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEGas2ShutOffValveStatus</Name>" & _
        "    <Code>SL_ProcessModule.ValveShutoffGas2</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEGas3ShutOffValveStatus</Name>" & _
        "    <Code>SL_ProcessModule.ValveShutoffGas3</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIGInProcessModuleTo</Name>" & _
        "    <Code>SL_ProcessModule.SLIGCGControl.txtIG</Code>" & _
        "    <OutputType>Scientific</OutputType>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetCGInProcessModuleTo</Name>" & _
        "    <Code>SL_ProcessModule.SLIGCGControl.txtCG</Code>" & _
        "    <OutputType>Scientific</OutputType>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEBeamPowerSupply_AutoBeam</Name>" & _
        "    <Code>SL_ProcessModule.btnAutoBeam</Code>" & _
        "  </MessageName>" & _
        "   <MessageName>" & _
        "    <Name>SetIBEFixtureControlSweep_RotationEndRight</Name>" & _
        "    <Code>SL_ProcessModule.SLFixture.txtRotationEnd</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEFixtureControl_TiltAngleRight</Name>" & _
        "    <Code>SL_ProcessModule.SLFixture.txtTiltAngleRight</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEFixtureControl_SetTiltAngleTo</Name>" & _
        "    <Code>SL_ProcessModule.SLFixture.txtTiltAngleLeft</Code>" & _
        "  </MessageName>" & _
        "    <MessageName>" & _
        "    <Name>SetProcessPanel_FixtureControl_SetTiltAngleTo</Name>" & _
        "    <Code>SL_ProcessPanel.SLFixture.txtTiltAngle</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEFixtureControlSweep_TiltAngleRight</Name>" & _
        "    <Code>SL_ProcessModule.SLFixture.txtTiltAngleRight</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEFixtureControlSweep_SetRotationStartTo</Name>" & _
        "    <Code>SL_ProcessModule.SLFixture.txtRotationSweepLeft</Code>" & _
        "  </MessageName>" & _
        "   <MessageName>" & _
        "    <Name>SetIBEFixtureControlSweep_RotationRight</Name>" & _
        "    <Code>SL_ProcessModule.SLFixture.txtRotationSweepRight</Code>" & _
        "  </MessageName> " & _
        "   <MessageName>" & _
        "    <Name>SetIBEFixtureControlContinuous_RotationRight</Name>" & _
        "    <Code>SL_ProcessModule.SLFixture.txtRotationContinuousRight</Code>" & _
        "  </MessageName> " & _
        "   <MessageName>" & _
        "    <Name>SetIBEFixtureControlStatic_TiltAngleRight</Name>" & _
        "    <Code>SL_ProcessModule.SLFixture.txtTiltAngleStaticRight</Code>" & _
        "  </MessageName>" & _
        "   <MessageName>" & _
        "    <Name>SetIBEFixtureControlStatic_RotationRight</Name>" & _
        "    <Code>SL_ProcessModule.SLFixture.txtRotationStaticRight</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEFixtureControlStatic_SetTiltAngleTo</Name>" & _
        "    <Code>SL_ProcessModule.SLFixture.txtTiltAngleStaticLeft</Code>" & _
        "  </MessageName>" & _
        "   <MessageName>" & _
        "    <Name>SetIBEFixtureControlContinuous_TiltAngleRight</Name>" & _
        "    <Code>SL_ProcessModule.SLFixture.txtTiltAngleContinuousRight</Code>" & _
        "  </MessageName>" & _
        "   <MessageName>" & _
        "    <Name>SetIBE_ConnectionStatusInProcessModuleTo</Name>" & _
        "    <Code>SL_ProcessModule.btnReConnect</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEProcessMonitor_TotalStepTo</Name>" & _
        "    <Code>SL_ProcessModule.txtTotalStep</Code>" & _
        "  </MessageName>" & _
        "  " & _
        "  <MessageName>" & _
        "    <Name>SetIBEChamber_ProcessMonitor_SetDeviceStartTo</Name>" & _
        "    <Code>SL_ProcessModule.SLRunRecipe.btnStart</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEChamber_ProcessMonitor_SetDeviceStopTo</Name>" & _
        "    <Code>SL_ProcessModule.SLRunRecipe.btnStart</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEChamber_ProcessMonitor_SetDevicePauseTo</Name>" & _
        "    <Code>SL_ProcessModule.SLRunRecipe.btnPause</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEChamber_ProcessMonitor_SetDeviceContinueTo</Name>" & _
        "    <Code>SL_ProcessModule.SLRunRecipe.btnPause</Code>" & _
        "  </MessageName>" & _
        "  <!--System Setup-->" & _
        "   <MessageName>" & _
        "    <Name>SetSourceUsageTimeIBETo</Name>" & _
        "    <Code>SL_SystemSetup.txtSourceUsage</Code>" & _
        "  </MessageName>" & _
        "  <!--End Single Loader  -->" & _
        "  " & _
        "  <MessageName>" & _
        "    <Name>SetIBEBodyPowerSupply_CurrentRight</Name>" & _
        "    <Code>IBE.dpsBodyPowerSupply.txtCurrentRight</Code>" & _
        "    <OutputType>Decimal</OutputType>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>ChangeButtonIGOfIBETo</Name>" & _
        "    <Code>IBE.BaCenterControl.bigcgIG</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEFixtureControlSweep_ChangeSmallCricleControlErrorTo</Name>" & _
        "    <Code>IBE.ftcFixtureControlSweep.sccFixtureError</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEFixtureControlSweep_ChangeSmallCricleControlTiltRotationTo</Name>" & _
        "    <Code>IBE.ftcFixtureControlSweep.SmallCricleControlTiltRotation</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEFixtureControlSweep_ChangeSmallCricleControlTiltAngleTo</Name>" & _
        "    <Code>IBE.ftcFixtureControlSweep.SmallCricleControlTiltAngle</Code>" & _
        "  </MessageName>" & _
        " <MessageName>" & _
        "    <Name>ChangeSlitValeOfIBETo</Name>" & _
        "    <Code>IBE.ValveControlMesa</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>ChangeButtonIBEMachineOnlineInChamberScreenTo</Name>" & _
        "    <Code>IBE.btnTooltipMachine</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEFixtureControlStatic_ChangeSmallCricleControlErrorTo</Name>" & _
        "    <Code>IBE.ftcFixtureControlStatic.sccFixtureError</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEFixtureControlStatic_ChangeSmallCricleControlTiltRotationTo</Name>" & _
        "    <Code>IBE.ftcFixtureControlStatic.SmallCricleControlTiltRotation</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEFixtureControlStatic_ChangeSmallCricleControlTiltAngleTo</Name>" & _
        "    <Code>IBE.ftcFixtureControlStatic.SmallCricleControlTiltAngle</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEFixtureControlStatic_RotationLastRight</Name>" & _
        "    <Code>IBE.ftcFixtureControlStatic.txtRotationLastRight</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEFixtureControlContinuous_ChangeSmallCricleControlErrorTo</Name>" & _
        "    <Code>IBE.ftcFixtureControlContinuous.sccFixtureError</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEFixtureControlContinuous_ChangeSmallCricleControlTiltRotationTo</Name>" & _
        "    <Code>IBE.ftcFixtureControlContinuous.SmallCricleControlTiltRotation</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEFixtureControlContinuous_ChangeSmallCricleControlTiltAngleTo</Name>" & _
        "    <Code>IBE.ftcFixtureControlContinuous.SmallCricleControlTiltAngle</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEFixtureControlContinuous_RotationLastRight</Name>" & _
        "    <Code>IBE.ftcFixtureControlContinuous.txtRotationLastRight</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEProcessMonitor_StepTimeTo</Name>" & _
        "    <Code>IBE.prmProcessMonitor.txtStepTime</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEProcessMonitor_StatusTo</Name>" & _
        "    <Code>IBE.prmProcessMonitor.txtStatus</Code>" & _
        "  </MessageName> " & _
        "  <MessageName>" & _
        "    <Name>SetIBEProcessRecipe_FinishProcessing</Name>" & _
        "    <Code>IBE.prcRunProcessRecipe.btnStart</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEWaferInFixtureTo</Name>" & _
        "    <Code>IBE.FixtureControl</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEScreenMachine</Name>" & _
        "    <Code>IBE.ScreenMachine</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEBaratronValveStatus</Name>" & _
        "    <Code>IBE.ValveControlBaratron</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBECryoPumpRegen</Name>" & _
        "    <Code>IBE.mnuMachineCryoPumpRegen</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBECryoAutoRegen</Name>" & _
        "    <Code>IBE.mnuMachineCryoAutoRegen</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEFixtureUnClamp</Name>" & _
        "    <Code>IBE.mnuFixtureUnClamp</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEFixtureStopAllAxis</Name>" & _
        "    <Code>IBE.mnuFixtureStopAllAxis</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEFixtureStartRotationAxis</Name>" & _
        "    <Code>IBE.mnuFixtureStartRotationAxis</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEFixtureHomeTiltAxis</Name>" & _
        "    <Code>IBE.mnuFixtureHomeTiltAxis</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEFixtureHomeRotationAxis</Name>" & _
        "    <Code>IBE.mnuFixtureHomeRotationAxis</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEFixtureHomeAllAxis</Name>" & _
        "    <Code>IBE.mnuFixtureHomeAllAxis</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEMachineVent</Name>" & _
        "    <Code>IBE.mnuMachineVent</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetIBEMachinePumpDown</Name>" & _
        "    <Code>IBE.mnuMachinePumpDown</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>StartAlarm</Name>" & _
        "    <Code>aplAlarm.tmrFlashAlarm</Code>" & _
        "  </MessageName>" & _
        "  <!-- Chamber 5-->" & _
        "  <MessageName>" & _
        "    <Name>ShowIBEStatusMessage</Name>" & _
        "    <Code>IBE.lblStatusText</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>ChangeButtonRFPowerIBETo</Name>" & _
        "    <Code>IBE.PowerStatusPanel.btnRFPower</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>ChangeButtonGridPowerIBETo</Name>" & _
        "    <Code>IBE.PowerStatusPanel.btnGrid</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>ChangeButtonPBNPowerIBETo</Name>" & _
        "    <Code>IBE.PowerStatusPanel.btnPBNPower</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>ChangeButtonACPowerIBETo</Name>" & _
        "    <Code>IBE.PowerStatusPanel.btnACPower</Code>" & _
        "  </MessageName>" & _
        "  <MessageName>" & _
        "    <Name>SetPVDChamber_ProcessControl_GetRunDataFileNameTo</Name>" & _
        "    <Code>WaferRun.btnRefresh</Code>" & _
        "  </MessageName>" & _
        "</MessageNames >"
    End Class
End Namespace
