'The following code was generated by Microsoft Visual Studio 2005.
'The test owner should check each test for validity.
Imports Microsoft.VisualStudio.TestTools.UnitTesting
Imports System
Imports System.Text
Imports System.Collections.Generic
Imports AVPLib
Imports AVPLibTest
Imports System.Xml

'''<summary>
'''This is a test class for AVPLib.AlignerRecipe and is intended
'''to contain all AVPLib.AlignerRecipe Unit Tests
'''</summary>
<TestClass()> _
Public Class AlignerRecipeTest

    Private testContextInstance As TestContext

    '''<summary>
    '''Gets or sets the test context which provides
    '''information about and functionality for the current test run.
    '''</summary>
    Public Property TestContext() As TestContext
        Get
            Return testContextInstance
        End Get
        Set(ByVal value As TestContext)
            testContextInstance = value
        End Set
    End Property

#Region "Additional test attributes"
    '
    'You can use the following additional attributes as you write your tests:
    '
    'Use ClassInitialize to run code before running the first test in the class
    '
    '<ClassInitialize()>  _
    'Public Shared Sub MyClassInitialize(ByVal testContext As TestContext)
    'End Sub
    '
    'Use ClassCleanup to run code after all tests in a class have run
    '
    '<ClassCleanup()>  _
    'Public Shared Sub MyClassCleanup()
    'End Sub
    '
    'Use TestInitialize to run code before running each test
    '
    '<TestInitialize()>  _
    'Public Sub MyTestInitialize()
    'End Sub
    '
    'Use TestCleanup to run code after each test has run
    '
    '<TestCleanup()>  _
    'Public Sub MyTestCleanup()
    'End Sub
    '
#End Region

    <ClassInitialize()> _
    Public Shared Sub MyClassInitialize(ByVal testContext As TestContext)
        AppDomain.CurrentDomain.SetData("APPBASE", "..\..\..\AVPLibTest\bin\TestData\DeltaPick\Aligner")
        AVPLib.Log.initialize()
    End Sub

    '''<summary>
    '''A test for Aligner Recipe.
    '''</summary>
    <TestMethod()> _
    Public Sub AlignerRecipeUnitTest()
        Dim fileName As String = "..\..\..\AVPLibTest\bin\TestData\DeltaPick\Aligner\STD.xml"

        Dim target As AlignerRecipe = New AlignerRecipe(fileName)

        Dim expectedValid As Boolean = True
        Assert.AreEqual(expectedValid, target.IsValid, "AVPLib.AlignerRecipe.IsValid did not return the expected value.")

        Dim expectedNumberOfSteps As Integer = 1
        Assert.AreEqual(expectedNumberOfSteps, target.NumberOfSteps, "AVPLib.AlignerRecipe.NumberOfSteps did not return the expected value.")

        Dim expectedPos As Integer = 0
        Dim actualPos As Integer = CInt(target.GetLongFromString(target.GetStepValue(1, "Angle"), 0))
        Assert.AreEqual(Of Integer)(expectedPos, actualPos, "AVPLib.AlignerRecipe.GetStepValue did not return the expected value.")
    End Sub

End Class
