'The following code was generated by Microsoft Visual Studio 2005.
'The test owner should check each test for validity.
Imports Microsoft.VisualStudio.TestTools.UnitTesting
Imports System
Imports System.Text
Imports System.Collections.Generic
Imports AVPLib





'''<summary>
'''This is a test class for AVPLib.AVPControlJob and is intended
'''to contain all AVPLib.AVPControlJob Unit Tests
'''</summary>
<TestClass()> _
Public Class AVPControlJobTest


    Private testContextInstance As TestContext

    '''<summary>
    '''Gets or sets the test context which provides
    '''information about and functionality for the current test run.
    '''</summary>
    Public Property TestContext() As TestContext
        Get
            Return testContextInstance
        End Get
        Set(ByVal value As TestContext)
            testContextInstance = Value
        End Set
    End Property
#Region "Additional test attributes"
    '
    'You can use the following additional attributes as you write your tests:
    '
    'Use ClassInitialize to run code before running the first test in the class
    '
    '<ClassInitialize()>  _
    'Public Shared Sub MyClassInitialize(ByVal testContext As TestContext)
    'End Sub
    '
    'Use ClassCleanup to run code after all tests in a class have run
    '
    '<ClassCleanup()>  _
    'Public Shared Sub MyClassCleanup()
    'End Sub
    '
    'Use TestInitialize to run code before running each test
    '
    '<TestInitialize()>  _
    'Public Sub MyTestInitialize()
    'End Sub
    '
    'Use TestCleanup to run code after each test has run
    '
    '<TestCleanup()>  _
    'Public Sub MyTestCleanup()
    'End Sub
    '
#End Region

    '''<summary>
    ''' <name> Tran Ngoc Khiet </name>
    ''' <date> June 15 2009 </date>
    '''A test for GetProcessJobTest_NormalCase01()
    '' Test case IG status is not Closed
    '''</summary>
    '''<summary>
    '''A test for GetProcessJob(ByVal String)
    '''</summary>
    <TestMethod()> _
    Public Sub GetProcessJobTest_NormalCase01()
        Dim target As AVPControlJob = New AVPControlJob

        Dim waferID As String = "1" 'TODO: Initialize to an appropriate value

        Dim expectedID As String = "1"
        Dim expectedCurrentStationID As Integer = 1
        Dim expectedSlotID As Integer = 1
        Dim expectedWaferStatus As Integer = 1
        Dim actual As AVPProcessJob
        actual = target.GetProcessJob(waferID)

        Assert.AreEqual(expectedID, actual.WaferInfo.WaferID, "AVPLib.AVPControlJob.GetProcessJob did not return the expected value.")
        Assert.AreEqual(expectedCurrentStationID, actual.WaferInfo.CurrentStationID, "AVPLib.AVPControlJob.GetProcessJob did not return the expected value.")
        Assert.AreEqual(expectedCurrentStationID, actual.WaferInfo.SlotID, "AVPLib.AVPControlJob.GetProcessJob did not return the expected value.")
        Assert.AreEqual(expectedCurrentStationID, actual.WaferInfo.WaferStatus, "AVPLib.AVPControlJob.GetProcessJob did not return the expected value.")
    End Sub

End Class
