'The following code was generated by Microsoft Visual Studio 2005.
'The test owner should check each test for validity.
Imports Microsoft.VisualStudio.TestTools.UnitTesting
Imports System
Imports System.Text
Imports System.Collections.Generic
Imports AVPLib.DataManagerment
'''<summary>
Imports System.Collections

'''This is a test class for AVPLib.ContainerData and is intended
Imports System.Xml

'''to contain all AVPLib.ContainerData Unit Tests
'''</summary>
<TestClass()> _
Public Class ContainerDataTest
    Private testContextInstance As TestContext

    '''<summary>
    '''Gets or sets the test context which provides
    '''information about and functionality for the current test run.
    '''</summary>
    Public Property TestContext() As TestContext
        Get
            Return testContextInstance
        End Get
        Set(ByVal value As TestContext)
            testContextInstance = value
        End Set
    End Property
#Region "Additional test attributes"
    '
    'You can use the following additional attributes as you write your tests:
    '
    'Use ClassInitialize to run code before running the first test in the class
    '
    <ClassInitialize()> _
    Public Shared Sub MyClassInitialize(ByVal testContext As TestContext)
        AVPLib.Log.initialize()
        AVPLib.ContainerDAO.FPath_WaferFlow = "..\..\..\AVPLibTest\bin\TestData\ContainerDataTest\SystemWaferFlow.xml"
    End Sub
    '
    'Use ClassCleanup to run code after all tests in a class have run
    '
    '<ClassCleanup()>  _
    Public Shared Sub MyClassCleanup()
    End Sub
    '
    'Use TestInitialize to run code before running each test
    '
    <TestInitialize()> _
    Public Sub MyTestInitialize()
    End Sub
    '
    'Use TestCleanup to run code after each test has run
    '
    '<TestCleanup()>  _
    'Public Sub MyTestCleanup()
    'End Sub
    '
#End Region
    '''<summary>
    '''A test for SelectedWaferNodes(ByVal System.Xml.XmlDocument, ByVal String)
    '''</summary>
    <TestMethod()> _
    Public Sub SelectedWaferNodesTest_Case1() ''true case
        AVPLib.ContainerDAO.FPath_WaferFlow = "..\..\..\AVPLibTest\bin\TestData\ContainerDataTest\SystemWaferFlow.xml"
        AVPLib.ContainerDAO.WaferFlowDoc = Nothing
        AVPLib.ContainerDAO.LoadSystemWaferFlow()
        Dim xdoc As XmlDocument = AVPLib.ContainerDAO.WaferFlowDoc
        Dim nodename As String = "WFFlow3"
        Dim expected As String = "WFFlow3"
        Dim actual As XmlNode
        actual = AVPLibTest.AVPLib_ContainerDataAccessor.SelectedWaferNodes(xdoc, nodename)

        Assert.AreEqual(expected, actual.FirstChild.InnerText, "AVPLib.ContainerData.SelectedWaferNodes did not return the expected value.")
    End Sub
    <TestMethod()> _
   Public Sub SelectedWaferNodesTest_Case2() ''fail case
        AVPLib.ContainerDAO.FPath_WaferFlow = "..\..\..\AVPLibTest\bin\TestData\ContainerDataTest\SystemWaferFlow.xml"
        AVPLib.ContainerDAO.WaferFlowDoc = Nothing
        AVPLib.ContainerDAO.LoadSystemWaferFlow()
        Dim xdoc As XmlDocument = AVPLib.ContainerDAO.WaferFlowDoc
        Dim nodename As String = "WFFlow1"
        Dim expected As String = "WFFlow3"
        Dim actual As XmlNode
        actual = AVPLibTest.AVPLib_ContainerDataAccessor.SelectedWaferNodes(xdoc, nodename)

        Assert.AreEqual(expected, actual.FirstChild.InnerText, "AVPLib.ContainerData.SelectedWaferNodes did not return the expected value.")
    End Sub
    <TestMethod()> _
  Public Sub SelectedWaferNodesTest_Case3() ''true case with big node
        AVPLib.ContainerDAO.FPath_WaferFlow = "..\..\..\AVPLibTest\bin\TestData\ContainerDataTest\SystemWaferFlow.xml"
        AVPLib.ContainerDAO.WaferFlowDoc = Nothing
        AVPLib.ContainerDAO.LoadSystemWaferFlow()

        Dim xdoc As XmlDocument = AVPLib.ContainerDAO.WaferFlowDoc
        Dim nodename As String = "WFFlow"
        Dim expected As String = "WFFlow"
        Dim actual As XmlNode
        actual = AVPLibTest.AVPLib_ContainerDataAccessor.SelectedWaferNodes(xdoc, nodename)

        Assert.AreEqual(expected, actual.FirstChild.InnerText, "AVPLib.ContainerData.SelectedWaferNodes did not return the expected value.")
    End Sub

    '''<summary>
    '''A test for AddWaferFlow(ByVal AVPLib.DataManagerment.WaferFlow)
    '''</summary>
    <TestMethod()> _
    Public Sub AddWaferFlowTest_Case1() ''true case
        AVPLib.ContainerDAO.FPath_WaferFlow = "..\..\..\AVPLibTest\bin\TestData\ContainerDataTest\AddWafer_SystemWaferFlow.xml"
        AVPLib.ContainerDAO.WaferFlowDoc = Nothing
        AVPLib.ContainerDAO.LoadSystemWaferFlow()

        Dim WfFlow As New WaferFlow
        Dim arrStep As New ArrayList
        Dim stepitem As New WaferflowStep
        Dim arrStation As New ArrayList

        stepitem.Number = 1
        arrStation.Add("Chamber1")
        stepitem.StationList = arrStation
        stepitem.RecipeName = "ABC"
        arrStep.Add(stepitem)

        WfFlow.WaferFlowName = "Test1"
        WfFlow.StepList = arrStep
        WfFlow.Description = "This is a test case2"
        WfFlow.LoopList = Nothing

        Dim expected As Boolean = True
        Dim actual As Boolean

        'actual = AVPLib.ContainerData.AddWaferFlow(WfFlow)

        Assert.AreEqual(expected, actual, "AVPLib.ContainerData.AddWaferFlow did not return the expected value.")
    End Sub
    <TestMethod()> _
       Public Sub AddWaferFlowTest_Case2() ''fail case with no station
        AVPLib.ContainerDAO.FPath_WaferFlow = "..\..\..\AVPLibTest\bin\TestData\ContainerDataTest\AddWafer_SystemWaferFlow.xml"
        AVPLib.ContainerDAO.WaferFlowDoc = Nothing
        AVPLib.ContainerDAO.LoadSystemWaferFlow()

        Dim WfFlow As New WaferFlow
        Dim arrStep As New ArrayList
        Dim stepitem As New WaferflowStep

        stepitem.Number = 1
        stepitem.StationList = Nothing
        stepitem.RecipeName = "ABC"
        arrStep.Add(stepitem)

        WfFlow.WaferFlowName = "Test2"
        WfFlow.StepList = arrStep
        WfFlow.Description = "This is a test case2"
        WfFlow.LoopList = Nothing

        Dim expected As Boolean = False
        Dim actual As Boolean

        'actual = AVPLib.ContainerData.AddWaferFlow(WfFlow)

        Assert.AreEqual(expected, actual, "AVPLib.ContainerData.AddWaferFlow did not return the expected value.")
    End Sub

    '''<summary>
    '''A test for DeleteLoopNode(ByVal String, ByVal String)
    '''</summary>
    <TestMethod()> _
    Public Sub DeleteLoopNodeTest_Case1() ''success case
        AVPLib.ContainerDAO.FPath_WaferFlow = "..\..\..\AVPLibTest\bin\TestData\ContainerDataTest\DeleteLoopNode_SystemWaferFlow.xml"
        AVPLib.ContainerDAO.WaferFlowDoc = Nothing
        AVPLib.ContainerDAO.LoadSystemWaferFlow()

        Dim LoopNo As String = "0" 'TODO: Initialize to an appropriate value

        Dim wfFlowName As String = "WFFlow" 'TODO: Initialize to an appropriate value

        Dim expected As Boolean = True
        Dim actual As Boolean

        actual = AVPLib.ContainerData.DeleteLoopNode(LoopNo, wfFlowName)

        Assert.AreEqual(expected, actual, "AVPLib.ContainerData.DeleteLoopNode did not return the expected value.")
    End Sub

    <TestMethod()> _
    Public Sub DeleteStepNodeTest_Case2() ''fail case
        AVPLib.ContainerDAO.FPath_WaferFlow = "..\..\..\AVPLibTest\bin\TestData\ContainerDataTest\DeleteLoopNode_SystemWaferFlow.xml"
        AVPLib.ContainerDAO.WaferFlowDoc = Nothing
        AVPLib.ContainerDAO.LoadSystemWaferFlow()

        Dim stepNo As String = "0" 'TODO: Initialize to an appropriate value

        Dim wfFlowName As String = "Test1" 'TODO: Initialize to an appropriate value

        Dim expected As Boolean = True
        Dim actual As Boolean = False

        actual = AVPLib.ContainerData.DeleteStepNode(stepNo, wfFlowName)

        Assert.AreEqual(expected, actual, "AVPLib.ContainerData.DeleteStepNode did not return the expected value.")
        'Assert.Inconclusive("Verify the correctness of this test method.")
    End Sub

    '''<summary>
    '''A test for DeleteWaferFlow(ByVal String)
    '''</summary>
    <TestMethod()> _
    Public Sub DeleteWaferFlowTest_Case1() ''success case
        AVPLib.ContainerDAO.FPath_WaferFlow = "..\..\..\AVPLibTest\bin\TestData\ContainerDataTest\DeleteWaferFlow_SystemWaferFlow.xml"
        AVPLib.ContainerDAO.WaferFlowDoc = Nothing
        AVPLib.ContainerDAO.LoadSystemWaferFlow()

        Dim WaferName As String = "WFFlow3" 'reset waferflow if run test second time

        Dim expected As Boolean = True
        Dim actual As Boolean

        actual = AVPLib.ContainerData.DeleteWaferFlow(WaferName)

        Assert.AreEqual(expected, actual, "AVPLib.ContainerData.DeleteWaferFlow did not return the expected value.")
    End Sub
    <TestMethod()> _
        Public Sub DeleteWaferFlowTest_Case2() ''fail case
        AVPLib.ContainerDAO.FPath_WaferFlow = "..\..\..\AVPLibTest\bin\TestData\ContainerDataTest\DeleteWaferFlow_SystemWaferFlow.xml"
        AVPLib.ContainerDAO.WaferFlowDoc = Nothing
        AVPLib.ContainerDAO.LoadSystemWaferFlow()

        Dim WaferName As String = "WFFlow4" ''

        Dim expected As Boolean = False
        Dim actual As Boolean

        actual = AVPLib.ContainerData.DeleteWaferFlow(WaferName)

        Assert.AreEqual(expected, actual, "AVPLib.ContainerData.DeleteWaferFlow did not return the expected value.")
    End Sub
    '''<summary>
    '''A test for GetAllWaferFlowName()
    '''</summary>
    <TestMethod()> _
    Public Sub GetAllWaferFlowNameTest_Case1() ''fail case
        AVPLib.ContainerDAO.FPath_WaferFlow = "..\..\..\AVPLibTest\bin\TestData\ContainerDataTest\SystemWaferFlow.xml"
        AVPLib.ContainerDAO.WaferFlowDoc = Nothing
        AVPLib.ContainerDAO.LoadSystemWaferFlow()

        Dim expected As New ArrayList
        expected.Add("WFFlow")
        expected.Add("WFFlow1") ''in actual list WFFLow2
        expected.Add("WFFlow2") ''in actual list WFFLow1
        expected.Add("WFFlow3")

        Dim actual As ArrayList

        actual = AVPLib.ContainerData.GetAllWaferFlowName
        ''actual get the same item of expected but the order of items is different
        '---->it is fail case
        CollectionAssert.AreEqual(expected, actual, "AVPLib.ContainerData.GetAllWaferFlowName did not return the expected value.")
        'Assert.Inconclusive("Verify the correctness of this test method.")
    End Sub
    <TestMethod()> _
        Public Sub GetAllWaferFlowNameTest_Case2() ''fail case
        AVPLib.ContainerDAO.FPath_WaferFlow = "..\..\..\AVPLibTest\bin\TestData\ContainerDataTest\SystemWaferFlow.xml"
        AVPLib.ContainerDAO.WaferFlowDoc = Nothing
        AVPLib.ContainerDAO.LoadSystemWaferFlow()

        Dim expected As New ArrayList
        expected.Add("WFFlow")
        expected.Add("WFFlow1")
        expected.Add("WFFlow2")

        Dim actual As ArrayList

        actual = AVPLib.ContainerData.GetAllWaferFlowName

        CollectionAssert.AreEqual(expected, actual, "AVPLib.ContainerData.GetAllWaferFlowName did not return the expected value.")
        'Assert.Inconclusive("Verify the correctness of this test method.")
    End Sub


    '''<summary>
    '''A test for GetLoopList(ByVal System.Xml.XmlNode)
    '''</summary>
    <TestMethod()> _
    Public Sub GetLoopListTest_Case1()
        AVPLib.ContainerDAO.FPath_WaferFlow = "..\..\..\AVPLibTest\bin\TestData\ContainerDataTest\SystemWaferFlow.xml"
        AVPLib.ContainerDAO.WaferFlowDoc = Nothing
        AVPLib.ContainerDAO.LoadSystemWaferFlow()

        Dim LoopListNode As XmlNode = AVPLib.ContainerData.SelectedWaferNodes(AVPLib.ContainerDAO.WaferFlowDoc, "WFFlow1").ChildNodes.Item(3)

        Dim expected As New ArrayList
        Dim loopitem As New AVPLib.DataManagerment.WaferflowLoop
        loopitem.LoopNo = 0
        loopitem.LoopStart = 1
        loopitem.LoopEnd = 2
        loopitem.LoopCount = 4

        expected.Add(loopitem)
        Dim actual As ArrayList

        actual = AVPLib.ContainerData.GetLoopList(LoopListNode)

        Assert.AreEqual(CType(expected.Item(0), WaferflowLoop).LoopNo, CType(actual.Item(0), WaferflowLoop).LoopNo, "AVPLib.ContainerData.GetLoopList did not return the expected value.")
        Assert.AreEqual(CType(expected.Item(0), WaferflowLoop).LoopStart, CType(actual.Item(0), WaferflowLoop).LoopStart, "AVPLib.ContainerData.GetLoopList did not return the expected value.")
        Assert.AreEqual(CType(expected.Item(0), WaferflowLoop).LoopEnd, CType(actual.Item(0), WaferflowLoop).LoopEnd, "AVPLib.ContainerData.GetLoopList did not return the expected value.")

    End Sub
    <TestMethod()> _
    Public Sub GetLoopListTest_Case2()
        AVPLib.ContainerDAO.FPath_WaferFlow = "..\..\..\AVPLibTest\bin\TestData\ContainerDataTest\SystemWaferFlow.xml"
        AVPLib.ContainerDAO.WaferFlowDoc = Nothing
        AVPLib.ContainerDAO.LoadSystemWaferFlow()

        Dim LoopListNode As XmlNode = AVPLib.ContainerData.SelectedWaferNodes(AVPLib.ContainerDAO.WaferFlowDoc, "WFFlow1").ChildNodes.Item(3)

        Dim expected As New ArrayList
        Dim loopitem As New AVPLib.DataManagerment.WaferflowLoop
        loopitem.LoopNo = 0
        loopitem.LoopStart = 2
        loopitem.LoopEnd = 3
        loopitem.LoopCount = 4

        expected.Add(loopitem)
        Dim actual As ArrayList

        actual = AVPLib.ContainerData.GetLoopList(LoopListNode)

        Assert.AreEqual(CType(expected.Item(0), WaferflowLoop).LoopNo, CType(actual.Item(0), WaferflowLoop).LoopNo, "AVPLib.ContainerData.GetLoopList did not return the expected value.")
        Assert.AreEqual(CType(expected.Item(0), WaferflowLoop).LoopStart, CType(actual.Item(0), WaferflowLoop).LoopStart, "AVPLib.ContainerData.GetLoopList did not return the expected value.")
        Assert.AreEqual(CType(expected.Item(0), WaferflowLoop).LoopEnd, CType(actual.Item(0), WaferflowLoop).LoopEnd, "AVPLib.ContainerData.GetLoopList did not return the expected value.")
    End Sub

    '''<summary>
    '''A test for GetStepList(ByVal System.Xml.XmlNode)
    '''</summary>
    <TestMethod()> _
    Public Sub GetStepListTest_Case1() ''success case
        AVPLib.ContainerDAO.FPath_WaferFlow = "..\..\..\AVPLibTest\bin\TestData\ContainerDataTest\SystemWaferFlow.xml"
        AVPLib.ContainerDAO.WaferFlowDoc = Nothing
        AVPLib.ContainerDAO.LoadSystemWaferFlow()

        Dim StepListNode As XmlNode = AVPLib.ContainerData.SelectedWaferNodes(AVPLib.ContainerDAO.WaferFlowDoc, "WFFlow1").ChildNodes.Item(2)

        Dim expected As New ArrayList
        Dim stepitem As New AVPLib.DataManagerment.WaferflowStep
        stepitem.Number = 1
        stepitem.RecipeName = "G1"
        Dim arrstation As New ArrayList
        arrstation.Add("Chamber1")
        stepitem.StationList = arrstation
        expected.Add(stepitem)

        Dim actual As ArrayList

        actual = AVPLib.ContainerData.GetStepList(StepListNode)

        Assert.AreEqual(CType(expected.Item(0), WaferflowStep).Number, CType(actual.Item(0), WaferflowStep).Number, "AVPLib.ContainerData.GetLoopList did not return the expected value.")
        Assert.AreEqual(CType(expected.Item(0), WaferflowStep).RecipeName, CType(actual.Item(0), WaferflowStep).RecipeName, "AVPLib.ContainerData.GetLoopList did not return the expected value.")
        CollectionAssert.AreEqual(CType(expected.Item(0), WaferflowStep).StationList, CType(actual.Item(0), WaferflowStep).StationList, "AVPLib.ContainerData.GetLoopList did not return the expected value.")

    End Sub
    <TestMethod()> _
       Public Sub GetStepListTest_Case2() 'fail case
        AVPLib.ContainerDAO.FPath_WaferFlow = "..\..\..\AVPLibTest\bin\TestData\ContainerDataTest\SystemWaferFlow.xml"
        AVPLib.ContainerDAO.WaferFlowDoc = Nothing
        AVPLib.ContainerDAO.LoadSystemWaferFlow()

        Dim StepListNode As XmlNode = AVPLib.ContainerData.SelectedWaferNodes(AVPLib.ContainerDAO.WaferFlowDoc, "WFFlow1").ChildNodes.Item(2)

        Dim expected As New ArrayList
        Dim stepitem As New AVPLib.DataManagerment.WaferflowStep
        stepitem.Number = 2
        stepitem.RecipeName = "G1"
        Dim arrstation As New ArrayList
        arrstation.Add("Chamber2")
        stepitem.StationList = arrstation
        expected.Add(stepitem)

        Dim actual As ArrayList

        actual = AVPLib.ContainerData.GetStepList(StepListNode)

        Assert.AreEqual(CType(expected.Item(0), WaferflowStep).Number, CType(actual.Item(0), WaferflowStep).Number, "AVPLib.ContainerData.GetLoopList did not return the expected value.")
        Assert.AreEqual(CType(expected.Item(0), WaferflowStep).RecipeName, CType(actual.Item(0), WaferflowStep).RecipeName, "AVPLib.ContainerData.GetLoopList did not return the expected value.")
        CollectionAssert.AreEqual(CType(expected.Item(0), WaferflowStep).StationList, CType(actual.Item(0), WaferflowStep).StationList, "AVPLib.ContainerData.GetLoopList did not return the expected value.")

    End Sub

    '''<summary>
    '''A test for GetWaferFlowbyName(ByVal String)
    '''</summary>
    <TestMethod()> _
    Public Sub GetWaferFlowbyNameTest_Case1() ''success case
        AVPLib.ContainerDAO.FPath_WaferFlow = "..\..\..\AVPLibTest\bin\TestData\ContainerDataTest\SystemWaferFlow.xml"
        AVPLib.ContainerDAO.WaferFlowDoc = Nothing
        AVPLib.ContainerDAO.LoadSystemWaferFlow()

        Dim FlowName As String = Nothing 'TODO: Initialize to an appropriate value

        Dim expected As New WaferFlow
        expected.WaferFlowName = "WFFlow3"

        Dim actual As WaferFlow

        actual = AVPLib.ContainerData.GetWaferFlowbyName(FlowName)

        Assert.AreEqual(expected.WaferFlowName, actual.WaferFlowName, "AVPLib.ContainerData.GetWaferFlowbyName did not return the expected value.")
    End Sub

    Public Sub GetWaferFlowbyNameTest_Case2() 'fail case
        AVPLib.ContainerDAO.FPath_WaferFlow = "..\..\..\AVPLibTest\bin\TestData\ContainerDataTest\SystemWaferFlow.xml"
        AVPLib.ContainerDAO.WaferFlowDoc = Nothing
        AVPLib.ContainerDAO.LoadSystemWaferFlow()

        Dim FlowName As String = Nothing 'TODO: Initialize to an appropriate value

        Dim expected As New WaferFlow
        expected.WaferFlowName = "WFFlow5"

        Dim actual As WaferFlow

        actual = AVPLib.ContainerData.GetWaferFlowbyName(FlowName)

        Assert.AreEqual(expected.WaferFlowName, actual.WaferFlowName, "AVPLib.ContainerData.GetWaferFlowbyName did not return the expected value.")
    End Sub

    '''<summary>
    '''A test for UpdateStep(ByVal AVPLib.DataManagerment.WaferflowStep, ByVal AVPLib.DataManagerment.WaferFlow)
    '''</summary>
    <DeploymentItem("AVPLib.dll"), _
     TestMethod()> _
    Public Sub UpdateStepTest_Case1()
        AVPLib.ContainerDAO.FPath_WaferFlow = "..\..\..\AVPLibTest\bin\TestData\ContainerDataTest\UpdateStep_SystemWaferFlow.xml"
        AVPLib.ContainerDAO.WaferFlowDoc = Nothing
        AVPLib.ContainerDAO.LoadSystemWaferFlow()

        Dim stepitem As New WaferflowStep ' = Nothing 'TODO: Initialize to an appropriate value
        stepitem.Number = 0
        stepitem.RecipeName = "20L50"
        Dim arrStation As New ArrayList
        arrStation.Add("Chamber3")
        stepitem.StationList = arrStation

        Dim expected As Boolean = True
        Dim actual As Boolean

        actual = AVPLibTest.AVPLib_ContainerDataAccessor.UpdateStep(stepitem, "WFFlow2")

        Assert.AreEqual(expected, actual, "AVPLib.ContainerData.UpdateStep did not return the expected value.")
        'Assert.Inconclusive("Verify the correctness of this test method.")
    End Sub
    <DeploymentItem("AVPLib.dll"), _
        TestMethod()> _
       Public Sub UpdateStepTest_Case2() ''fail case
        AVPLib.ContainerDAO.FPath_WaferFlow = "..\..\..\AVPLibTest\bin\TestData\ContainerDataTest\UpdateStep_SystemWaferFlow.xml"
        AVPLib.ContainerDAO.WaferFlowDoc = Nothing
        AVPLib.ContainerDAO.LoadSystemWaferFlow()

        Dim stepitem As New WaferflowStep ' = Nothing 'TODO: Initialize to an appropriate value
        stepitem.Number = 1
        stepitem.RecipeName = "20L50"
        Dim arrStation As New ArrayList
        arrStation.Add("Chamber3")
        stepitem.StationList = arrStation

        Dim expected As Boolean = True
        Dim actual As Boolean

        actual = AVPLibTest.AVPLib_ContainerDataAccessor.UpdateStep(stepitem, "WFFlow2")

        Assert.AreEqual(expected, actual, "AVPLib.ContainerData.UpdateStep did not return the expected value.")
        'Assert.Inconclusive("Verify the correctness of this test method.")
    End Sub
    '''<summary>
    '''A test for UpdateWaferFlow(ByVal AVPLib.DataManagerment.WaferFlow)
    '''</summary>
    <TestMethod()> _
    Public Sub UpdateWaferFlowTest_Case1()
        AVPLib.ContainerDAO.FPath_WaferFlow = "..\..\..\AVPLibTest\bin\TestData\ContainerDataTest\UpdateWaferFlow_SystemWaferFlow.xml"
        AVPLib.ContainerDAO.WaferFlowDoc = Nothing
        AVPLib.ContainerDAO.LoadSystemWaferFlow()

        Dim WfFlow As New WaferFlow
        WfFlow.WaferFlowName = "WFFlow2"
        WfFlow.Description = ""
        ''''''''''''''''''''
        Dim stepitem As New WaferflowStep ' = Nothing 'TODO: Initialize to an appropriate value
        stepitem.Number = 0
        stepitem.RecipeName = "20L50"
        Dim arrStation As New ArrayList
        arrStation.Add("Chamber3")
        stepitem.StationList = arrStation

        Dim arrstep As New ArrayList
        arrstep.Add(stepitem)
        WfFlow.StepList = arrstep
        WfFlow.LoopList = Nothing

        Dim expected As Boolean = True
        Dim actual As Boolean

        '        actual = AVPLib.ContainerData.UpdateWaferFlow(WfFlow)

        Assert.AreEqual(expected, actual, "AVPLib.ContainerData.UpdateWaferFlow did not return the expected value.")
    End Sub
    Public Sub UpdateWaferFlowTest_Case2() ''fail b/c we don't have Step Number 3
        AVPLib.ContainerDAO.FPath_WaferFlow = "..\..\..\AVPLibTest\bin\TestData\ContainerDataTest\UpdateWaferFlow_SystemWaferFlow.xml"
        AVPLib.ContainerDAO.WaferFlowDoc = Nothing
        AVPLib.ContainerDAO.LoadSystemWaferFlow()

        Dim WfFlow As New WaferFlow
        WfFlow.WaferFlowName = "WFFlow2"
        WfFlow.Description = ""
        ''''''''''''''''''''
        Dim stepitem As New WaferflowStep ' = Nothing 'TODO: Initialize to an appropriate value
        stepitem.Number = 3
        stepitem.RecipeName = "20L50"
        Dim arrStation As New ArrayList
        arrStation.Add("Chamber3")
        stepitem.StationList = arrStation

        Dim arrstep As New ArrayList
        arrstep.Add(stepitem)
        WfFlow.StepList = arrstep
        WfFlow.LoopList = Nothing

        Dim expected As Boolean = True
        Dim actual As Boolean

        '        actual = AVPLib.ContainerData.UpdateWaferFlow(WfFlow)

        Assert.AreEqual(expected, actual, "AVPLib.ContainerData.UpdateWaferFlow did not return the expected value.")
    End Sub
    '''<summary>
    '''A test for AddLoop(ByVal Integer, ByVal AVPLib.DataManagerment.WaferflowLoop, ByVal String)
    '''</summary>
    <DeploymentItem("AVPLib.dll"), _
     TestMethod()> _
    Public Sub AddLoopTest_Case1()
        AVPLib.ContainerDAO.FPath_WaferFlow = "..\..\..\AVPLibTest\bin\TestData\ContainerDataTest\AddLoop_SystemWaferFlow.xml"
        AVPLib.ContainerDAO.WaferFlowDoc = Nothing
        AVPLib.ContainerDAO.LoadSystemWaferFlow()

        Dim i As Integer = 1

        Dim loopitem As New WaferflowLoop
        loopitem.LoopNo = i
        loopitem.LoopStart = 0
        loopitem.LoopEnd = 3
        loopitem.LoopCount = 4

        Dim wfFlowName As String = "WFFlow"

        Dim expected As Boolean = True
        Dim actual As Boolean

        actual = AVPLibTest.AVPLib_ContainerDataAccessor.AddLoop(i, loopitem, wfFlowName)

        Assert.AreEqual(expected, actual, "AVPLib.ContainerData.AddLoop did not return the expected value.")
    End Sub
    <DeploymentItem("AVPLib.dll"), _
         TestMethod()> _
        Public Sub AddLoopTest_Case2() 'fail b/c we don't have WaferFlow WFFlow5
        AVPLib.ContainerDAO.FPath_WaferFlow = "..\..\..\AVPLibTest\bin\TestData\ContainerDataTest\AddLoop_SystemWaferFlow.xml"
        AVPLib.ContainerDAO.WaferFlowDoc = Nothing
        AVPLib.ContainerDAO.LoadSystemWaferFlow()

        Dim i As Integer = 1

        Dim loopitem As New WaferflowLoop
        loopitem.LoopNo = i
        loopitem.LoopStart = 0
        loopitem.LoopEnd = 3
        loopitem.LoopCount = 4

        Dim wfFlowName As String = "WFFlow5"

        Dim expected As Boolean = True
        Dim actual As Boolean

        actual = AVPLibTest.AVPLib_ContainerDataAccessor.AddLoop(i, loopitem, wfFlowName)

        Assert.AreEqual(expected, actual, "AVPLib.ContainerData.AddLoop did not return the expected value.")
    End Sub
    '''<summary>
    '''A test for AddStep(ByVal Integer, ByVal AVPLib.DataManagerment.WaferflowStep, ByVal String)
    '''</summary>
    <DeploymentItem("AVPLib.dll"), _
     TestMethod()> _
    Public Sub AddStepTest_Case1()
        AVPLib.ContainerDAO.FPath_WaferFlow = "..\..\..\AVPLibTest\bin\TestData\ContainerDataTest\AddStep_SystemWaferFlow.xml"
        AVPLib.ContainerDAO.WaferFlowDoc = Nothing
        AVPLib.ContainerDAO.LoadSystemWaferFlow()

        Dim i As Integer 'TODO: Initialize to an appropriate value

        Dim stepitem As New WaferflowStep
        stepitem.Number = 4
        stepitem.RecipeName = "G1"
        Dim arrstation As New ArrayList
        arrstation.Add("Chamber1")
        stepitem.StationList = arrstation

        Dim wfFlowName As String = "WFFlow"

        Dim expected As Boolean = True
        Dim actual As Boolean

        actual = AVPLibTest.AVPLib_ContainerDataAccessor.AddStep(i, stepitem, wfFlowName)

        Assert.AreEqual(expected, actual, "AVPLib.ContainerData.AddStep did not return the expected value.")

    End Sub
    <DeploymentItem("AVPLib.dll"), _
    TestMethod()> _
   Public Sub AddStepTest_Case2()
        AVPLib.ContainerDAO.FPath_WaferFlow = "..\..\..\AVPLibTest\bin\TestData\ContainerDataTest\AddStep_SystemWaferFlow.xml"
        AVPLib.ContainerDAO.WaferFlowDoc = Nothing
        AVPLib.ContainerDAO.LoadSystemWaferFlow()

        Dim i As Integer 'TODO: Initialize to an appropriate value

        Dim stepitem As New WaferflowStep
        stepitem.Number = 2
        stepitem.RecipeName = "G1"
        Dim arrstation As New ArrayList
        arrstation.Add("Chamber1")
        stepitem.StationList = arrstation

        Dim wfFlowName As String = "WFFlow"

        Dim expected As Boolean = True
        Dim actual As Boolean

        actual = AVPLibTest.AVPLib_ContainerDataAccessor.AddStep(i, stepitem, wfFlowName)

        Assert.AreEqual(expected, actual, "AVPLib.ContainerData.AddStep did not return the expected value.")

    End Sub
End Class
