'The following code was generated by Microsoft Visual Studio 2005.
'The test owner should check each test for validity.
Imports Microsoft.VisualStudio.TestTools.UnitTesting
Imports System
Imports System.Text
Imports System.Collections.Generic




'''<summary>
'''This is a test class for AVPLib.Business.ControllerManager and is intended
'''to contain all AVPLib.Business.ControllerManager Unit Tests
'''</summary>
<TestClass()> _
Public Class ControllerManagerTest


    Private testContextInstance As TestContext

    '''<summary>
    '''Gets or sets the test context which provides
    '''information about and functionality for the current test run.
    '''</summary>
    Public Property TestContext() As TestContext
        Get
            Return testContextInstance
        End Get
        Set(ByVal value As TestContext)
            testContextInstance = Value
        End Set
    End Property
#Region "Additional test attributes"
    '
    'You can use the following additional attributes as you write your tests:
    '
    'Use ClassInitialize to run code before running the first test in the class
    '
    <ClassInitialize()> _
    Public Shared Sub MyClassInitialize(ByVal testContext As TestContext)
        AVPLib.Log.initialize()
        AVPLib.DataManagerment.EquipmentManager.Initialize()
        AVPLib.Business.ControllerManager.Initialize()

    End Sub
    '
    'Use ClassCleanup to run code after all tests in a class have run
    '
    '<ClassCleanup()>  _
    'Public Shared Sub MyClassCleanup()
    'End Sub
    '
    'Use TestInitialize to run code before running each test
    '
    '<TestInitialize()>  _
    'Public Sub MyTestInitialize()
    'End Sub
    '
    'Use TestCleanup to run code after each test has run
    '
    '<TestCleanup()>  _
    'Public Sub MyTestCleanup()
    'End Sub
    '
#End Region


    '''<summary>
    '''A test for SetWaferInsideStation(ByVal String, ByVal String)
    '''</summary>
    <TestMethod()> _
    Public Sub SetWaferInsideStationTest()
        Dim strStationName1 As String = "Aligner" 'TODO: Initialize to an appropriate value
        Dim strStationName2 As String = "LoadLockB,Slot6" 'TODO: Initialize to an appropriate value
        Dim strStationName3 As String = "Chamber3" 'TODO: Initialize to an appropriate value
        Dim strStationName4 As String = "Robot" 'TODO: Initialize to an appropriate value
        Dim strStationName5 As String = "LoadLockA,Slot5" 'TODO: Initialize to an appropriate value

        '   Dim strOnOff As String = "Off" 'TODO: Initialize to an appropriate value

        AVPLib.Business.ControllerManager.SetWaferInsideStation(strStationName1, "Off")
        AVPLib.Business.ControllerManager.SetWaferInsideStation(strStationName2, "On")
        AVPLib.Business.ControllerManager.SetWaferInsideStation(strStationName3, "On")
        AVPLib.Business.ControllerManager.SetWaferInsideStation(strStationName4, "Off")
        AVPLib.Business.ControllerManager.SetWaferInsideStation(strStationName5, "On")


    End Sub

End Class
