'The following code was generated by Microsoft Visual Studio 2005.
'The test owner should check each test for validity.
Imports Microsoft.VisualStudio.TestTools.UnitTesting
Imports System
Imports System.Text
Imports System.Collections.Generic
'''<summary>
'''This is a test class for AVPLib.ContainerData and is intended
'''to contain all AVPLib.ContainerData Unit Tests
'''</summary>
<TestClass()> _
Public Class ContainerDataTest


    Private testContextInstance As TestContext

    '''<summary>
    '''Gets or sets the test context which provides
    '''information about and functionality for the current test run.
    '''</summary>
    Public Property TestContext() As TestContext
        Get
            Return testContextInstance
        End Get
        Set(ByVal value As TestContext)
            testContextInstance = Value
        End Set
    End Property
#Region "Additional test attributes"
    '
    'You can use the following additional attributes as you write your tests:
    '
    'Use ClassInitialize to run code before running the first test in the class
    '
    <ClassInitialize()> _
    Public Shared Sub MyClassInitialize(ByVal testContext As TestContext)
       
        AppDomain.CurrentDomain.SetData("APPBASE", "..\..\..\AVPLibTest\bin\TestData\GetAlignerStationLocationTest_TestNormalCase_001\")
        AVPLib.Log.initialize()
        AVPLib.ContainerData.RobotConfigStart()
        AVPLib.ContainerData.LoadConfigurationData()
    End Sub
    '
    'Use ClassCleanup to run code after all tests in a class have run
    '
    '<ClassCleanup()>  _
    'Public Shared Sub MyClassCleanup()
    'End Sub
    '
    'Use TestInitialize to run code before running each test
    '
    '<TestInitialize()> _
    'Public Sub MyTestInitialize()
    '    AppDomain.CurrentDomain.SetData("APPBASE", "..\..\..\AVPLibTest\bin\TestData\GetAlignerStationLocationTest_TestNormalCase_001\")
    '    AVPLib.Log.initialize()
    '    AVPLib.ContainerData.RobotConfigStart()
    '    AVPLib.ContainerData.LoadConfigurationData()
    'End Sub
    '
    'Use TestCleanup to run code after each test has run
    '
    '<TestCleanup()> _
    'Public Sub MyTestCleanup()
    '    AppDomain.CurrentDomain.SetData("APPBASE", "..\..\..\AVPLibTest\bin\TestData\GetAlignerStationLocationTest_TestNormalCase_001\")
    'End Sub
    '
#End Region


    '''<summary>
    '''A test for GetAlignerStationLocation(ByRef Integer, ByRef Integer)
    ''' Test case DeltaPickNeeded = False and DeltaPickStation = 9 
    '''</summary>
    <TestMethod()> _
    Public Sub GetAlignerStationLocationTest_TestNormalCase_001()

        Dim iplaceStation As Integer = 8 'TODO: Initialize to an appropriate value
        Dim iplaceStation_expected As Integer = 8 'TODO: Initialize to an appropriate value

        Dim ipickStation As Integer = 8 'TODO: Initialize to an appropriate value
        Dim ipickStation_expected As Integer = 8 'TODO: Initialize to an appropriate value

        Dim expected As Boolean = True
        Dim actual As Boolean

        actual = AVPLib.ContainerData.GetAlignerStationLocation(iplaceStation, ipickStation)

        Assert.AreEqual(iplaceStation_expected, iplaceStation, "iplaceStation_GetAlignerStationLocation_expected was not set correctly.")
        Assert.AreEqual(ipickStation_expected, ipickStation, "ipickStation_GetAlignerStationLocation_expected was not set correctly.")
        Assert.AreEqual(expected, actual, "AVPLib.ContainerData.GetAlignerStationLocation did not return the expected value." & _
                "")
    End Sub

    '''<summary>
    '''A test for GetAlignerStationLocation(ByRef Integer, ByRef Integer)
    ''' Test case DeltaPickNeeded = True and DeltaPickStation = 9 
    '''</summary>
    <TestMethod()> _
    Public Sub GetAlignerStationLocationTest_TestNormalCase_002()
        Dim iplaceStation As Integer = 8 'TODO: Initialize to an appropriate value
        Dim iplaceStation_expected As Integer = 8 'TODO: Initialize to an appropriate value

        Dim ipickStation As Integer = 9 'TODO: Initialize to an appropriate value
        Dim ipickStation_expected As Integer = 8 'TODO: Initialize to an appropriate value

        Dim expected As Boolean = True
        Dim actual As Boolean

        actual = AVPLib.ContainerData.GetAlignerStationLocation(iplaceStation, ipickStation)

        Assert.AreEqual(iplaceStation_expected, iplaceStation, "iplaceStation_GetAlignerStationLocation_expected was not set correctly.")
        Assert.AreEqual(ipickStation_expected, ipickStation, "ipickStation_GetAlignerStationLocation_expected was not set correctly.")
        Assert.AreEqual(expected, actual, "AVPLib.ContainerData.GetAlignerStationLocation did not return the expected value." & _
                "")
    End Sub


End Class
