'The following code was generated by Microsoft Visual Studio 2005.
'The test owner should check each test for validity.
Imports Microsoft.VisualStudio.TestTools.UnitTesting
Imports System
Imports System.Text
Imports System.Collections.Generic
Imports System.Collections


'''<summary>
'''This is a test class for AVPLib.DataManagerment.EquipmentManager and is intended
'''to contain all AVPLib.DataManagerment.EquipmentManager Unit Tests
'''</summary>
<TestClass()> _
Public Class EquipmentManagerTest


    Private testContextInstance As TestContext

    '''<summary>
    '''Gets or sets the test context which provides
    '''information about and functionality for the current test run.
    '''</summary>
    Public Property TestContext() As TestContext
        Get
            Return testContextInstance
        End Get
        Set(ByVal value As TestContext)
            testContextInstance = value
        End Set
    End Property
#Region "Additional test attributes"
    '
    'You can use the following additional attributes as you write your tests:
    '
    'Use ClassInitialize to run code before running the first test in the class
    '
    '<ClassInitialize()>  _
    'Public Shared Sub MyClassInitialize(ByVal testContext As TestContext)
    'End Sub
    '
    'Use ClassCleanup to run code after all tests in a class have run
    '
    '<ClassCleanup()>  _
    'Public Shared Sub MyClassCleanup()
    'End Sub
    '
    'Use TestInitialize to run code before running each test
    '
    <TestInitialize()> _
    Public Sub MyTestInitialize()
        AVPLib.Log.init()

    End Sub
    '
    'Use TestCleanup to run code after each test has run
    '
    '<TestCleanup()>  _
    'Public Sub MyTestCleanup()
    'End Sub
    '
#End Region

    '''<summary>
    '''A test for CheckEquipmentsOnline(ByVal String(), ByRef System.Collections.Generic.List(Of String))
    ''' Test case all chamber online
    '''</summary>
    <TestMethod()> _
    Public Sub CheckEquipmentsOnlineTest_NormalCase001()
        AVPLib.DataManagerment.EquipmentManager.Initialize()
        Dim EquipmentNames() As String = {"LoadLockB", "Chamber5"}  'TODO: Initialize to an appropriate value
        Dim lstStrNotOnlineEquipments As System.Collections.Generic.List(Of String) = New List(Of String) 'TODO: Initialize to an appropriate value
        lstStrNotOnlineEquipments.Add("Chamber5")
        Dim actual As Boolean
        actual = CheckEquipmentsOnline(EquipmentNames, lstStrNotOnlineEquipments)
        Assert.AreEqual(True, actual, "AVPLib.DataManagerment.EquipmentManager.CheckEquipmentsOnline did not return the " & _
                "expected value.")
    End Sub
    Public Function CheckEquipmentsOnline(ByVal EquipmentNames As String(), ByRef lstStrNotOnlineEquipments As List(Of String)) As Boolean
        AVPLib.Log.coreLogger.Info("Enter CheckEquipmentsOnline")
        Try
            'SyncLock (m_objLock)
            'lstStrNotOnlineEquipments = New List(Of String)
            Dim eqmEquiment As AVPLib.DataManagerment.Equipment = Nothing
            ' all equipment is online as default
            Dim isOnline As Boolean = True
            ' for each equipment in the equipment list
            For Each strName As String In EquipmentNames
                eqmEquiment = AVPLib.DataManagerment.EquipmentManager.GetEquipment(strName)
                Dim enmEqquipmentControlStatus As AVPLib.DataManagerment.Equipment.ControlStatuses = AVPLib.DataManagerment.Equipment.ControlStatuses.OFFLINE

                'this is a not good design, should not use CType
                If (eqmEquiment.Name.IndexOf(AVPLib.ConstEnum.LoadLock) >= 0) Then
                    Dim ll As AVPLib.DataManagerment.LoadLock = CType(eqmEquiment, AVPLib.DataManagerment.LoadLock)
                    enmEqquipmentControlStatus = AVPLib.DataManagerment.Equipment.ControlStatuses.ONLINE
                ElseIf (eqmEquiment.Name.IndexOf(AVPLib.ConstEnum.Chamber) >= 0) Then
                    Dim cb As AVPLib.DataManagerment.Chamber = CType(eqmEquiment, AVPLib.DataManagerment.Chamber)
                    enmEqquipmentControlStatus = AVPLib.DataManagerment.Equipment.ControlStatuses.ONLINE
                Else
                    ' just ignore this case
                    AVPLib.Log.coreLogger.Warn(String.Format("Unknown equipment {0} found", eqmEquiment.Name))
                End If

                If (enmEqquipmentControlStatus <> AVPLib.DataManagerment.Equipment.ControlStatuses.ONLINE) Then
                    isOnline = False
                    ' add to the list of offline equipments
                    lstStrNotOnlineEquipments.Add(strName)
                End If
            Next
            Return isOnline
            'End SyncLock
        Catch ex As Exception
            AVPLib.Log.avpLogger.Error(ex.ToString())
        End Try
        AVPLib.Log.coreLogger.Info("Leave CheckEquipmentsOnline")
    End Function

    '''<summary>
    '''A test for CheckEquipmentsOnline(ByVal String(), ByRef System.Collections.Generic.List(Of String))
    '' Test case for have Chamber not online
    '''</summary>
    <TestMethod()> _
    Public Sub CheckEquipmentsOnlineTest_NormalCase002()
        AVPLib.DataManagerment.EquipmentManager.Initialize()
        Dim EquipmentNames() As String = {"LoadLockA", "Chamber2"} 'TODO: Initialize to an appropriate value
        Dim lstStrNotOnlineEquipments As System.Collections.Generic.List(Of String) = New List(Of String) 'TODO: Initialize to an appropriate value
        lstStrNotOnlineEquipments.Add("Chamber2")
        Dim actual As Boolean
        actual = CheckEquipmentsOnline1(EquipmentNames, lstStrNotOnlineEquipments)
        Assert.AreEqual(True, actual, "AVPLib.DataManagerment.EquipmentManager.CheckEquipmentsOnline did not return the " & _
                "expected value.")
    End Sub
    Public Function CheckEquipmentsOnline1(ByVal EquipmentNames As String(), ByRef lstStrNotOnlineEquipments As List(Of String)) As Boolean
        AVPLib.Log.coreLogger.Info("Enter CheckEquipmentsOnline")
        Try
            'SyncLock (m_objLock)
            'lstStrNotOnlineEquipments = New List(Of String)
            Dim eqmEquiment As AVPLib.DataManagerment.Equipment = Nothing
            ' all equipment is online as default
            Dim isOnline As Boolean = True
            ' for each equipment in the equipment list
            For Each strName As String In EquipmentNames
                eqmEquiment = AVPLib.DataManagerment.EquipmentManager.GetEquipment(strName)
                Dim enmEqquipmentControlStatus As AVPLib.DataManagerment.Equipment.ControlStatuses = AVPLib.DataManagerment.Equipment.ControlStatuses.OFFLINE

                'this is a not good design, should not use CType
                If (eqmEquiment.Name.IndexOf(AVPLib.ConstEnum.LoadLock) >= 0) Then
                    Dim ll As AVPLib.DataManagerment.LoadLock = CType(eqmEquiment, AVPLib.DataManagerment.LoadLock)
                    enmEqquipmentControlStatus = AVPLib.DataManagerment.Equipment.ControlStatuses.OFFLINE
                ElseIf (eqmEquiment.Name.IndexOf(AVPLib.ConstEnum.Chamber) >= 0) Then
                    Dim cb As AVPLib.DataManagerment.Chamber = CType(eqmEquiment, AVPLib.DataManagerment.Chamber)
                    enmEqquipmentControlStatus = AVPLib.DataManagerment.Equipment.ControlStatuses.OFFLINE
                Else
                    ' just ignore this case
                    AVPLib.Log.coreLogger.Warn(String.Format("Unknown equipment {0} found", eqmEquiment.Name))
                End If

                If (enmEqquipmentControlStatus <> AVPLib.DataManagerment.Equipment.ControlStatuses.ONLINE) Then
                    isOnline = False
                    ' add to the list of offline equipments
                    lstStrNotOnlineEquipments.Add(strName)
                End If
            Next
            Return isOnline
            'End SyncLock
        Catch ex As Exception
            AVPLib.Log.avpLogger.Error(ex.ToString())
        End Try
        AVPLib.Log.coreLogger.Info("Leave CheckEquipmentsOnline")
    End Function
End Class
