'The following code was generated by Microsoft Visual Studio 2005.
'The test owner should check each test for validity.
Imports Microsoft.VisualStudio.TestTools.UnitTesting
Imports System
Imports System.Text
Imports System.Collections.Generic
Imports AVPLib.DataManagerment
Imports AVPLib




'''<summary>
'''This is a test class for AVPLib.DataManagerment.LoadLock and is intended
'''to contain all AVPLib.DataManagerment.LoadLock Unit Tests
'''</summary>
<TestClass()> _
Public Class LoadLockTest


    Private testContextInstance As TestContext

    '''<summary>
    '''Gets or sets the test context which provides
    '''information about and functionality for the current test run.
    '''</summary>
    Public Property TestContext() As TestContext
        Get
            Return testContextInstance
        End Get
        Set(ByVal value As TestContext)
            testContextInstance = value
        End Set
    End Property
#Region "Additional test attributes"
    '
    'You can use the following additional attributes as you write your tests:
    '
    'Use ClassInitialize to run code before running the first test in the class
    '
    <ClassInitialize()> _
    Public Shared Sub MyClassInitialize(ByVal testContext As TestContext)
        AppDomain.CurrentDomain.SetData("APPBASE", "..\..\..\AVPLibTest\bin\TestData\LoadLockTest\")
        AVPLib.Log.initialize()
        AVPLib.ContainerData.InitConfigStart()
        AVPLib.ContainerData.LoadConfigurationData()

    End Sub
    '
    'Use ClassCleanup to run code after all tests in a class have run
    '
    '<ClassCleanup()>  _
    'Public Shared Sub MyClassCleanup()
    'End Sub
    '
    'Use TestInitialize to run code before running each test
    '
    <TestInitialize()> _
    Public Sub MyTestInitialize()
       
    End Sub
    '
    'Use TestCleanup to run code after each test has run
    '
    '<TestCleanup()>  _
    'Public Sub MyTestCleanup()
    'End Sub
    '
#End Region

    '''<summary>
    '''A test for checkCondition2OpenLLRough()
    '''</summary>
    <TestMethod()> _
    Public Sub CheckCondition2OpenLLRoughTest_Case_1()
        Dim target As LoadLock = New LoadLock
        Dim expected As String = Nothing
        Dim actual As String
        target.HiVacValveStatus = Equipment.WorkingStatuses.On
        actual = target.checkCondition2OpenLLRough
        Assert.AreEqual(expected, actual, "AVPLib.DataManagerment.LoadLock.checkCondition2OpenLLRough did not return the exp" & _
                "ected value.")

    End Sub
    <TestMethod()> _
     Public Sub CheckCondition2OpenLLRoughTest_Case_2()
        Dim target As LoadLock = New LoadLock

        Dim expected As String = Nothing
        Dim actual As String
        target.HiVacValveStatus = Equipment.WorkingStatuses.Off
        target.IGStatus = Equipment.WorkingStatuses.On
        actual = target.checkCondition2OpenLLRough
        Assert.AreEqual(expected, actual, "AVPLib.DataManagerment.LoadLock.checkCondition2OpenLLRough did not return the exp" & _
                "ected value.")
    End Sub
    <TestMethod()> _
        Public Sub CheckCondition2OpenLLRoughTest_Case_3()
        Dim target As LoadLock = New LoadLock

        Dim expected As String = Nothing
        Dim actual As String
        target.HiVacValveStatus = Equipment.WorkingStatuses.Off
        target.IGStatus = Equipment.WorkingStatuses.Off
        target.SlitValveStatus = Equipment.WorkingStatuses.On
        actual = target.checkCondition2OpenLLRough
        Assert.AreEqual(expected, actual, "AVPLib.DataManagerment.LoadLock.checkCondition2OpenLLRough did not return the exp" & _
                "ected value.")
    End Sub
    <TestMethod()> _
           Public Sub CheckCondition2OpenLLRoughTest_Case_4()
        Dim target As LoadLock = New LoadLock

        Dim expected As String = Nothing
        Dim actual As String
        target.HiVacValveStatus = Equipment.WorkingStatuses.Off
        target.IGStatus = Equipment.WorkingStatuses.Off
        target.SlitValveStatus = Equipment.WorkingStatuses.Off
        target.SlowVentValveStatus = Equipment.WorkingStatuses.On
        target.FastVentValveStatus = Equipment.WorkingStatuses.Off
        actual = target.checkCondition2OpenLLRough
        Assert.AreEqual(expected, actual, "AVPLib.DataManagerment.LoadLock.checkCondition2OpenLLRough did not return the exp" & _
                "ected value.")
    End Sub
    '''<summary>
    '''A test for checkCondition2OpenLLHiVac()
    '''</summary>
    <System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", MessageId:="Member")> <TestMethod()> _
    Public Sub CheckCondition2OpenLLHiVacTest_Case1()
        Dim target As LoadLock = New LoadLock

        Dim expected As String = Nothing
        Dim actual As String

        target.VacSwitchStatus = Equipment.WorkingStatuses.On
        actual = target.checkCondition2OpenLLHiVac

        Assert.AreEqual(expected, actual, "AVPLib.DataManagerment.LoadLock.checkCondition2OpenLLHiVac did not return the exp" & _
                "ected value.")

    End Sub
    <System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", MessageId:="Member")> <TestMethod()> _
    Public Sub CheckCondition2OpenLLHiVacTest_Case2()
        Dim target As LoadLock = New LoadLock

        Dim expected As String = Nothing
        Dim actual As String

        target.VacSwitchStatus = Equipment.WorkingStatuses.Off
        target.IG = 0.1 ''>0.02
        actual = target.checkCondition2OpenLLHiVac

        Assert.AreEqual(expected, actual, "AVPLib.DataManagerment.LoadLock.checkCondition2OpenLLHiVac did not return the exp" & _
                "ected value.")

    End Sub

    '''<summary>
    ''' <name> Tran Ngoc Khiet </name>
    ''' <date> June 15 2009 </date>
    '''A test for checkCondition2OpenLLIGTest()
    '' Test case with T2 of LLA < 20K
    '''</summary>
    <TestMethod()> _
    Public Sub checkCondition2OpenLLIGTest_TestNormalCase_001()
        Dim target As LoadLock = New LoadLock
        Dim LLACryo As DataManagerment.LLCryo = CType(DataManagerment.EquipmentManager.GetEquipment(ConstEnum.Equipments.LLACryo.ToString()), AVPLib.DataManagerment.LLCryo)
        Dim expected As String = String.Empty
        Dim actual As String
        target.HiVacValveStatus = Equipment.WorkingStatuses.On
        target.Name = "LoadLockA"
        'LLACryo.T2 < VentPumdownLib.TMLLCommand.LLCryoT2 = 20K
        LLACryo.T2 = 10
        actual = target.checkCondition2OpenLLIG

        Assert.AreEqual(expected, actual, "AVPLib.DataManagerment.LoadLock.checkCondition2OpenLLIG did not return the expect" & _
                "ed value.")
    End Sub
    '''<summary>
    ''' <name> Tran Ngoc Khiet </name>
    ''' <date> June 15 2009 </date>
    '''A test for checkCondition2OpenLLIGTest()
    '' Test case with T2 of LLA = 20K
    '''</summary>
    <TestMethod()> _
    Public Sub checkCondition2OpenLLIGTest_TestNormalCase_002()
        Dim target As LoadLock = New LoadLock
        Dim LLACryo As DataManagerment.LLCryo = CType(DataManagerment.EquipmentManager.GetEquipment(ConstEnum.Equipments.LLACryo.ToString()), AVPLib.DataManagerment.LLCryo)
        Dim expected As String = "T2 of LoadLockA Cryo > 20K"
        Dim actual As String
        target.HiVacValveStatus = Equipment.WorkingStatuses.On
        target.Name = "LoadLockA"
        'LLACryo.T2 < VentPumdownLib.TMLLCommand.LLCryoT2 = 20K
        LLACryo.T2 = 20
        actual = target.checkCondition2OpenLLIG

        Assert.AreEqual(expected, actual, "AVPLib.DataManagerment.LoadLock.checkCondition2OpenLLIG did not return the expect" & _
                "ed value.")
    End Sub
    '''<summary>
    ''' <name> Tran Ngoc Khiet </name>
    ''' <date> June 15 2009 </date>
    '''A test for checkCondition2OpenLLIGTest()
    '' Test case with T2 of LLA > 20K
    '''</summary>
    <TestMethod()> _
    Public Sub checkCondition2OpenLLIGTest_TestNormalCase_003()
        Dim target As LoadLock = New LoadLock
        Dim LLACryo As DataManagerment.LLCryo = CType(DataManagerment.EquipmentManager.GetEquipment(ConstEnum.Equipments.LLACryo.ToString()), AVPLib.DataManagerment.LLCryo)
        Dim expected As String = "T2 of LoadLockA Cryo > 20K"
        Dim actual As String
        target.HiVacValveStatus = Equipment.WorkingStatuses.On
        target.Name = "LoadLockA"
        'LLACryo.T2 < VentPumdownLib.TMLLCommand.LLCryoT2 > 20K
        LLACryo.T2 = 21
        actual = target.checkCondition2OpenLLIG

        Assert.AreEqual(expected, actual, "AVPLib.DataManagerment.LoadLock.checkCondition2OpenLLIG did not return the expect" & _
                "ed value.")
    End Sub
    '''<summary>
    ''' <name> Tran Ngoc Khiet </name>
    ''' <date> June 15 2009 </date>
    '''A test for checkCondition2OpenLLIGTest()
    '' Test case with TM hivac not Opened
    '''</summary>
    <TestMethod()> _
    Public Sub checkCondition2OpenLLIGTest_TestNormalCase_004()
        Dim target As LoadLock = New LoadLock
        Dim LLACryo As DataManagerment.LLCryo = CType(DataManagerment.EquipmentManager.GetEquipment(ConstEnum.Equipments.LLACryo.ToString()), AVPLib.DataManagerment.LLCryo)
        Dim expected As String = "Hivac valve of LoadLockA is not Open"
        Dim actual As String
        target.HiVacValveStatus = Equipment.WorkingStatuses.Off  'TM Hivac not Opened
        target.Name = "LoadLockA"
        LLACryo.T2 = 15
        actual = target.checkCondition2OpenLLIG
        Assert.AreEqual(expected, actual, "AVPLib.DataManagerment.LoadLock.checkCondition2OpenLLIG did not return the expect" & _
                "ed value.")
    End Sub

    '''<summary>
    ''' <name> Tran Ngoc Khiet </name>
    ''' <date> June 15 2009 </date>
    '''A test for checkCondition2OpenLLIGTest()
    '' Test case with T2 of LLB < 20K
    '''</summary>
    <TestMethod()> _
    Public Sub checkCondition2OpenLLIGTest_TestNormalCase_005()
        Dim target As LoadLock = New LoadLock
        Dim LLBCryo As DataManagerment.LLCryo = CType(DataManagerment.EquipmentManager.GetEquipment(ConstEnum.Equipments.LLBCryo.ToString()), AVPLib.DataManagerment.LLCryo)
        Dim expected As String = String.Empty
        Dim actual As String
        target.HiVacValveStatus = Equipment.WorkingStatuses.On
        target.Name = "LoadLockB"
        'LLBCryo.T2 < VentPumdownLib.TMLLCommand.LLCryoT2 = 20K
        LLBCryo.T2 = 10
        actual = target.checkCondition2OpenLLIG
        Assert.AreEqual(expected, actual, "AVPLib.DataManagerment.LoadLock.checkCondition2OpenLLIG did not return the expect" & _
                "ed value.")
    End Sub
    '''<summary>
    ''' <name> Tran Ngoc Khiet </name>
    ''' <date> June 15 2009 </date>
    '''A test for checkCondition2OpenLLIGTest()
    '' Test case with T2 of LLB = 20K
    '''</summary>
    <TestMethod()> _
    Public Sub checkCondition2OpenLLIGTest_TestNormalCase_006()
        Dim target As LoadLock = New LoadLock
        Dim LLBCryo As DataManagerment.LLCryo = CType(DataManagerment.EquipmentManager.GetEquipment(ConstEnum.Equipments.LLBCryo.ToString()), AVPLib.DataManagerment.LLCryo)
        Dim expected As String = "T2 of LoadLockB Cryo > 20K"
        Dim actual As String
        target.HiVacValveStatus = Equipment.WorkingStatuses.On
        target.Name = "LoadLockB"
        'LLBCryo.T2 < VentPumdownLib.TMLLCommand.LLCryoT2 = 20K
        LLBCryo.T2 = 20
        actual = target.checkCondition2OpenLLIG
        Assert.AreEqual(expected, actual, "AVPLib.DataManagerment.LoadLock.checkCondition2OpenLLIG did not return the expect" & _
                "ed value.")
    End Sub
    '''<summary>
    ''' <name> Tran Ngoc Khiet </name>
    ''' <date> June 15 2009 </date>
    '''A test for checkCondition2OpenLLIGTest()
    '' Test case with T2 of LLA > 20K
    '''</summary>
    <TestMethod()> _
    Public Sub checkCondition2OpenLLIGTest_TestNormalCase_007()
        Dim target As LoadLock = New LoadLock
        Dim LLBCryo As DataManagerment.LLCryo = CType(DataManagerment.EquipmentManager.GetEquipment(ConstEnum.Equipments.LLBCryo.ToString()), AVPLib.DataManagerment.LLCryo)
        Dim expected As String = "T2 of LoadLockB Cryo > 20K"
        Dim actual As String
        target.HiVacValveStatus = Equipment.WorkingStatuses.On
        target.Name = "LoadLockB"
        'LLBCryo.T2 < VentPumdownLib.TMLLCommand.LLCryoT2 > 20K
        LLBCryo.T2 = 21
        actual = target.checkCondition2OpenLLIG
        Assert.AreEqual(expected, actual, "AVPLib.DataManagerment.LoadLock.checkCondition2OpenLLIG did not return the expect" & _
                "ed value.")
    End Sub
    '''<summary>
    ''' <name> Tran Ngoc Khiet </name>
    ''' <date> June 15 2009 </date>
    '''A test for checkCondition2OpenLLIGTest()
    '' Test case with TM hivac not Opened
    '''</summary>
    <TestMethod()> _
    Public Sub checkCondition2OpenLLIGTest_TestNormalCase_008()
        Dim target As LoadLock = New LoadLock
        Dim LLBCryo As DataManagerment.LLCryo = CType(DataManagerment.EquipmentManager.GetEquipment(ConstEnum.Equipments.LLBCryo.ToString()), AVPLib.DataManagerment.LLCryo)
        Dim expected As String = "Hivac valve of LoadLockB is not Open"
        Dim actual As String
        target.HiVacValveStatus = Equipment.WorkingStatuses.Off  'TM Hivac not Opened
        target.Name = "LoadLockB"
        LLBCryo.T2 = 15
        actual = target.checkCondition2OpenLLIG
        Assert.AreEqual(expected, actual, "AVPLib.DataManagerment.LoadLock.checkCondition2OpenLLIG did not return the expect" & _
                "ed value.")
    End Sub

    '''<summary>
    ''' <name> Tran Ngoc Khiet </name>
    ''' <date> June 15 2009 </date>
    '''A test for checkCondition2OpenLLVentTest()
    '' Test case normal for LoadLockA
    '''</summary>
    <TestMethod()> _
    Public Sub checkCondition2OpenLLVentTest_TestNormalCase_001()
        Dim target As LoadLock = New LoadLock

        Dim expected As String = String.Empty
        Dim actual As String
        target.HiVacValveStatus = Equipment.WorkingStatuses.Off
        target.IGStatus = Equipment.WorkingStatuses.Off
        target.SlitValveStatus = Equipment.WorkingStatuses.Off
        target.SlowRoughValveStatus = Equipment.WorkingStatuses.Off
        target.FastRoughValveStatus = Equipment.WorkingStatuses.Off

        actual = target.checkCondition2OpenLLVent

        Assert.AreEqual(expected, actual, "AVPLib.DataManagerment.LoadLock.checkCondition2OpenLLVent did not return the expe" & _
                "cted value.")
    End Sub
    '''<summary>
    ''' <name> Tran Ngoc Khiet </name>
    ''' <date> June 15 2009 </date>
    '''A test for checkCondition2OpenLLVentTest()
    '' Test case HIvac valve is not Closed
    '''</summary>
    <TestMethod()> _
    Public Sub checkCondition2OpenLLVentTest_TestNormalCase_002()
        Dim target As LoadLock = New LoadLock

        Dim expected As String = "Hivac valve LoadLockA was not closed"
        Dim actual As String
        target.HiVacValveStatus = Equipment.WorkingStatuses.On ' Hivac valve is not Closed
        target.IGStatus = Equipment.WorkingStatuses.Off
        target.SlitValveStatus = Equipment.WorkingStatuses.Off
        target.SlowRoughValveStatus = Equipment.WorkingStatuses.Off
        target.FastRoughValveStatus = Equipment.WorkingStatuses.Off
        target.Name = "LoadLockA"
        actual = target.checkCondition2OpenLLVent

        Assert.AreEqual(expected, actual, "AVPLib.DataManagerment.LoadLock.checkCondition2OpenLLVent did not return the expe" & _
                "cted value.")
    End Sub
    '''<summary>
    ''' <name> Tran Ngoc Khiet </name>
    ''' <date> June 15 2009 </date>
    '''A test for checkCondition2OpenLLVentTest()
    '' Test case IG status is not Closed
    '''</summary>
    <TestMethod()> _
    Public Sub checkCondition2OpenLLVentTest_TestNormalCase_003()
        Dim target As LoadLock = New LoadLock

        Dim expected As String = "IG of LoadLockA was not closed"
        Dim actual As String
        target.HiVacValveStatus = Equipment.WorkingStatuses.Off
        target.IGStatus = Equipment.WorkingStatuses.Unknown 'Or target.IGStatus = Equipment.WorkingStatuses.On  ''IG status is not Closed
        target.SlitValveStatus = Equipment.WorkingStatuses.Off
        target.SlowRoughValveStatus = Equipment.WorkingStatuses.Off
        target.FastRoughValveStatus = Equipment.WorkingStatuses.Off
        target.Name = "LoadLockA"
        actual = target.checkCondition2OpenLLVent
        Assert.AreEqual(expected, actual, "AVPLib.DataManagerment.LoadLock.checkCondition2OpenLLVent did not return the expe" & _
                "cted value.")
    End Sub
    '''<summary>
    ''' <name> Tran Ngoc Khiet </name>
    ''' <date> June 15 2009 </date>
    '''A test for checkCondition2OpenLLVentTest()
    '' Test case SlitValveStatus is not Closed
    '''</summary>
    <TestMethod()> _
    Public Sub checkCondition2OpenLLVentTest_TestNormalCase_004()
        Dim target As LoadLock = New LoadLock

        Dim expected As String = "Mesa Valve of LoadLockA was not closed"
        Dim actual As String
        target.HiVacValveStatus = Equipment.WorkingStatuses.Off
        target.IGStatus = Equipment.WorkingStatuses.Off
        target.SlitValveStatus = Equipment.WorkingStatuses.On  'Or target.SlitValveStatus = Equipment.WorkingStatuses.RedUnknown  => SlitValveStatus is not Closed
        target.SlowRoughValveStatus = Equipment.WorkingStatuses.Off
        target.FastRoughValveStatus = Equipment.WorkingStatuses.Off
        target.Name = "LoadLockA"
        actual = target.checkCondition2OpenLLVent
        Assert.AreEqual(expected, actual, "AVPLib.DataManagerment.LoadLock.checkCondition2OpenLLVent did not return the expe" & _
                "cted value.")
    End Sub
    '''<summary>
    ''' <name> Tran Ngoc Khiet </name>
    ''' <date> June 15 2009 </date>
    '''A test for checkCondition2OpenLLVentTest()
    '' Test case SlowRoughValveStatus is not Closed
    '''</summary>
    <TestMethod()> _
    Public Sub checkCondition2OpenLLVentTest_TestNormalCase_005()
        Dim target As LoadLock = New LoadLock

        Dim expected As String = "Slow Rough Valve of LoadLockA was not closed"
        Dim actual As String
        target.HiVacValveStatus = Equipment.WorkingStatuses.Off
        target.IGStatus = Equipment.WorkingStatuses.Off
        target.SlitValveStatus = Equipment.WorkingStatuses.Off
        target.SlowRoughValveStatus = Equipment.WorkingStatuses.Unknown 'Or target.SlowRoughValveStatus = Equipment.WorkingStatuses.On  => SlowRoughValveStatus is not Closed
        target.FastRoughValveStatus = Equipment.WorkingStatuses.Off
        target.Name = "LoadLockA"
        actual = target.checkCondition2OpenLLVent
        Assert.AreEqual(expected, actual, "AVPLib.DataManagerment.LoadLock.checkCondition2OpenLLVent did not return the expe" & _
                "cted value.")
    End Sub
    '''<summary>
    ''' <name> Tran Ngoc Khiet </name>
    ''' <date> June 15 2009 </date>
    '''A test for checkCondition2OpenLLVentTest()
    '' Test case FastRoughValveStatus is not Closed
    '''</summary>
    <TestMethod()> _
    Public Sub checkCondition2OpenLLVentTest_TestNormalCase_006()
        Dim target As LoadLock = New LoadLock

        Dim expected As String = "Fast Rough Valve of LoadLockA was not closed"
        Dim actual As String
        target.HiVacValveStatus = Equipment.WorkingStatuses.Off
        target.IGStatus = Equipment.WorkingStatuses.Off
        target.SlitValveStatus = Equipment.WorkingStatuses.Off
        target.SlowRoughValveStatus = Equipment.WorkingStatuses.Off
        target.FastRoughValveStatus = Equipment.WorkingStatuses.On 'Or target.FastRoughValveStatus = Equipment.WorkingStatuses.RedUnknown => FastRoughValveStatus is not Closed
        target.Name = "LoadLockA"
        actual = target.checkCondition2OpenLLVent
        Assert.AreEqual(expected, actual, "AVPLib.DataManagerment.LoadLock.checkCondition2OpenLLVent did not return the expe" & _
                "cted value.")
    End Sub
    
    '''<summary>
    ''' <name> Tran Ngoc Khiet </name>
    ''' <date> June 15 2009 </date>
    '''A test for checkCondition2OpenLLVentTest()
    '' Test case HIvac valve is not Closed
    '''</summary>
    <TestMethod()> _
    Public Sub checkCondition2OpenLLVentTest_TestNormalCase_007()
        Dim target As LoadLock = New LoadLock

        Dim expected As String = "Hivac valve LoadLockB was not closed"
        Dim actual As String
        target.HiVacValveStatus = Equipment.WorkingStatuses.On ' Hivac valve is not Closed
        target.IGStatus = Equipment.WorkingStatuses.Off
        target.SlitValveStatus = Equipment.WorkingStatuses.Off
        target.SlowRoughValveStatus = Equipment.WorkingStatuses.Off
        target.FastRoughValveStatus = Equipment.WorkingStatuses.Off
        target.Name = "LoadLockB"
        actual = target.checkCondition2OpenLLVent

        Assert.AreEqual(expected, actual, "AVPLib.DataManagerment.LoadLock.checkCondition2OpenLLVent did not return the expe" & _
                "cted value.")
    End Sub
    '''<summary>
    ''' <name> Tran Ngoc Khiet </name>
    ''' <date> June 15 2009 </date>
    '''A test for checkCondition2OpenLLVentTest()
    '' Test case IG status is not Closed
    '''</summary>
    <TestMethod()> _
    Public Sub checkCondition2OpenLLVentTest_TestNormalCase_008()
        Dim target As LoadLock = New LoadLock

        Dim expected As String = "IG of LoadLockB was not closed"
        Dim actual As String
        target.HiVacValveStatus = Equipment.WorkingStatuses.Off
        target.IGStatus = Equipment.WorkingStatuses.Unknown 'Or target.IGStatus = Equipment.WorkingStatuses.On  ''IG status is not Closed
        target.SlitValveStatus = Equipment.WorkingStatuses.Off
        target.SlowRoughValveStatus = Equipment.WorkingStatuses.Off
        target.FastRoughValveStatus = Equipment.WorkingStatuses.Off
        target.Name = "LoadLockB"
        actual = target.checkCondition2OpenLLVent
        Assert.AreEqual(expected, actual, "AVPLib.DataManagerment.LoadLock.checkCondition2OpenLLVent did not return the expe" & _
                "cted value.")
    End Sub
    '''<summary>
    ''' <name> Tran Ngoc Khiet </name>
    ''' <date> June 15 2009 </date>
    '''A test for checkCondition2OpenLLVentTest()
    '' Test case SlitValveStatus is not Closed
    '''</summary>
    <TestMethod()> _
    Public Sub checkCondition2OpenLLVentTest_TestNormalCase_009()
        Dim target As LoadLock = New LoadLock

        Dim expected As String = "Mesa Valve of LoadLockB was not closed"
        Dim actual As String
        target.HiVacValveStatus = Equipment.WorkingStatuses.Off
        target.IGStatus = Equipment.WorkingStatuses.Off
        target.SlitValveStatus = Equipment.WorkingStatuses.On  'Or target.SlitValveStatus = Equipment.WorkingStatuses.RedUnknown  => SlitValveStatus is not Closed
        target.SlowRoughValveStatus = Equipment.WorkingStatuses.Off
        target.FastRoughValveStatus = Equipment.WorkingStatuses.Off
        target.Name = "LoadLockB"
        actual = target.checkCondition2OpenLLVent
        Assert.AreEqual(expected, actual, "AVPLib.DataManagerment.LoadLock.checkCondition2OpenLLVent did not return the expe" & _
                "cted value.")
    End Sub
    '''<summary>
    ''' <name> Tran Ngoc Khiet </name>
    ''' <date> June 15 2009 </date>
    '''A test for checkCondition2OpenLLVentTest()
    '' Test case SlowRoughValveStatus is not Closed
    '''</summary>
    <TestMethod()> _
    Public Sub checkCondition2OpenLLVentTest_TestNormalCase_010()
        Dim target As LoadLock = New LoadLock

        Dim expected As String = "Slow Rough Valve of LoadLockB was not closed"
        Dim actual As String
        target.HiVacValveStatus = Equipment.WorkingStatuses.Off
        target.IGStatus = Equipment.WorkingStatuses.Off
        target.SlitValveStatus = Equipment.WorkingStatuses.Off
        target.SlowRoughValveStatus = Equipment.WorkingStatuses.Unknown 'Or target.SlowRoughValveStatus = Equipment.WorkingStatuses.On  => SlowRoughValveStatus is not Closed
        target.FastRoughValveStatus = Equipment.WorkingStatuses.Off
        target.Name = "LoadLockB"
        actual = target.checkCondition2OpenLLVent
        Assert.AreEqual(expected, actual, "AVPLib.DataManagerment.LoadLock.checkCondition2OpenLLVent did not return the expe" & _
                "cted value.")
    End Sub
    '''<summary>
    ''' <name> Tran Ngoc Khiet </name>
    ''' <date> June 15 2009 </date>
    '''A test for checkCondition2OpenLLVentTest()
    '' Test case FastRoughValveStatus is not Closed
    '''</summary>
    <TestMethod()> _
    Public Sub checkCondition2OpenLLVentTest_TestNormalCase_011()
        Dim target As LoadLock = New LoadLock

        Dim expected As String = "Fast Rough Valve of LoadLockB was not closed"
        Dim actual As String
        target.HiVacValveStatus = Equipment.WorkingStatuses.Off
        target.IGStatus = Equipment.WorkingStatuses.Off
        target.SlitValveStatus = Equipment.WorkingStatuses.Off
        target.SlowRoughValveStatus = Equipment.WorkingStatuses.Off
        target.FastRoughValveStatus = Equipment.WorkingStatuses.On 'Or target.FastRoughValveStatus = Equipment.WorkingStatuses.RedUnknown => FastRoughValveStatus is not Closed
        target.Name = "LoadLockB"
        actual = target.checkCondition2OpenLLVent
        Assert.AreEqual(expected, actual, "AVPLib.DataManagerment.LoadLock.checkCondition2OpenLLVent did not return the expe" & _
                "cted value.")
    End Sub
End Class
