'The following code was generated by Microsoft Visual Studio 2005.
'The test owner should check each test for validity.
Imports Microsoft.VisualStudio.TestTools.UnitTesting
Imports System
Imports System.Text
Imports System.Collections.Generic
Imports System.Xml
Imports System.Collections






'''<summary>
'''This is a test class for AVPLib.PollingLib and is intended
'''to contain all AVPLib.PollingLib Unit Tests
'''</summary>
<TestClass()> _
Public Class PollingLibTest

    Private Shared UserDoc As XmlDocument = Nothing 'TODO: Initialize to an appropriate value
    Private testContextInstance As TestContext

    '''<summary>
    '''Gets or sets the test context which provides
    '''information about and functionality for the current test run.
    '''</summary>
    Public Property TestContext() As TestContext
        Get
            Return testContextInstance
        End Get
        Set(ByVal value As TestContext)
            testContextInstance = Value
        End Set
    End Property
#Region "Additional test attributes"
    '
    'You can use the following additional attributes as you write your tests:
    '
    'Use ClassInitialize to run code before running the first test in the class
    '
    <ClassInitialize()> _
    Public Shared Sub MyClassInitialize(ByVal testContext As TestContext)
        AppDomain.CurrentDomain.SetData("APPBASE", "..\..\..\AVPLibTest\bin\TestData\UserSetupLibTest_GetUserFunction")
        AVPLib.Log.initialize()
        UserDoc = New XmlDocument()
        'UserDoc.Load(XmlFPath)

    End Sub
    '
    'Use ClassCleanup to run code after all tests in a class have run
    '
    '<ClassCleanup()>  _
    'Public Shared Sub MyClassCleanup()
    'End Sub
    '
    'Use TestInitialize to run code before running each test
    '
    '<TestInitialize()>  _
    'Public Sub MyTestInitialize()
    'End Sub
    '
    'Use TestCleanup to run code after each test has run
    '
    '<TestCleanup()>  _
    'Public Sub MyTestCleanup()
    'End Sub
    '
#End Region


    '''<summary>
    '''A test for GetConfig(ByVal System.Xml.XmlDocument)
    '''</summary>
    <TestMethod()> _
    Public Sub GetConfigTest()
        UserDoc.Load("..\..\..\AVPLibTest\bin\TestData\GetConfigTest_PollingInterval_NormalCase\PollingInterval.xml")
        Dim PollingDoc As XmlDocument = UserDoc 'TODO: Initialize to an appropriate value

        Dim expected1 As New AVPLib.Polling("LLBElevator", 200, True) 'real value is Timeout="d000" IsLog="True"-->error and use default value
        Dim expected2 As New AVPLib.Polling("Robot", 200, True) 'real value is Timeout="-200" IsLog="True"-->error and use default 200
        Dim expected3 As New AVPLib.Polling("Aligner", 1000, True) 'real value is IsLog=False ->not equal
        Dim actual As AVPLib.Polling
        Dim hstConfigValue As Hashtable = AVPLib.PollingLib.GetConfig(PollingDoc)

        actual = CType(hstConfigValue.Item("LLBElevator"), AVPLib.Polling)
        Assert.AreEqual(expected1.IsLog, actual.IsLog, "AVPLib.PollingLib.GetConfig did not return the expected value.")
        Assert.AreEqual(expected1.Interval, actual.Interval, "AVPLib.PollingLib.GetConfig did not return the expected value.")

        actual = CType(hstConfigValue.Item("Robot"), AVPLib.Polling)
        Assert.AreEqual(expected2.IsLog, actual.IsLog, "AVPLib.PollingLib.GetConfig did not return the expected value.")
        Assert.AreEqual(expected2.Interval, actual.Interval, "AVPLib.PollingLib.GetConfig did not return the expected value.")

        actual = CType(hstConfigValue.Item("Aligner"), AVPLib.Polling)
        Assert.AreEqual(expected3.IsLog, actual.IsLog, "AVPLib.PollingLib.GetConfig did not return the expected value.")
        Assert.AreEqual(expected3.Interval, actual.Interval, "AVPLib.PollingLib.GetConfig did not return the expected value.")
    End Sub

End Class
