'The following code was generated by Microsoft Visual Studio 2005.
'The test owner should check each test for validity.
Imports Microsoft.VisualStudio.TestTools.UnitTesting
Imports System
Imports System.Text
Imports System.Collections.Generic
Imports System.Xml
Imports System.Collections






'''<summary>
'''This is a test class for AVPLib.PressureConfigurationLib and is intended
'''to contain all AVPLib.PressureConfigurationLib Unit Tests
'''</summary>
<TestClass()> _
Public Class PressureConfigurationLibTest


    Private testContextInstance As TestContext
    Private Shared UserDoc As XmlDocument = Nothing 'TODO: Initialize to an appropriate value
    '''<summary>
    '''Gets or sets the test context which provides
    '''information about and functionality for the current test run.
    '''</summary>
    Public Property TestContext() As TestContext
        Get
            Return testContextInstance
        End Get
        Set(ByVal value As TestContext)
            testContextInstance = value
        End Set
    End Property
#Region "Additional test attributes"
    '
    'You can use the following additional attributes as you write your tests:
    '
    'Use ClassInitialize to run code before running the first test in the class
    '
    <ClassInitialize()> _
    Public Shared Sub MyClassInitialize(ByVal testContext As TestContext)
        AppDomain.CurrentDomain.SetData("APPBASE", "..\..\..\AVPLibTest\bin\TestData\UserSetupLibTest_GetUserFunction")
        AVPLib.Log.initialize()
        UserDoc = New XmlDocument()
    End Sub
    '
    'Use ClassCleanup to run code after all tests in a class have run
    '
    '<ClassCleanup()>  _
    'Public Shared Sub MyClassCleanup()
    'End Sub
    '
    'Use TestInitialize to run code before running each test
    '
    '<TestInitialize()>  _
    'Public Sub MyTestInitialize()
    'End Sub
    '
    'Use TestCleanup to run code after each test has run
    '
    '<TestCleanup()>  _
    'Public Sub MyTestCleanup()
    'End Sub
    '
#End Region


    '''<summary>
    '''A test for GetPressureConfig(ByVal System.Xml.XmlDocument)
    '' test normal case 
    '''</summary>
    <TestMethod()> _
      Public Sub GetPressureConfigTest_NormalCase_001()
        UserDoc.Load("..\..\..\AVPLibTest\bin\TestData\GetPressureConfigTest_NormalCase\PressureConfig.xml")
        Dim PressureDoc As XmlDocument = UserDoc 'TODO: Initialize to an appropriate value

        Dim expected1 As Integer = 2 'correct
        Dim expected2 As Integer = 0 '-->error number:ab-> and use default
        Dim expected3 As Integer = 0 '->error number:-2 and use default value
        Dim exMinItem0 As Double = 0.375 'correct
        Dim exMaxItem0 As Double = 2.842 'correct
        Dim exMinItem1 As Double = 2.842 'correct
        Dim exMaxItem1 As Double = 4.945 'correct
        Dim exMinItem2 As Double = 4.94 'correct
        Dim exMaxItem2 As Double = 5.659 'correct
        Dim exStringItem0 As String = "-0.02585 + (0.03767*{0}) + (0.04563*({0}^2)) + (0.1151*({0}^3)) + (-0.04158*({0}^4)) + (0.008737*({0}^5))"
        Dim exStringItem1 As String = "(0.1031 + (-0.02322*{0}) + (0.07229*({0}^2))) / (1 + (-0.3986*{0}) + 0.07438*({0}^2) + (-0.006866*({0}^3)))"
        Dim exStringItem2 As String = "(100.624 + (-20.5623*{0}))/(1 + (-0.37679*{0}) + 0.0348656*({0}^2))"
        Dim exIGFormula As String = "log10({0}) + 10"

        Dim actual As Hashtable

        actual = AVPLib.PressureConfigurationLib.GetPressureConfig(PressureDoc)

        Assert.AreEqual(Of Integer)(expected1, CInt(actual.Item("TransferModule")), "AVPLib.PressureConfigurationLib.GetPressureConfig did not return the expected val" & _
                "ue.")
        Assert.AreEqual(Of Integer)(expected2, CInt(actual.Item("LoadLockB")), "AVPLib.PressureConfigurationLib.GetPressureConfig did not return the expected val" & _
                       "ue.")
        Assert.AreEqual(Of Integer)(expected3, CInt(actual.Item("IBEMaintainance")), "AVPLib.PressureConfigurationLib.GetPressureConfig did not return the expected val" & _
                            "ue.")
        Assert.AreEqual(Of Double)(exMinItem0, CDbl(CType(actual.Item("CG_Formula"), System.Collections.Generic.List(Of AVPLib.CGFormula)).Item(0).Min), "AVPLib.PressureConfigurationLib.GetPressureConfig did not return the expected val" & _
                                   "ue.")
        Assert.AreEqual(Of Double)(exMaxItem0, CDbl(CType(actual.Item("CG_Formula"), System.Collections.Generic.List(Of AVPLib.CGFormula)).Item(0).Max), "AVPLib.PressureConfigurationLib.GetPressureConfig did not return the expected val" & _
                                   "ue.")
        Assert.AreEqual(Of Double)(exMinItem1, CDbl(CType(actual.Item("CG_Formula"), System.Collections.Generic.List(Of AVPLib.CGFormula)).Item(1).Min), "AVPLib.PressureConfigurationLib.GetPressureConfig did not return the expected val" & _
                                   "ue.")
        Assert.AreEqual(Of Double)(exMaxItem1, CDbl(CType(actual.Item("CG_Formula"), System.Collections.Generic.List(Of AVPLib.CGFormula)).Item(1).Max), "AVPLib.PressureConfigurationLib.GetPressureConfig did not return the expected val" & _
                                   "ue.")
        Assert.AreEqual(Of Double)(exMinItem2, CDbl(CType(actual.Item("CG_Formula"), System.Collections.Generic.List(Of AVPLib.CGFormula)).Item(2).Min), "AVPLib.PressureConfigurationLib.GetPressureConfig did not return the expected val" & _
                                          "ue.")
        Assert.AreEqual(Of Double)(exMaxItem2, CDbl(CType(actual.Item("CG_Formula"), System.Collections.Generic.List(Of AVPLib.CGFormula)).Item(2).Max), "AVPLib.PressureConfigurationLib.GetPressureConfig did not return the expected val" & _
                                   "ue.")
        Assert.AreEqual(Of String)(exStringItem0, (CType(actual.Item("CG_Formula"), System.Collections.Generic.List(Of AVPLib.CGFormula)).Item(0).Fomula).ToString(), "AVPLib.PressureConfigurationLib.GetPressureConfig did not return the expected val" & _
                                 "ue.")
        Assert.AreEqual(Of String)(exStringItem1, (CType(actual.Item("CG_Formula"), System.Collections.Generic.List(Of AVPLib.CGFormula)).Item(1).Fomula).ToString(), "AVPLib.PressureConfigurationLib.GetPressureConfig did not return the expected val" & _
                                "ue.")
        Assert.AreEqual(Of String)(exStringItem2, (CType(actual.Item("CG_Formula"), System.Collections.Generic.List(Of AVPLib.CGFormula)).Item(2).Fomula).ToString(), "AVPLib.PressureConfigurationLib.GetPressureConfig did not return the expected val" & _
                                "ue.")
        Assert.AreEqual(exIGFormula, actual.Item("IG_Formula"), "AVPLib.PressureConfigurationLib.GetPressureConfig did not return the expected val" & _
                               "ue.")
    End Sub

    '''<summary>
    '''A test for GetPressureConfig(ByVal System.Xml.XmlDocument)
    ''' test case for haven't MIN and MAX
    '''</summary>
    <TestMethod()> _
    Public Sub GetPressureConfigTest_NormalCase_002()
        UserDoc.Load("..\..\..\AVPLibTest\bin\TestData\GetPressureConfigTest_NormalCase_002\PressureConfig.xml")
        Dim PressureDoc As XmlDocument = UserDoc 'TODO: Initialize to an appropriate value

        Dim exMinItem0 As Double = 0.375 'incorrect
        Dim exMaxItem0 As Double = 2.842 'incorrect
        Dim exMinItem1 As Double = 2.842 'incorrect
        Dim exMaxItem1 As Double = 4.945 'incorrect
        Dim exMinItem2 As Double = 4.94 'incorrect
        Dim exMaxItem2 As Double = 5.659 'incorrect

        Dim actual As Hashtable
        actual = AVPLib.PressureConfigurationLib.GetPressureConfig(PressureDoc)

        Assert.AreEqual(Of Double)(exMinItem0, CDbl(CType(actual.Item("CG_Formula"), System.Collections.Generic.List(Of AVPLib.CGFormula)).Item(0).Min), "AVPLib.PressureConfigurationLib.GetPressureConfig did not return the expected val" & _
                                   "ue.")
        Assert.AreEqual(Of Double)(exMaxItem0, CDbl(CType(actual.Item("CG_Formula"), System.Collections.Generic.List(Of AVPLib.CGFormula)).Item(0).Max), "AVPLib.PressureConfigurationLib.GetPressureConfig did not return the expected val" & _
                                   "ue.")
        Assert.AreEqual(Of Double)(exMinItem1, CDbl(CType(actual.Item("CG_Formula"), System.Collections.Generic.List(Of AVPLib.CGFormula)).Item(1).Min), "AVPLib.PressureConfigurationLib.GetPressureConfig did not return the expected val" & _
                                   "ue.")
        Assert.AreEqual(Of Double)(exMaxItem1, CDbl(CType(actual.Item("CG_Formula"), System.Collections.Generic.List(Of AVPLib.CGFormula)).Item(1).Max), "AVPLib.PressureConfigurationLib.GetPressureConfig did not return the expected val" & _
                                   "ue.")
        Assert.AreEqual(Of Double)(exMinItem2, CDbl(CType(actual.Item("CG_Formula"), System.Collections.Generic.List(Of AVPLib.CGFormula)).Item(2).Min), "AVPLib.PressureConfigurationLib.GetPressureConfig did not return the expected val" & _
                                          "ue.")
        Assert.AreEqual(Of Double)(exMaxItem2, CDbl(CType(actual.Item("CG_Formula"), System.Collections.Generic.List(Of AVPLib.CGFormula)).Item(2).Max), "AVPLib.PressureConfigurationLib.GetPressureConfig did not return the expected val" & _
                                   "ue.")
    End Sub
End Class
