'The following code was generated by Microsoft Visual Studio 2005.
'The test owner should check each test for validity.
Imports Microsoft.VisualStudio.TestTools.UnitTesting
Imports System
Imports System.Text
Imports System.Collections.Generic
Imports System.Xml
Imports System.Collections






'''<summary>
'''This is a test class for AVPLib.TimeoutLib and is intended
'''to contain all AVPLib.TimeoutLib Unit Tests
'''</summary>
<TestClass()> _
Public Class TimeoutLibTest


    Private testContextInstance As TestContext
    Private Shared UserDoc As XmlDocument = Nothing 'TODO: Initialize to an appropriate value
    '''<summary>
    '''Gets or sets the test context which provides
    '''information about and functionality for the current test run.
    '''</summary>
    Public Property TestContext() As TestContext
        Get
            Return testContextInstance
        End Get
        Set(ByVal value As TestContext)
            testContextInstance = Value
        End Set
    End Property
#Region "Additional test attributes"
    '
    'You can use the following additional attributes as you write your tests:
    '
    'Use ClassInitialize to run code before running the first test in the class
    '
    <ClassInitialize()> _
    Public Shared Sub MyClassInitialize(ByVal testContext As TestContext)
        AppDomain.CurrentDomain.SetData("APPBASE", "..\..\..\AVPLibTest\bin\TestData\GetConfigTest_TimeoutInterval_NormalCase")
        AVPLib.Log.initialize()
        UserDoc = New XmlDocument()
    End Sub
    '
    'Use ClassCleanup to run code after all tests in a class have run
    '
    '<ClassCleanup()>  _
    'Public Shared Sub MyClassCleanup()
    'End Sub
    '
    'Use TestInitialize to run code before running each test
    '
    '<TestInitialize()>  _
    'Public Sub MyTestInitialize()
    'End Sub
    '
    'Use TestCleanup to run code after each test has run
    '
    '<TestCleanup()>  _
    'Public Sub MyTestCleanup()
    'End Sub
    '
#End Region


    '''<summary>
    '''A test for GetConfig(ByVal System.Xml.XmlDocument)
    '''</summary>
    <TestMethod()> _
    Public Sub GetConfigTest()
        UserDoc.Load("..\..\..\AVPLibTest\bin\TestData\GetConfigTest_TimeoutInterval_NormalCase\Timeout.xml")
        Dim PressureDoc As XmlDocument = UserDoc 'TODO: Initialize to an appropriate value

        Dim expected1 As Double = 2000 '-->error number:-200-> and use default:0
        Dim expected2 As Double = 2000 '-->error number:abc-> and use default:0
        Dim expected3 As Double = 2000 '->Correct number
        Dim actual As Hashtable

        actual = AVPLib.TimeoutLib.GetConfig(PressureDoc)

        Assert.AreEqual(expected1, CDbl(actual.Item("LLBCryo")), "AVPLib.TimeoutLib.GetConfig did not return the expected value.")
        Assert.AreEqual(expected2, CDbl(actual.Item("LLAElevator")), "AVPLib.TimeoutLib.GetConfig did not return the expected value.")
        Assert.AreEqual(expected3, CDbl(actual.Item("Aligner")), "AVPLib.TimeoutLib.GetConfig did not return the expected value.")
        'Assert.Inconclusive("Verify the correctness of this test method.")
    End Sub

End Class
