'The following code was generated by Microsoft Visual Studio 2005.
'The test owner should check each test for validity.
Imports Microsoft.VisualStudio.TestTools.UnitTesting
Imports System
Imports System.Text
Imports System.Collections.Generic
Imports AVPLib.DataManagerment
Imports AVPLib
'''<summary>
'''This is a test class for AVPLib.DataManagerment.TransferModule and is intended
'''to contain all AVPLib.DataManagerment.TransferModule Unit Tests
'''</summary>
<TestClass()> _
Public Class TransferModuleTest


    Private testContextInstance As TestContext

    '''<summary>
    '''Gets or sets the test context which provides
    '''information about and functionality for the current test run.
    '''</summary>
    Public Property TestContext() As TestContext
        Get
            Return testContextInstance
        End Get
        Set(ByVal value As TestContext)
            testContextInstance = Value
        End Set
    End Property
#Region "Additional test attributes"
    '
    'You can use the following additional attributes as you write your tests:
    '
    'Use ClassInitialize to run code before running the first test in the class
    '
    <ClassInitialize()> _
    Public Shared Sub MyClassInitialize(ByVal testContext As TestContext)
        AppDomain.CurrentDomain.SetData("APPBASE", "..\..\..\AVPLibTest\bin\TestData\LoadLockTest\")
        AVPLib.Log.initialize()
        AVPLib.ContainerData.InitConfigStart()
        AVPLib.ContainerData.LoadConfigurationData()
    End Sub
    '
    'Use ClassCleanup to run code after all tests in a class have run
    '
    '<ClassCleanup()>  _
    'Public Shared Sub MyClassCleanup()
    'End Sub
    '
    'Use TestInitialize to run code before running each test
    '
    '<TestInitialize()>  _
    'Public Sub MyTestInitialize()
    'End Sub
    '
    'Use TestCleanup to run code after each test has run
    '
    '<TestCleanup()>  _
    'Public Sub MyTestCleanup()
    'End Sub
    '
#End Region


    '''<summary>
    '''A test for checkCondition2OpenTMHiVac()
    '''</summary>
    <TestMethod()> _
    Public Sub CheckCondition2OpenTMVacTest_Case1()
        Dim target As TransferModule = New TransferModule

        Dim expected As String = Nothing
        Dim actual As String
        target.VacSwitchStatus = Equipment.WorkingStatuses.Off
        actual = target.checkCondition2OpenTMHiVac ''''--->actual has error message
        Assert.AreEqual(expected, actual, "AVPLib.DataManagerment.TransferModule.checkCondition2OpenTMHiVac did not return t" & _
                "he expected value.")
    End Sub
    '''A test for checkCondition2OpenTMHiVac()
    '''</summary>
    <TestMethod()> _
    Public Sub CheckCondition2OpenTMVacTest_Case2()
        Dim target As TransferModule = New TransferModule

        Dim expected As String = Nothing
        Dim actual As String
        target.VacSwitchStatus = Equipment.WorkingStatuses.On
        target.CG = 0.2 ''>0.02
        actual = target.checkCondition2OpenTMHiVac ''''--->actual has error message
        Assert.AreEqual(expected, actual, "AVPLib.DataManagerment.TransferModule.checkCondition2OpenTMHiVac did not return t" & _
                "he expected value.")
    End Sub
    '''<summary>
    '''A test for checkCondition2OpenTMIG()
    '''</summary>
    <TestMethod()> _
    Public Sub CheckCondition2OpenTMIGTest_Case1()
        Dim target As TransferModule = New TransferModule

        Dim expected As String = Nothing
        Dim actual As String
        target.HiVacValveStatus = Equipment.WorkingStatuses.Off

        actual = target.checkCondition2OpenTMIG

        Assert.AreEqual(expected, actual, "AVPLib.DataManagerment.TransferModule.checkCondition2OpenTMIG did not return the " & _
                "expected value.")
    End Sub
    <TestMethod()> _
        Public Sub CheckCondition2OpenTMIGTest_Case2()
        Dim target As TransferModule = New TransferModule
        Dim TMCryo As AVPLib.DataManagerment.TMCryo = CType(AVPLib.DataManagerment.EquipmentManager.GetEquipment(AVPLib.ConstEnum.Equipments.TMCryo.ToString()), AVPLib.DataManagerment.TMCryo)
        Dim expected As String = Nothing
        Dim actual As String
        target.HiVacValveStatus = Equipment.WorkingStatuses.On
        TMCryo.T2 = 1 ''<20
        actual = target.checkCondition2OpenTMIG

        Assert.AreEqual(expected, actual, "AVPLib.DataManagerment.TransferModule.checkCondition2OpenTMIG did not return the " & _
                "expected value.")
    End Sub

    '''<summary>
    ''' <name> Tran Ngoc Khiet </name>
    ''' <date> June 15 2009 </date>
    '''A test for checkCondition2OpenTMRough()
    '' Test case all right
    '''</summary>
    <TestMethod()> _
    Public Sub checkCondition2OpenTMRoughTest_TestNormalCase_001()
        Dim target As TransferModule = New TransferModule
        Dim loadLockA As DataManagerment.LoadLock = CType(DataManagerment.EquipmentManager.GetEquipment(ConstEnum.Equipments.LoadLockA.ToString()), DataManagerment.LoadLock)
        Dim loadLockB As DataManagerment.LoadLock = CType(EquipmentManager.GetEquipment(ConstEnum.Equipments.LoadLockB.ToString()), DataManagerment.LoadLock)
        Dim Chamber1 As DataManagerment.Chamber = CType(EquipmentManager.GetEquipment(ConstEnum.Equipments.Chamber1.ToString()), DataManagerment.Chamber)
        Dim Chamber2 As DataManagerment.Chamber = CType(EquipmentManager.GetEquipment(ConstEnum.Equipments.Chamber2.ToString()), DataManagerment.Chamber)
        Dim Chamber3 As DataManagerment.Chamber = CType(EquipmentManager.GetEquipment(ConstEnum.Equipments.Chamber3.ToString()), DataManagerment.Chamber)
        Dim Chamber4 As DataManagerment.Chamber = CType(EquipmentManager.GetEquipment(ConstEnum.Equipments.Chamber4.ToString()), DataManagerment.Chamber)
        Dim Chamber5 As DataManagerment.Chamber = CType(EquipmentManager.GetEquipment(ConstEnum.Equipments.Chamber5.ToString()), DataManagerment.Chamber)

        Dim expected As String = String.Empty
        Dim actual As String
        ' Is TM Hivac Valve closed?
        target.HiVacValveStatus = Equipment.WorkingStatuses.Off
        ' IS TM IG off?
        target.IGStatus = Equipment.WorkingStatuses.Off
        ' Is all Vent valves closed (both TM and LL)
        loadLockA.SlitValveStatus = Equipment.WorkingStatuses.Off
        loadLockB.SlitValveStatus = Equipment.WorkingStatuses.Off
        Chamber1.SlitValveStatus = Equipment.WorkingStatuses.Off
        Chamber2.SlitValveStatus = Equipment.WorkingStatuses.Off
        Chamber3.SlitValveStatus = Equipment.WorkingStatuses.Off
        Chamber4.SlitValveStatus = Equipment.WorkingStatuses.Off
        Chamber5.SlitValveStatus = Equipment.WorkingStatuses.Off
        ' Is all Vent valves closed (both TM and LL)
        target.FastVentValveStatus = Equipment.WorkingStatuses.Off
        loadLockA.FastVentValveStatus = Equipment.WorkingStatuses.Off
        loadLockB.FastVentValveStatus = Equipment.WorkingStatuses.Off
        loadLockA.SlowVentValveStatus = Equipment.WorkingStatuses.Off
        loadLockB.SlowVentValveStatus = Equipment.WorkingStatuses.Off
        ' is all rough valves closed?
        target.FastRoughValveStatus = Equipment.WorkingStatuses.Off
        loadLockA.FastRoughValveStatus = Equipment.WorkingStatuses.Off
        loadLockB.FastRoughValveStatus = Equipment.WorkingStatuses.Off
        loadLockA.SlowRoughValveStatus = Equipment.WorkingStatuses.Off
        loadLockB.SlowRoughValveStatus = Equipment.WorkingStatuses.Off
        actual = target.checkCondition2OpenTMRough

        Assert.AreEqual(expected, actual, "AVPLib.DataManagerment.TransferModule.checkCondition2OpenTMRough did not return t" & _
                "he expected value.")
    End Sub

    '''<summary>
    ''' <name> Tran Ngoc Khiet </name>
    ''' <date> June 15 2009 </date>
    '''A test for checkCondition2OpenTMRough()
    '' Test case Tm hivac valve not closed
    '''</summary>
    <TestMethod()> _
    Public Sub checkCondition2OpenTMRoughTest_TestNormalCase_002()
        Dim target As TransferModule = New TransferModule
        Dim loadLockA As DataManagerment.LoadLock = CType(DataManagerment.EquipmentManager.GetEquipment(ConstEnum.Equipments.LoadLockA.ToString()), DataManagerment.LoadLock)
        Dim loadLockB As DataManagerment.LoadLock = CType(EquipmentManager.GetEquipment(ConstEnum.Equipments.LoadLockB.ToString()), DataManagerment.LoadLock)
        Dim Chamber1 As DataManagerment.Chamber = CType(EquipmentManager.GetEquipment(ConstEnum.Equipments.Chamber1.ToString()), DataManagerment.Chamber)
        Dim Chamber2 As DataManagerment.Chamber = CType(EquipmentManager.GetEquipment(ConstEnum.Equipments.Chamber2.ToString()), DataManagerment.Chamber)
        Dim Chamber3 As DataManagerment.Chamber = CType(EquipmentManager.GetEquipment(ConstEnum.Equipments.Chamber3.ToString()), DataManagerment.Chamber)
        Dim Chamber4 As DataManagerment.Chamber = CType(EquipmentManager.GetEquipment(ConstEnum.Equipments.Chamber4.ToString()), DataManagerment.Chamber)
        Dim Chamber5 As DataManagerment.Chamber = CType(EquipmentManager.GetEquipment(ConstEnum.Equipments.Chamber5.ToString()), DataManagerment.Chamber)

        Dim expected As String = "TM Hivac Valve did not closed"
        Dim actual As String
        ' Is TM Hivac Valve closed?
        target.HiVacValveStatus = Equipment.WorkingStatuses.Unknown ''' TM hivac valve not closed
        ' target.HiVacValveStatus = Equipment.WorkingStatuses.On ''' TM hivac valve not closed
        ' IS TM IG off?
        target.IGStatus = Equipment.WorkingStatuses.Off
        ' Is all Vent valves closed (both TM and LL)
        loadLockA.SlitValveStatus = Equipment.WorkingStatuses.Off
        loadLockB.SlitValveStatus = Equipment.WorkingStatuses.Off
        Chamber1.SlitValveStatus = Equipment.WorkingStatuses.Off
        Chamber2.SlitValveStatus = Equipment.WorkingStatuses.Off
        Chamber3.SlitValveStatus = Equipment.WorkingStatuses.Off
        Chamber4.SlitValveStatus = Equipment.WorkingStatuses.Off
        Chamber5.SlitValveStatus = Equipment.WorkingStatuses.Off
        ' Is all Vent valves closed (both TM and LL)
        target.FastVentValveStatus = Equipment.WorkingStatuses.Off
        loadLockA.FastVentValveStatus = Equipment.WorkingStatuses.Off
        loadLockB.FastVentValveStatus = Equipment.WorkingStatuses.Off
        loadLockA.SlowVentValveStatus = Equipment.WorkingStatuses.Off
        loadLockB.SlowVentValveStatus = Equipment.WorkingStatuses.Off
        ' is all rough valves closed?
        target.FastRoughValveStatus = Equipment.WorkingStatuses.Off
        loadLockA.FastRoughValveStatus = Equipment.WorkingStatuses.Off
        loadLockB.FastRoughValveStatus = Equipment.WorkingStatuses.Off
        loadLockA.SlowRoughValveStatus = Equipment.WorkingStatuses.Off
        loadLockB.SlowRoughValveStatus = Equipment.WorkingStatuses.Off
        actual = target.checkCondition2OpenTMRough

        Assert.AreEqual(expected, actual, "AVPLib.DataManagerment.TransferModule.checkCondition2OpenTMRough did not return t" & _
                "he expected value.")
    End Sub
    '''<summary>
    ''' <name> Tran Ngoc Khiet </name>
    ''' <date> June 15 2009 </date>
    '''A test for checkCondition2OpenTMRough()
    '' Test case not all rough valves
    '''</summary>
    <TestMethod()> _
    Public Sub checkCondition2OpenTMRoughTest_TestNormalCase_003()
        Dim target As TransferModule = New TransferModule
        Dim loadLockA As DataManagerment.LoadLock = CType(DataManagerment.EquipmentManager.GetEquipment(ConstEnum.Equipments.LoadLockA.ToString()), DataManagerment.LoadLock)
        Dim loadLockB As DataManagerment.LoadLock = CType(EquipmentManager.GetEquipment(ConstEnum.Equipments.LoadLockB.ToString()), DataManagerment.LoadLock)
        Dim Chamber1 As DataManagerment.Chamber = CType(EquipmentManager.GetEquipment(ConstEnum.Equipments.Chamber1.ToString()), DataManagerment.Chamber)
        Dim Chamber2 As DataManagerment.Chamber = CType(EquipmentManager.GetEquipment(ConstEnum.Equipments.Chamber2.ToString()), DataManagerment.Chamber)
        Dim Chamber3 As DataManagerment.Chamber = CType(EquipmentManager.GetEquipment(ConstEnum.Equipments.Chamber3.ToString()), DataManagerment.Chamber)
        Dim Chamber4 As DataManagerment.Chamber = CType(EquipmentManager.GetEquipment(ConstEnum.Equipments.Chamber4.ToString()), DataManagerment.Chamber)
        Dim Chamber5 As DataManagerment.Chamber = CType(EquipmentManager.GetEquipment(ConstEnum.Equipments.Chamber5.ToString()), DataManagerment.Chamber)

        Dim expected As String = "LoadLockA Verify LL Isolation Valve was not Closed"
        Dim actual As String
        ' Is TM Hivac Valve closed?
        target.HiVacValveStatus = Equipment.WorkingStatuses.Off
        ' IS TM IG off?
        target.IGStatus = Equipment.WorkingStatuses.Off
        ' Is all Vent valves closed (both TM and LL)
        loadLockA.SlitValveStatus = Equipment.WorkingStatuses.On    ' Load lock A  not closed
        loadLockB.SlitValveStatus = Equipment.WorkingStatuses.Off
        Chamber1.SlitValveStatus = Equipment.WorkingStatuses.Off
        Chamber2.SlitValveStatus = Equipment.WorkingStatuses.Off
        Chamber3.SlitValveStatus = Equipment.WorkingStatuses.Off
        Chamber4.SlitValveStatus = Equipment.WorkingStatuses.Off
        Chamber5.SlitValveStatus = Equipment.WorkingStatuses.Off
        ' Is all Vent valves closed (both TM and LL)
        target.FastVentValveStatus = Equipment.WorkingStatuses.Off
        loadLockA.FastVentValveStatus = Equipment.WorkingStatuses.Off
        loadLockB.FastVentValveStatus = Equipment.WorkingStatuses.Off
        loadLockA.SlowVentValveStatus = Equipment.WorkingStatuses.Off
        loadLockB.SlowVentValveStatus = Equipment.WorkingStatuses.Off
        ' is all rough valves closed?
        target.FastRoughValveStatus = Equipment.WorkingStatuses.Off
        loadLockA.FastRoughValveStatus = Equipment.WorkingStatuses.Off
        loadLockB.FastRoughValveStatus = Equipment.WorkingStatuses.Off
        loadLockA.SlowRoughValveStatus = Equipment.WorkingStatuses.Off
        loadLockB.SlowRoughValveStatus = Equipment.WorkingStatuses.Off
        actual = target.checkCondition2OpenTMRough
        Assert.AreEqual(expected, actual, "AVPLib.DataManagerment.TransferModule.checkCondition2OpenTMRough did not return t" & _
                "he expected value.")
    End Sub

    '''<summary>
    ''' <name> Tran Ngoc Khiet </name>
    ''' <date> June 15 2009 </date>
    '''A test for checkCondition2OpenTMVent()
    '' Test case right
    '''</summary>
    <TestMethod()> _
    Public Sub checkCondition2OpenTMVentTest_TestNormalCase_001()
        Dim target As TransferModule = New TransferModule
        Dim loadLockA As DataManagerment.LoadLock = CType(DataManagerment.EquipmentManager.GetEquipment(ConstEnum.Equipments.LoadLockA.ToString()), DataManagerment.LoadLock)
        Dim loadLockB As DataManagerment.LoadLock = CType(EquipmentManager.GetEquipment(ConstEnum.Equipments.LoadLockB.ToString()), DataManagerment.LoadLock)
        Dim Chamber1 As DataManagerment.Chamber = CType(EquipmentManager.GetEquipment(ConstEnum.Equipments.Chamber1.ToString()), DataManagerment.Chamber)
        Dim Chamber2 As DataManagerment.Chamber = CType(EquipmentManager.GetEquipment(ConstEnum.Equipments.Chamber2.ToString()), DataManagerment.Chamber)
        Dim Chamber3 As DataManagerment.Chamber = CType(EquipmentManager.GetEquipment(ConstEnum.Equipments.Chamber3.ToString()), DataManagerment.Chamber)
        Dim Chamber4 As DataManagerment.Chamber = CType(EquipmentManager.GetEquipment(ConstEnum.Equipments.Chamber4.ToString()), DataManagerment.Chamber)
        Dim Chamber5 As DataManagerment.Chamber = CType(EquipmentManager.GetEquipment(ConstEnum.Equipments.Chamber5.ToString()), DataManagerment.Chamber)

        Dim expected As String = String.Empty
        Dim actual As String
        target.HiVacValveStatus = Equipment.WorkingStatuses.Off
        target.IGStatus = Equipment.WorkingStatuses.Off
        loadLockA.SlitValveStatus = Equipment.WorkingStatuses.Off
        loadLockB.SlitValveStatus = Equipment.WorkingStatuses.Off
        Chamber1.SlitValveStatus = Equipment.WorkingStatuses.Off
        Chamber2.SlitValveStatus = Equipment.WorkingStatuses.Off
        Chamber3.SlitValveStatus = Equipment.WorkingStatuses.Off
        Chamber4.SlitValveStatus = Equipment.WorkingStatuses.Off
        Chamber5.SlitValveStatus = Equipment.WorkingStatuses.Off
        target.FastRoughValveStatus = Equipment.WorkingStatuses.Off
        actual = target.checkCondition2OpenTMVent
        Assert.AreEqual(expected, actual, "AVPLib.DataManagerment.TransferModule.checkCondition2OpenTMVent did not return th" & _
                "e expected value.")
    End Sub
    '''<summary>
    ''' <name> Tran Ngoc Khiet </name>
    ''' <date> June 15 2009 </date>
    '''A test for checkCondition2OpenTMVent()
    '' Test case with TM hivac valve not closed
    '''</summary>
    <TestMethod()> _
    Public Sub checkCondition2OpenTMVentTest_TestNormalCase_002()
        Dim target As TransferModule = New TransferModule
        Dim loadLockA As DataManagerment.LoadLock = CType(DataManagerment.EquipmentManager.GetEquipment(ConstEnum.Equipments.LoadLockA.ToString()), DataManagerment.LoadLock)
        Dim loadLockB As DataManagerment.LoadLock = CType(EquipmentManager.GetEquipment(ConstEnum.Equipments.LoadLockB.ToString()), DataManagerment.LoadLock)
        Dim Chamber1 As DataManagerment.Chamber = CType(EquipmentManager.GetEquipment(ConstEnum.Equipments.Chamber1.ToString()), DataManagerment.Chamber)
        Dim Chamber2 As DataManagerment.Chamber = CType(EquipmentManager.GetEquipment(ConstEnum.Equipments.Chamber2.ToString()), DataManagerment.Chamber)
        Dim Chamber3 As DataManagerment.Chamber = CType(EquipmentManager.GetEquipment(ConstEnum.Equipments.Chamber3.ToString()), DataManagerment.Chamber)
        Dim Chamber4 As DataManagerment.Chamber = CType(EquipmentManager.GetEquipment(ConstEnum.Equipments.Chamber4.ToString()), DataManagerment.Chamber)
        Dim Chamber5 As DataManagerment.Chamber = CType(EquipmentManager.GetEquipment(ConstEnum.Equipments.Chamber5.ToString()), DataManagerment.Chamber)

        Dim expected As String = "TransferModule Hivac Valve did not closed"
        Dim actual As String
        target.HiVacValveStatus = Equipment.WorkingStatuses.On   ' TM hivac not closed
        target.IGStatus = Equipment.WorkingStatuses.Off
        loadLockA.SlitValveStatus = Equipment.WorkingStatuses.Off
        loadLockB.SlitValveStatus = Equipment.WorkingStatuses.Off
        Chamber1.SlitValveStatus = Equipment.WorkingStatuses.Off
        Chamber2.SlitValveStatus = Equipment.WorkingStatuses.Off
        Chamber3.SlitValveStatus = Equipment.WorkingStatuses.Off
        Chamber4.SlitValveStatus = Equipment.WorkingStatuses.Off
        Chamber5.SlitValveStatus = Equipment.WorkingStatuses.Off
        target.FastRoughValveStatus = Equipment.WorkingStatuses.Off
        actual = target.checkCondition2OpenTMVent
        Assert.AreEqual(expected, actual, "AVPLib.DataManagerment.TransferModule.checkCondition2OpenTMVent did not return th" & _
                "e expected value.")
    End Sub
End Class
