'The following code was generated by Microsoft Visual Studio 2005.
'The test owner should check each test for validity.
Imports Microsoft.VisualStudio.TestTools.UnitTesting
Imports System
Imports System.Text
Imports System.Collections.Generic
Imports AVPLib.Communication.TerminalDriver
Imports System.Collections






'''<summary>
'''This is a test class for AVPLib.Communication.TerminalDriver.TSAlignerResultDecoder and is intended
'''to contain all AVPLib.Communication.TerminalDriver.TSAlignerResultDecoder Unit Tests
'''</summary>
<TestClass()> _
Public Class TSAlignerResultDecoderTest


    Private testContextInstance As TestContext

    '''<summary>
    '''Gets or sets the test context which provides
    '''information about and functionality for the current test run.
    '''</summary>
    Public Property TestContext() As TestContext
        Get
            Return testContextInstance
        End Get
        Set(ByVal value As TestContext)
            testContextInstance = Value
        End Set
    End Property
#Region "Additional test attributes"
    '
    'You can use the following additional attributes as you write your tests:
    '
    'Use ClassInitialize to run code before running the first test in the class
    '
    '<ClassInitialize()>  _
    'Public Shared Sub MyClassInitialize(ByVal testContext As TestContext)
    'End Sub
    '
    'Use ClassCleanup to run code after all tests in a class have run
    '
    '<ClassCleanup()>  _
    'Public Shared Sub MyClassCleanup()
    'End Sub
    '
    'Use TestInitialize to run code before running each test
    '
    '<TestInitialize()>  _
    'Public Sub MyTestInitialize()
    'End Sub
    '
    'Use TestCleanup to run code after each test has run
    '
    '<TestCleanup()>  _
    'Public Sub MyTestCleanup()
    'End Sub
    '
#End Region

    <ClassInitialize()> _
    Public Shared Sub MyClassInitialize(ByVal testContext As TestContext)
        AVPLib.Log.initialize()
    End Sub

    '''<summary>
    '''A test for Decode(ByVal String)
    '''</summary>
    <TestMethod()> _
    Public Sub DecodeTest()
        Dim target As TSAlignerResultDecoder = New TSAlignerResultDecoder

        Dim MessageValue As String = "DATA 3518 0972 00515 04762 N"

        Dim expected As ArrayList = New ArrayList
        Dim actual As ArrayList = Nothing

        Dim AlignerOperatingStatus As AVPLib.DataManagerment.Equipment.OperationStatuses = _
        AVPLib.DataManagerment.Equipment.OperationStatuses.READY
        Dim RSLTAngularLocation As Integer = 3518
        Dim RSLTEccentricityAngle As Integer = 972
        Dim RSLTMaxEccentricity As Integer = 515
        Dim RSLTAvgCCD As Integer = 4762
        Dim RSLTReScanNeed As Boolean = False
        Dim RSLTTypeCode As Integer = -1

        expected.Add(AlignerOperatingStatus)
        expected.Add(RSLTAngularLocation)
        expected.Add(RSLTEccentricityAngle)
        expected.Add(RSLTMaxEccentricity)
        expected.Add(RSLTAvgCCD)
        expected.Add(RSLTReScanNeed)
        expected.Add(RSLTTypeCode)

        actual = target.Decode(MessageValue)

        CollectionAssert.AreEqual(expected, actual, "AVPLib.Communication.TerminalDriver.TSAlignerResultDecoder.Decode did not " & _
                "the expected value.")
    End Sub

End Class
