'The following code was generated by Microsoft Visual Studio 2005.
'The test owner should check each test for validity.
Imports Microsoft.VisualStudio.TestTools.UnitTesting
Imports System
Imports System.Text
Imports System.Collections.Generic
Imports AVPLib.Communication.TerminalDriver
Imports System.Collections






'''<summary>
'''This is a test class for AVPLib.Communication.TerminalDriver.TSRobotRqStnDecoder and is intended
'''to contain all AVPLib.Communication.TerminalDriver.TSRobotRqStnDecoder Unit Tests
'''</summary>
<TestClass()> _
Public Class TSRobotRqStnDecoderTest


    Private testContextInstance As TestContext

    '''<summary>
    '''Gets or sets the test context which provides
    '''information about and functionality for the current test run.
    '''</summary>
    Public Property TestContext() As TestContext
        Get
            Return testContextInstance
        End Get
        Set(ByVal value As TestContext)
            testContextInstance = Value
        End Set
    End Property
#Region "Additional test attributes"
    '
    'You can use the following additional attributes as you write your tests:
    '
    'Use ClassInitialize to run code before running the first test in the class
    '
    '<ClassInitialize()>  _
    'Public Shared Sub MyClassInitialize(ByVal testContext As TestContext)
    'End Sub
    '
    'Use ClassCleanup to run code after all tests in a class have run
    '
    '<ClassCleanup()>  _
    'Public Shared Sub MyClassCleanup()
    'End Sub
    '
    'Use TestInitialize to run code before running each test
    '
    '<TestInitialize()>  _
    'Public Sub MyTestInitialize()
    'End Sub
    '
    'Use TestCleanup to run code after each test has run
    '
    '<TestCleanup()>  _
    'Public Sub MyTestCleanup()
    'End Sub
    '
#End Region

    <ClassInitialize()> _
    Public Shared Sub MyClassInitialize(ByVal testContext As TestContext)
        AVPLib.Log.initialize()
    End Sub

    '''<summary>
    '''A test for Decode(ByVal String)
    '''</summary>
    <TestMethod()> _
    Public Sub DecodeTest()
        Dim target As TSRobotRqStnDecoder = New TSRobotRqStnDecoder

        Dim MessageValue As String = "STN 0009 0669324 019197 005500 005500 0000 000000"

        Dim expected As ArrayList = New ArrayList()
        Dim actual As ArrayList

        Dim RobotOperatingStatus As AVPLib.DataManagerment.Equipment.OperationStatuses = _
        AVPLib.DataManagerment.Equipment.OperationStatuses.READY
        Dim ReqAlStn_R As Integer = 669324
        Dim ReqAlStn_Traw As Integer = 19197
        Dim ReqAlStn_Z As Integer = 5500
        Dim ReqLOWER As Integer = 5500
        Dim ReqNSLOTS As Integer = 0
        Dim ReqPITCH As Integer = 0

        expected.Add(RobotOperatingStatus)
        expected.Add(ReqAlStn_R)
        expected.Add(ReqAlStn_Traw)
        expected.Add(ReqAlStn_Z)
        expected.Add(ReqLOWER)
        expected.Add(ReqNSLOTS)
        expected.Add(ReqPITCH)

        actual = target.Decode(MessageValue)

        CollectionAssert.AreEqual(expected, actual, "AVPLib.Communication.TerminalDriver.TSRobotRqStnDecoder.Decode did not return the" & _
                " expected value.")
    End Sub

End Class
