'The following code was generated by Microsoft Visual Studio 2005.
'The test owner should check each test for validity.
Imports Microsoft.VisualStudio.TestTools.UnitTesting
Imports System
Imports System.Text
Imports System.Collections.Generic
Imports System.Xml
Imports AVPLib
Imports System.Collections

'''<summary>
'''This is a test class for AVPLib.UserSetupLib and is intended
'''to contain all AVPLib.UserSetupLib Unit Tests
'''</summary>
<TestClass()> _
Public Class UserSetupLibTest

    Private Shared UserDoc As XmlDocument = Nothing 'TODO: Initialize to an appropriate value
    Private testContextInstance As TestContext
    Private Shared userOperator As New AVPLib.DBUser
    Private Shared userAdmin As New AVPLib.DBUser
    Private Shared userNormal As New AVPLib.DBUser
    Private Shared userAnother As New AVPLib.DBUser
    Private Shared ArrPermission_Normal As New Collections.ArrayList
    Private Shared ArrPermission_Operator As New Collections.ArrayList
    Private Shared ArrPermission_Admin As New Collections.ArrayList
    Private Shared ArrPermission_Another As New Collections.ArrayList
    '''<summary>
    '''Gets or sets the test context which provides
    '''information about and functionality for the current test run.
    '''</summary>
    Public Property TestContext() As TestContext
        Get
            Return testContextInstance
        End Get
        Set(ByVal value As TestContext)
            testContextInstance = value
        End Set
    End Property
#Region "Additional test attributes"
    '
    'You can use the following additional attributes as you write your tests:
    '
    'Use ClassInitialize to run code before running the first test in the class
    '
    <ClassInitialize()> _
    Public Shared Sub MyClassInitialize(ByVal testContext As TestContext)
        'Create an XmlWriterSettings instance.
        AppDomain.CurrentDomain.SetData("APPBASE", "..\..\..\AVPLibTest\bin\TestData\UserSetupLibTest_GetUserFunction")
        AVPLib.Log.initialize()

        Dim oSettings As XmlWriterSettings = New XmlWriterSettings()
        oSettings.Indent = True
        oSettings.OmitXmlDeclaration = True
        oSettings.Encoding = Encoding.ASCII

        Dim XmlFPath As String = AppDomain.CurrentDomain.SetupInformation.ApplicationBase + "\Group.xml"

        Dim UserPermission As AVPLib.DBUserPermission
        Dim writer As XmlWriter = XmlWriter.Create(XmlFPath, oSettings)

        writer.WriteStartDocument(True)
        writer.WriteStartElement("Groups")

        writer.WriteStartElement("Group")
        writer.WriteAttributeString("id", "1")
        writer.WriteString("Administrator")
        writer.WriteEndElement()

        writer.WriteStartElement("Group")
        writer.WriteAttributeString("id", "2")
        writer.WriteString("Operator")
        writer.WriteEndElement()

        writer.WriteEndElement()
        writer.WriteEndDocument()
        writer.Flush()
        writer.Close()

        'User file
        XmlFPath = AppDomain.CurrentDomain.SetupInformation.ApplicationBase + "\User.xml"
        writer = XmlWriter.Create(XmlFPath, oSettings)

        writer.WriteStartDocument(True)
        writer.WriteStartElement("Users")
        writer.WriteString(Chr(13))
        writer.WriteEndElement()
        writer.WriteEndDocument()
        writer.Flush()
        writer.Close()

        UserDoc = New XmlDocument()
        UserDoc.Load(XmlFPath)

        userAdmin.Username = "Admins"
        userAdmin.Password = "12345"
        userAdmin.Disable = False
        userAdmin.Group = New AVPLib.DBGroup(1, userAdmin.Username)
        UserPermission = New AVPLib.DBUserPermission("001", "Cassette and Robot Maintenance", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("002", "System Configuration", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("003", "User Maintenance", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("004", "HR PVD Chamber Maintenance", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("005", "Recipe Editor", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("006", "Transfer Chamber Maintenance", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("007", "Wafer Analysis", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("008", "System Maintenance", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("009", "Sequence Editor", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("010", "Operator", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("011", "DataLog", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("012", "Ecth Chamber Maintenance", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("013", "User Setup", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("014", "Alarm", True)
        ArrPermission_Admin.Add(UserPermission)

        userAdmin.ListPermission = ArrPermission_Admin
        SaveUser(UserDoc, userAdmin)
        ''''''''''''''''''''''''''
        userOperator.Username = "Operator"
        userOperator.Password = "OPERATOR"
        userOperator.Disable = False
        userOperator.Group = New AVPLib.DBGroup(2, userOperator.Username)
        UserPermission = New AVPLib.DBUserPermission("001", "Cassette and Robot Maintenance", True)
        ArrPermission_Operator.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("002", "System Configuration", True)
        ArrPermission_Operator.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("003", "User Maintenance", False)
        ArrPermission_Operator.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("004", "HR PVD Chamber Maintenance", False)
        ArrPermission_Operator.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("005", "Recipe Editor", True)
        ArrPermission_Operator.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("006", "Transfer Chamber Maintenance", False)
        ArrPermission_Operator.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("007", "Wafer Analysis", True)
        ArrPermission_Operator.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("008", "System Maintenance", False)
        ArrPermission_Operator.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("009", "Sequence Editor", True)
        ArrPermission_Operator.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("010", "Operator", True)
        ArrPermission_Operator.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("011", "DataLog", True)
        ArrPermission_Operator.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("012", "Ecth Chamber Maintenance", False)
        ArrPermission_Operator.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("013", "User Setup", False)
        ArrPermission_Operator.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("014", "Alarm", True)
        ArrPermission_Operator.Add(UserPermission)
        userOperator.ListPermission = ArrPermission_Operator
        SaveUser(UserDoc, userOperator)
        ''''''''''''''''''''''''''''''
        userNormal.Username = "kiet"
        userNormal.Password = "111"
        userNormal.Disable = False
        userNormal.Group = New AVPLib.DBGroup(1, userNormal.Username)
        UserPermission = New AVPLib.DBUserPermission("001", "Cassette and Robot Maintenance", False)
        ArrPermission_Normal.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("002", "System Configuration", False)
        ArrPermission_Normal.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("003", "User Maintenance", False)
        ArrPermission_Normal.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("004", "HR PVD Chamber Maintenance", False)
        ArrPermission_Normal.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("005", "Recipe Editor", False)
        ArrPermission_Normal.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("006", "Transfer Chamber Maintenance", False)
        ArrPermission_Normal.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("007", "Wafer Analysis", False)
        ArrPermission_Normal.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("008", "System Maintenance", True)
        ArrPermission_Normal.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("009", "Sequence Editor", True)
        ArrPermission_Normal.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("010", "Operator", False)
        ArrPermission_Normal.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("011", "DataLog", True)
        ArrPermission_Normal.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("012", "Ecth Chamber Maintenance", False)
        ArrPermission_Normal.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("013", "User Setup", False)
        ArrPermission_Normal.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("014", "Alarm", False)
        ArrPermission_Normal.Add(UserPermission)
        userNormal.ListPermission = ArrPermission_Normal
        SaveUser(UserDoc, userNormal)

        ''
        userAnother.Username = "truc"
        userAnother.Password = "9999"
        userAnother.Disable = False
        userAnother.Group = New AVPLib.DBGroup(1, userAnother.Username)
        UserPermission = New AVPLib.DBUserPermission("001", "Cassette and Robot Maintenance", True)
        ArrPermission_Another.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("002", "System Configuration", False)
        ArrPermission_Another.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("003", "User Maintenance", False)
        ArrPermission_Another.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("004", "HR PVD Chamber Maintenance", False)
        ArrPermission_Another.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("005", "Recipe Editor", False)
        ArrPermission_Another.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("006", "Transfer Chamber Maintenance", False)
        ArrPermission_Another.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("007", "Wafer Analysis", False)
        ArrPermission_Another.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("008", "System Maintenance", True)
        ArrPermission_Another.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("009", "Sequence Editor", True)
        ArrPermission_Another.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("010", "Operator", False)
        ArrPermission_Another.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("011", "DataLog", True)
        ArrPermission_Another.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("012", "Ecth Chamber Maintenance", False)
        ArrPermission_Another.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("013", "User Setup", False)
        ArrPermission_Another.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("014", "Alarm", False)
        ArrPermission_Another.Add(UserPermission)
        userAnother.ListPermission = ArrPermission_Another
        SaveUser(UserDoc, userAnother)
        AppDomain.CurrentDomain.SetData("APPBASE", "..\..\..\AVP_Robot_Project\bin\Debug\")
    End Sub
    Private Shared Function SaveUser(ByVal UserDoc As System.Xml.XmlDocument, ByVal user As DBUser) As DBUser
        Try
            Dim root As System.Xml.XmlNode = UserDoc.FirstChild
            Dim UserNode As System.Xml.XmlNode = UserDoc.CreateElement("User")
            Dim Username As System.Xml.XmlNode = UserDoc.CreateElement("Username")
            Username.InnerText = user.Username
            UserNode.AppendChild(Username)
            Dim Password As System.Xml.XmlNode = UserDoc.CreateElement("Password")
            Password.InnerText = user.Password
            UserNode.AppendChild(Password)
            Dim Group As System.Xml.XmlNode = UserDoc.CreateElement("Group")
            Group.InnerText = user.Group.Id.ToString()
            UserNode.AppendChild(Group)
            Dim Disable As System.Xml.XmlNode = UserDoc.CreateElement("Disable")
            Disable.InnerText = CStr(Math.Abs(CInt(user.Disable)))
            UserNode.AppendChild(Disable)

            Dim AccessList As System.Xml.XmlNode = UserDoc.CreateElement("AccessList")
            For i As Integer = 0 To user.ListPermission.Count - 1
                Dim Access As System.Xml.XmlNode = UserDoc.CreateElement("Access")
                Dim Permit As System.Xml.XmlAttribute = UserDoc.CreateAttribute("Permit")
                Dim DBUserPermission As DBUserPermission = CType(user.ListPermission.Item(i), DBUserPermission)
                Permit.Value = CStr(Math.Abs(CInt(DBUserPermission.Permit)))
                Dim Code As System.Xml.XmlAttribute = UserDoc.CreateAttribute("Code")
                Code.Value = DBUserPermission.Code
                Access.Attributes.Append(Permit)
                Access.Attributes.Append(Code)
                Access.InnerText = DBUserPermission.Name
                AccessList.AppendChild(Access)
            Next

            UserNode.AppendChild(AccessList)
            root.AppendChild(UserNode)
            UserDoc.Save(UserDoc.BaseURI.Substring(UserDoc.BaseURI.LastIndexOf("///") + 3))
        Catch ex As Exception
            Microsoft.VisualBasic.MsgBox(ex.ToString())
        End Try
        Return user
    End Function
    '
    'Use ClassCleanup to run code after all tests in a class have run
    '
    '<ClassCleanup()>  _
    'Public Shared Sub MyClassCleanup()
    'End Sub
    '
    'Use TestInitialize to run code before running each test
    '
    '<TestInitialize()>  _
    'Public Sub MyTestInitialize()
    'End Sub
    '
    'Use TestCleanup to run code after each test has run
    '
    '<TestCleanup()>  _
    'Public Sub MyTestCleanup()
    'End Sub
    '
#End Region


    '''<summary>
    '''A test for GetUser(ByVal System.Xml.XmlDocument, ByVal String)
    '''</summary>
    <TestMethod()> _
    Public Sub GetUserTest()
        UserDoc.Load("..\..\..\AVPLibTest\bin\TestData\UserSetupLibTest_GetUserFunction\User.xml")
        Dim Username As String = Nothing 'TODO: Initialize to an appropriate value
        'Dim result As String = String.Empty
        Dim expected As DBUser = Nothing
        Dim actual As DBUser
        Dim i As Integer = 1
        Dim ExpectedPermission As AVPLib.DBUserPermission
        Dim ActualPermission As AVPLib.DBUserPermission

        Username = "Operator"
        expected = userOperator

        actual = AVPLib.UserSetupLib.GetUser(UserDoc, Username)
        Assert.AreEqual(expected.Username.ToString(), actual.Username.ToString(), "AVPLib.UserSetupLib.GetUser.UserName did not return the expected value.")

        Assert.AreEqual(expected.Password, actual.Password, "AVPLib.UserSetupLib.GetUser.Password did not return the expected value.")

        Assert.AreEqual(expected.Disable, actual.Disable, "AVPLib.UserSetupLib.GetUser.Disable did not return the expected value.")

        For i = 0 To 13
            ExpectedPermission = CType(expected.ListPermission.Item(i), AVPLib.DBUserPermission)
            ActualPermission = CType(actual.ListPermission.Item(i), AVPLib.DBUserPermission)
            Assert.AreEqual(ExpectedPermission.Name, ActualPermission.Name, "AVPLib.UserSetupLib.GetUser.Name did not return the expected value.")
            Assert.AreEqual(ExpectedPermission.Permit, ActualPermission.Permit, "AVPLib.UserSetupLib.GetUser.Permit did not return the expected value.")
            Assert.AreEqual(ExpectedPermission.Code, ActualPermission.Code, "AVPLib.UserSetupLib.GetUser.Code did not return the expected value.")
        Next

        Assert.AreEqual(expected.Group.Id, actual.Group.Id, "AVPLib.UserSetupLib.GetUser.Group.ID did not return the expected value.")
        Assert.AreEqual(expected.Group.Name.ToString(), actual.Group.Name.ToString(), "AVPLib.UserSetupLib.GetUser.Group.Name did not return the expected value.")

        ''Test admin user
        Username = "Admins"
        expected = userAdmin
        actual = AVPLib.UserSetupLib.GetUser(UserDoc, Username)
        Assert.AreEqual(expected.Username.ToString(), actual.Username.ToString(), "AVPLib.UserSetupLib.GetUser.Username did not return the expected value.")
        Assert.AreEqual(expected.Password, actual.Password, "AVPLib.UserSetupLib.GetUser.Password did not return the expected value.")
        Assert.AreEqual(expected.Disable, actual.Disable, "AVPLib.UserSetupLib.GetUser.Disable did not return the expected value.")

        For i = 0 To 13
            ExpectedPermission = CType(expected.ListPermission.Item(i), AVPLib.DBUserPermission)
            ActualPermission = CType(actual.ListPermission.Item(i), AVPLib.DBUserPermission)
            Assert.AreEqual(ExpectedPermission.Name, ActualPermission.Name, "AVPLib.UserSetupLib.GetUser.Name did not return the expected value.")
            Assert.AreEqual(ExpectedPermission.Permit, ActualPermission.Permit, "AVPLib.UserSetupLib.GetUser.Permit did not return the expected value.")
            Assert.AreEqual(ExpectedPermission.Code, ActualPermission.Code, "AVPLib.UserSetupLib.GetUser.Code did not return the expected value.")
        Next

        Assert.AreEqual(1, actual.Group.Id, "AVPLib.UserSetupLib.GetUser.Group.ID did not return the expected value.")
        Assert.AreEqual("Administrator", actual.Group.Name.ToString(), "AVPLib.UserSetupLib.GetUser.Group.Name did not return the expected value.")

        ' ''Test User normal
        Username = "kiet"
        expected = userNormal
        actual = AVPLib.UserSetupLib.GetUser(UserDoc, Username)
        Assert.AreEqual(expected.Username.ToString(), actual.Username.ToString(), "AVPLib.UserSetupLib.GetUser.Username did not return the expected value.")
        Assert.AreEqual(expected.Password, actual.Password, "AVPLib.UserSetupLib.GetUser.Password did not return the expected value.")
        Assert.AreEqual(expected.Disable, actual.Disable, "AVPLib.UserSetupLib.GetUser.Disable did not return the expected value.")

        For i = 0 To 13
            ExpectedPermission = CType(expected.ListPermission.Item(i), AVPLib.DBUserPermission)
            ActualPermission = CType(actual.ListPermission.Item(i), AVPLib.DBUserPermission)
            Assert.AreEqual(ExpectedPermission.Name, ActualPermission.Name, "AVPLib.UserSetupLib.GetUser.Name did not return the expected value.")
            Assert.AreEqual(ExpectedPermission.Permit, ActualPermission.Permit, "AVPLib.UserSetupLib.GetUser.Permit did not return the expected value.")
            Assert.AreEqual(ExpectedPermission.Code, ActualPermission.Code, "AVPLib.UserSetupLib.GetUser.Code did not return the expected value.")
        Next

        Assert.AreEqual(1, actual.Group.Id, "AVPLib.UserSetupLib.GetUser.Group.ID did not return the expected value.")
        Assert.AreEqual("Administrator", actual.Group.Name.ToString(), "AVPLib.UserSetupLib.GetUser.Group.Name did not return the expected value.")
    End Sub


    '''<summary>
    '''A test for GetListUser(ByVal System.Xml.XmlDocument)
    '''</summary>
    <TestMethod()> _
    Public Sub GetListUserTest_NormalCase()
        '    Dim UserDoc As XmlDocument = Nothing 'TODO: Initialize to an appropriate value
        UserDoc.Load("..\..\..\AVPLibTest\bin\TestData\UserSetupLibTest_GetListUserFunction_NormalCase\User.xml")
        'Dim expected As New ArrayList
        'Dim actual As ArrayList
        'expected.Add("Admins")
        'expected.Add("Operator")
        'expected.Add("kiet")
        'expected.Add("truc")

        'actual = AVPLib.UserSetupLib.GetListUser(UserDoc)
        'THIS IS WRONG
        'CollectionAssert.AreEqual(expected, actual, "AVPLib.UserSetupLib.GetListUser did not return the expected value.")
        '   Assert.Inconclusive("Verify the correctness of this test method.")
    End Sub
    '''<summary>
    '''A test for GetListUser(ByVal System.Xml.XmlDocument)
    '''</summary>
    <TestMethod()> _
    Public Sub GetListUserTest_SpecialCase()
        '    Dim UserDoc As XmlDocument = Nothing 'TODO: Initialize to an appropriate value
        UserDoc.Load("..\..\..\AVPLibTest\bin\TestData\UserSetupLibTest_GetListUserFunction_SpecialCase\User2.xml")

        'Dim expected As New ArrayList
        'Dim actual As ArrayList
        'expected.Add("Admins")
        'expected.Add("Operator")
        'expected.Add("kiet")
        'expected.Add("truc")
        'expected.Add("trucle")

        'actual = AVPLib.UserSetupLib.GetListUser(UserDoc)

        'CollectionAssert.AreEqual(expected, actual, "AVPLib.UserSetupLib.GetListUser did not return the expected value.")
        '   Assert.Inconclusive("Verify the correctness of this test method.")
    End Sub

    '''<summary>
    '''A test for SaveUser(ByVal System.Xml.XmlDocument, ByVal AVPLib.DBUser)
    '''</summary>
    <TestMethod()> _
    Public Sub SaveUserTest_NormalCase()
        UserDoc.Load("..\..\..\AVPLibTest\bin\TestData\UserSetupLibTest_SaveUserFunction_NormalCase\User2.xml")
        'Dim UserDoc As XmlDocument = Nothing 'TODO: Initialize to an appropriate value
        Dim UserPermission As AVPLib.DBUserPermission
        Dim user As DBUser = Nothing 'TODO: Initialize to an appropriate value

        'Dim expected As DBUser = Nothing
        Dim actual As DBUser
        ArrPermission_Admin.Clear()
        userAdmin.Username = "Admininistrator"
        userAdmin.Password = "123456789"
        userAdmin.Disable = False
        userAdmin.Group = New AVPLib.DBGroup(1, userAdmin.Username)
        UserPermission = New AVPLib.DBUserPermission("001", "Cassette and Robot Maintenance", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("002", "System Configuration", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("003", "User Maintenance", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("004", "HR PVD Chamber Maintenance", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("005", "Recipe Editor", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("006", "Transfer Chamber Maintenance", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("007", "Wafer Analysis", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("008", "System Maintenance", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("009", "Sequence Editor", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("010", "Operator", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("011", "DataLog", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("012", "Ecth Chamber Maintenance", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("013", "User Setup", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("014", "Alarm", True)
        ArrPermission_Admin.Add(UserPermission)

        userAdmin.ListPermission = ArrPermission_Admin
        '  SaveUser(UserDoc, userAdmin)
        user = userAdmin

        actual = AVPLib.UserSetupLib.SaveUser(UserDoc, user)

        Assert.AreEqual(user.Username, actual.Username, "AVPLib.UserSetupLib.SaveUser.UserName did not return the expected value.")
        Assert.AreEqual(user.Password, actual.Password, "AVPLib.UserSetupLib.SaveUser.Password did not return the expected value.")
        Assert.AreEqual(Of Boolean)(user.Disable, actual.Disable, "AVPLib.UserSetupLib.SaveUser.Disable did not return the expected value.")
        Assert.AreEqual(user.Group.Id, actual.Group.Id, "AVPLib.UserSetupLib.SaveUser.Group.ID did not return the expected value.")
        Assert.AreEqual(user.Group.Name.ToString(), actual.Group.Name.ToString(), "AVPLib.UserSetupLib.SaveUser.Group.Name did not return the expected value.")
        CollectionAssert.AreEqual(user.ListPermission, actual.ListPermission, "AVPLib.UserSetupLib.SaveUser.ListPermission did not return the expected value.")
    End Sub
    <TestMethod()> _
    Public Sub SaveUserTest_SpecialCase()
        UserDoc.Load("..\..\..\AVPLibTest\bin\TestData\UserSetupLibTest_SaveUserFunction_SpecialCase\User2.xml")
        'Dim UserDoc As XmlDocument = Nothing 'TODO: Initialize to an appropriate value
        Dim UserPermission As AVPLib.DBUserPermission
        Dim user As DBUser = Nothing 'TODO: Initialize to an appropriate value

        'Dim expected As DBUser = Nothing
        Dim actual As DBUser
        ArrPermission_Admin.Clear()
        userAdmin.Username = "TestSpecial"
        userAdmin.Password = "123agcd"
        userAdmin.Disable = False
        userAdmin.Group = New AVPLib.DBGroup(2, userAdmin.Username)
        UserPermission = New AVPLib.DBUserPermission("001", "Cassette and Robot Maintenance", False)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("002", "System Configuration", False)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("003", "User Maintenance", False)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("004", "HR PVD Chamber Maintenance", False)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("005", "Recipe Editor", False)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("006", "Transfer Chamber Maintenance", False)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("007", "Wafer Analysis", False)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("008", "System Maintenance", False)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("009", "Sequence Editor", False)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("010", "Operator", False)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("011", "DataLog", False)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("012", "Ecth Chamber Maintenance", False)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("013", "User Setup", False)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("014", "Alarm", False)
        ArrPermission_Admin.Add(UserPermission)

        userAdmin.ListPermission = ArrPermission_Admin
        '  SaveUser(UserDoc, userAdmin)
        user = userAdmin

        actual = AVPLib.UserSetupLib.SaveUser(UserDoc, user)

        Assert.AreEqual(user.Username, actual.Username, "AVPLib.UserSetupLib.SaveUser.UserName did not return the expected value.")
        Assert.AreEqual(user.Password, actual.Password, "AVPLib.UserSetupLib.SaveUser.Password did not return the expected value.")
        Assert.AreEqual(Of Boolean)(user.Disable, actual.Disable, "AVPLib.UserSetupLib.SaveUser.Disable did not return the expected value.")
        Assert.AreEqual(user.Group.Id, actual.Group.Id, "AVPLib.UserSetupLib.SaveUser.Group.ID did not return the expected value.")
        Assert.AreEqual(user.Group.Name.ToString(), actual.Group.Name.ToString(), "AVPLib.UserSetupLib.SaveUser.Group.Name did not return the expected value.")
        CollectionAssert.AreEqual(user.ListPermission, actual.ListPermission, "AVPLib.UserSetupLib.SaveUser.ListPermission did not return the expected value.")
    End Sub

    '''<summary>
    '''A test for UpdateUser(ByVal System.Xml.XmlDocument, ByVal AVPLib.DBUser)
    '''</summary>
    <TestMethod()> _
    Public Sub UpdateUserTest_NormalCase()
        UserDoc.Load("..\..\..\AVPLibTest\bin\TestData\UserSetupLibTest_UpdateUserFunction_NormalCase\User2.xml")
        'Dim UserDoc As XmlDocument = Nothing 'TODO: Initialize to an appropriate value
        Dim UserPermission As AVPLib.DBUserPermission
        Dim user As DBUser = Nothing 'TODO: Initialize to an appropriate value

        'Dim expected As DBUser = Nothing
        Dim actual As DBUser
        ArrPermission_Admin.Clear()
        userAdmin.Username = "Admininistrator"
        userAdmin.Password = "123456"
        userAdmin.Disable = False
        userAdmin.Group = New AVPLib.DBGroup(1, userAdmin.Username)
        UserPermission = New AVPLib.DBUserPermission("001", "Cassette and Robot Maintenance", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("002", "System Configuration", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("003", "User Maintenance", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("004", "HR PVD Chamber Maintenance", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("005", "Recipe Editor", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("006", "Transfer Chamber Maintenance", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("007", "Wafer Analysis", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("008", "System Maintenance", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("009", "Sequence Editor", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("010", "Operator", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("011", "DataLog", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("012", "Ecth Chamber Maintenance", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("013", "User Setup", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("014", "Alarm", True)
        ArrPermission_Admin.Add(UserPermission)

        userAdmin.ListPermission = ArrPermission_Admin
        '  SaveUser(UserDoc, userAdmin)
        user = userAdmin

        actual = AVPLib.UserSetupLib.UpdateUser(UserDoc, user)

        Assert.AreEqual(user.Username, actual.Username, "AVPLib.UserSetupLib.UpdateUser.UserName did not return the expected value.")
        Assert.AreEqual(user.Password, actual.Password, "AVPLib.UserSetupLib.UpdateUser.Password did not return the expected value.")
        Assert.AreEqual(Of Boolean)(user.Disable, actual.Disable, "AVPLib.UserSetupLib.UpdateUser.Disable did not return the expected value.")
        Assert.AreEqual(user.Group.Id, actual.Group.Id, "AVPLib.UserSetupLib.UpdateUser.Group.ID did not return the expected value.")
        Assert.AreEqual(user.Group.Name.ToString(), actual.Group.Name.ToString(), "AVPLib.UserSetupLib.UpdateUser.Group.Name did not return the expected value.")
        CollectionAssert.AreEqual(user.ListPermission, actual.ListPermission, "AVPLib.UserSetupLib.UpdateUser.ListPermission did not return the expected value.")

    End Sub
    <TestMethod()> _
        Public Sub UpdateUserTest_SpecialCase()
        UserDoc.Load("..\..\..\AVPLibTest\bin\TestData\UserSetupLibTest_UpdateUserFunction_SpecialCase\User2.xml")
        'Dim UserDoc As XmlDocument = Nothing 'TODO: Initialize to an appropriate value
        Dim UserPermission As AVPLib.DBUserPermission
        Dim user As DBUser = Nothing 'TODO: Initialize to an appropriate value

        'Dim expected As DBUser = Nothing
        Dim actual As DBUser
        ArrPermission_Admin.Clear()
        userAdmin.Username = "Admin"
        userAdmin.Password = "123456"
        userAdmin.Disable = False
        userAdmin.Group = New AVPLib.DBGroup(3, userAdmin.Username)
        UserPermission = New AVPLib.DBUserPermission("001", "Cassette and Robot Maintenance", False)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("002", "System Configuration", False)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("003", "User Maintenance", False)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("004", "HR PVD Chamber Maintenance", False)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("005", "Recipe Editor", False)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("006", "Transfer Chamber Maintenance", False)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("007", "Wafer Analysis", False)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("008", "System Maintenance", False)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("009", "Sequence Editor", False)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("010", "Operator", False)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("011", "DataLog", False)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("012", "Ecth Chamber Maintenance", False)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("013", "User Setup", False)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("014", "Alarm", False)
        ArrPermission_Admin.Add(UserPermission)

        userAdmin.ListPermission = ArrPermission_Admin
        '  SaveUser(UserDoc, userAdmin)
        user = userAdmin

        actual = AVPLib.UserSetupLib.UpdateUser(UserDoc, user)

        Assert.AreEqual(user.Username, actual.Username, "AVPLib.UserSetupLib.UpdateUser.UserName did not return the expected value.")
        Assert.AreEqual(user.Password, actual.Password, "AVPLib.UserSetupLib.UpdateUser.Password did not return the expected value.")
        Assert.AreEqual(Of Boolean)(user.Disable, actual.Disable, "AVPLib.UserSetupLib.UpdateUser.Disable did not return the expected value.")
        Assert.AreEqual(user.Group.Id, actual.Group.Id, "AVPLib.UserSetupLib.UpdateUser.Group.ID did not return the expected value.")
        Assert.AreEqual(user.Group.Name.ToString(), actual.Group.Name.ToString(), "AVPLib.UserSetupLib.UpdateUser.Group.Name did not return the expected value.")
        CollectionAssert.AreEqual(user.ListPermission, actual.ListPermission, "AVPLib.UserSetupLib.UpdateUser.ListPermission did not return the expected value.")

    End Sub
    '''<summary>
    '''A test for DeleteUser(ByVal System.Xml.XmlDocument, ByVal AVPLib.DBUser)
    '''</summary>
    <TestMethod()> _
    Public Sub DeleteUserTest_Normal()
        UserDoc.Load("..\..\..\AVPLibTest\bin\TestData\UserSetupLibTest_DeleteUserFunction\User2.xml")
        'Dim UserDoc As XmlDocument = Nothing 'TODO: Initialize to an appropriate value
        Dim UserPermission As AVPLib.DBUserPermission
        Dim user As DBUser = Nothing 'TODO: Initialize to an appropriate value

        'Dim expected As DBUser = Nothing
        Dim actual As DBUser
        ArrPermission_Admin.Clear()
        userAdmin.Username = "truc"
        userAdmin.Password = "123456"
        userAdmin.Disable = False
        userAdmin.Group = New AVPLib.DBGroup(1, userAdmin.Username)
        UserPermission = New AVPLib.DBUserPermission("001", "Cassette and Robot Maintenance", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("002", "System Configuration", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("003", "User Maintenance", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("004", "HR PVD Chamber Maintenance", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("005", "Recipe Editor", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("006", "Transfer Chamber Maintenance", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("007", "Wafer Analysis", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("008", "System Maintenance", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("009", "Sequence Editor", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("010", "Operator", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("011", "DataLog", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("012", "Ecth Chamber Maintenance", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("013", "User Setup", True)
        ArrPermission_Admin.Add(UserPermission)
        UserPermission = New AVPLib.DBUserPermission("014", "Alarm", True)
        ArrPermission_Admin.Add(UserPermission)

        userAdmin.ListPermission = ArrPermission_Admin
        '  SaveUser(UserDoc, userAdmin)
        user = userAdmin

        actual = AVPLib.UserSetupLib.DeleteUser(UserDoc, user)

        Assert.AreEqual(user.Username, actual.Username, "AVPLib.UserSetupLib.UpdateUser.UserName did not return the expected value.")
        Assert.AreEqual(user.Password, actual.Password, "AVPLib.UserSetupLib.UpdateUser.Password did not return the expected value.")
        Assert.AreEqual(Of Boolean)(user.Disable, actual.Disable, "AVPLib.UserSetupLib.UpdateUser.Disable did not return the expected value.")
        Assert.AreEqual(user.Group.Id, actual.Group.Id, "AVPLib.UserSetupLib.UpdateUser.Group.ID did not return the expected value.")
        Assert.AreEqual(user.Group.Name.ToString(), actual.Group.Name.ToString(), "AVPLib.UserSetupLib.UpdateUser.Group.Name did not return the expected value.")
        CollectionAssert.AreEqual(user.ListPermission, actual.ListPermission, "AVPLib.UserSetupLib.UpdateUser.ListPermission did not return the expected value.")

    End Sub

    '''<summary>
    '''A test for GetGroup(ByVal System.Xml.XmlDocument, ByVal Integer)
    '''</summary>
    <TestMethod()> _
    Public Sub GetGroupTest_NormalCase()
        ' Dim GroupDoc As XmlDocument = Nothing 'TODO: Initialize to an appropriate value
        UserDoc.Load("..\..\..\AVPLibTest\bin\TestData\UserSetupLibTest_GetGroupFunction_NormalCase\Group.xml")
        Dim Id As Integer 'TODO: Initialize to an appropriate value
        Id = 2
        'Dim expected As DBGroup = Nothing
        Dim actual As DBGroup

        actual = AVPLib.UserSetupLib.GetGroup(UserDoc, Id)

        Assert.AreEqual(2, actual.Id, "AVPLib.UserSetupLib.GetGroup did not return the expected value.")
        Assert.AreEqual("Operator", actual.Name.ToString(), "AVPLib.UserSetupLib.GetGroup did not return the expected value.")

    End Sub
    <TestMethod()> _
     Public Sub GetGroupTest_SpecialCase()
        ' Dim GroupDoc As XmlDocument = Nothing 'TODO: Initialize to an appropriate value
        UserDoc.Load("..\..\..\AVPLibTest\bin\TestData\UserSetupLibTest_GetGroupFunction_SpecialCase\Group.xml")
        Dim Id As Integer 'TODO: Initialize to an appropriate value
        Id = 3
        'Dim expected As DBGroup = Nothing
        Dim actual As DBGroup

        actual = AVPLib.UserSetupLib.GetGroup(UserDoc, Id)

        Assert.AreEqual(3, actual.Id, "AVPLib.UserSetupLib.GetGroup did not return the expected value.")
        Assert.AreEqual("Other", actual.Name.ToString(), "AVPLib.UserSetupLib.GetGroup did not return the expected value.")

    End Sub
    '''<summary>
    '''A test for GetListGroup(ByVal System.Xml.XmlDocument)
    '''</summary>
    <TestMethod()> _
    Public Sub GetListGroupTest_NormalCase()
        UserDoc.Load("..\..\..\AVPLibTest\bin\TestData\UserSetupLibTest_GetListGroupFunction_NormalCase\Group.xml")

        Dim expected As New ArrayList
        Dim actual As ArrayList
        expected.Add(New AVPLib.DBGroup(1, "Administrator"))
        expected.Add(New AVPLib.DBGroup(2, "Operator"))

        actual = AVPLib.UserSetupLib.GetListGroup(UserDoc)

        Assert.AreEqual(CType(expected.Item(0), DBGroup).Id, CType(actual.Item(0), DBGroup).Id, "AVPLib.UserSetupLib.GetListGroup did not return the expected value.")
        Assert.AreEqual(CType(expected.Item(0), DBGroup).Name.ToString(), CType(actual.Item(0), DBGroup).Name.ToString(), "AVPLib.UserSetupLib.GetListGroup did not return the expected value.")
        Assert.AreEqual(CType(expected.Item(1), DBGroup).Id, CType(actual.Item(1), DBGroup).Id, "AVPLib.UserSetupLib.GetListGroup did not return the expected value.")
        Assert.AreEqual(CType(expected.Item(1), DBGroup).Name.ToString(), CType(actual.Item(1), DBGroup).Name.ToString(), "AVPLib.UserSetupLib.GetListGroup did not return the expected value.")

    End Sub
    <TestMethod()> _
   Public Sub GetListGroupTest_SpecialCase()
        UserDoc.Load("..\..\..\AVPLibTest\bin\TestData\UserSetupLibTest_GetListGroupFunction_SpecialCase\Group2.xml")

        Dim expected As New ArrayList
        Dim actual As ArrayList
        expected.Add(New AVPLib.DBGroup(1, "Administrator"))
        expected.Add(New AVPLib.DBGroup(2, "Operator"))
        expected.Add(New AVPLib.DBGroup(3, "Guess"))

        actual = AVPLib.UserSetupLib.GetListGroup(UserDoc)

        Assert.AreEqual(CType(expected.Item(3), DBGroup).Id, CType(actual.Item(3), DBGroup).Id, "AVPLib.UserSetupLib.GetListGroup did not return the expected value.")
        Assert.AreEqual(CType(expected.Item(3), DBGroup).Name.ToString(), CType(actual.Item(3), DBGroup).Name.ToString(), "AVPLib.UserSetupLib.GetListGroup did not return the expected value.")
        Assert.AreEqual(CType(expected.Item(1), DBGroup).Id, CType(actual.Item(1), DBGroup).Id, "AVPLib.UserSetupLib.GetListGroup did not return the expected value.")
        Assert.AreEqual(CType(expected.Item(1), DBGroup).Name.ToString(), CType(actual.Item(1), DBGroup).Name.ToString(), "AVPLib.UserSetupLib.GetListGroup did not return the expected value.")

    End Sub
End Class
