'The following code was generated by Microsoft Visual Studio 2005.
'The test owner should check each test for validity.
Imports Microsoft.VisualStudio.TestTools.UnitTesting
Imports System
Imports System.Text
Imports System.Collections.Generic
Imports System.Xml
Imports System.Collections






'''<summary>
'''This is a test class for AVPLib.ValueMessageEquipmentLib and is intended
'''to contain all AVPLib.ValueMessageEquipmentLib Unit Tests
'''</summary>
<Assembly: System.Resources.NeutralResourcesLanguageAttribute("en-US")> 
<TestClass()> _
Public Class ValueMessageEquipmentLibTest

    Private Shared UserDoc As XmlDocument = Nothing 'TODO: Initialize to an appropriate value
    Private testContextInstance As TestContext

    '''<summary>
    '''Gets or sets the test context which provides
    '''information about and functionality for the current test run.
    '''</summary>
    Public Property TestContext() As TestContext
        Get
            Return testContextInstance
        End Get
        Set(ByVal value As TestContext)
            testContextInstance = value
        End Set
    End Property
#Region "Additional test attributes"
    '
    'You can use the following additional attributes as you write your tests:
    '
    'Use ClassInitialize to run code before running the first test in the class
    '
    <ClassInitialize()> _
    Public Shared Sub MyClassInitialize(ByVal testContext As TestContext)
        AVPLib.Log.initialize()
        UserDoc = New XmlDocument()
        UserDoc.Load("..\..\..\AVPLibTest\bin\TestData\ValueMessageEquipmentLibTest_NormalCase\ParseMessageName.xml")

    End Sub
    '
    'Use ClassCleanup to run code after all tests in a class have run
    '
    '<ClassCleanup()>  _
    'Public Shared Sub MyClassCleanup()
    'End Sub
    '
    'Use TestInitialize to run code before running each test
    '
    '<TestInitialize()>  _
    'Public Sub MyTestInitialize()
    'End Sub
    '
    'Use TestCleanup to run code after each test has run
    '
    '<TestCleanup()>  _
    'Public Sub MyTestCleanup()
    'End Sub
    '
#End Region


    '''<summary>
    '''A test for GetMessageConfig(ByVal System.Xml.XmlDocument)
    '''</summary>
    <TestMethod()> _
    Public Sub GetMessageConfigTest_NormalCase()
        Dim expected As New Hashtable
        Dim actual As Hashtable

        actual = AVPLib.ValueMessageEquipmentLib.GetMessageConfig(UserDoc)
        'name - code
        expected.Add("Alarm.OrangeStatus", "FlashOrangeLight")
        expected.Add("IBEMaintainance.BeamPowerSupply_VoltageRight", "BeamPowerSupply_VoltageRight")
        expected.Add("IBEMaintainance.FinishProcessing", "ProcessRecipe_FinishProcessing")

        Assert.AreEqual(expected.Item("Alarm.OrangeStatus").ToString(), actual.Item("Alarm.OrangeStatus").ToString(), "AVPLib.ValueMessageEquipmentLib.GetMessageConfig did not return the expected value.")
        Assert.AreEqual(expected.Item("IBEMaintainance.BeamPowerSupply_VoltageRight").ToString(), actual.Item("IBEMaintainance.BeamPowerSupply_VoltageRight").ToString(), "AVPLib.ValueMessageEquipmentLib.GetMessageConfig did not return the expected value.")
        Assert.AreEqual(expected.Item("IBEMaintainance.FinishProcessing").ToString(), actual.Item("IBEMaintainance.FinishProcessing").ToString(), "AVPLib.ValueMessageEquipmentLib.GetMessageConfig did not return the expected value.")

    End Sub
    '''<summary>
    '''A test for GetMessageConfig(ByVal System.Xml.XmlDocument)
    '''</summary>
    <TestMethod()> _
    Public Sub GetMessageConfigTest_SpecialCase()
        Dim expected As New Hashtable
        Dim actual As Hashtable

        actual = AVPLib.ValueMessageEquipmentLib.GetMessageConfig(UserDoc)
        'name - code
        expected.Add("Chamber5.WaferID", "SetIGOfChamber1InProcessScreenTo,SetIGOfChamber1InCassettesScreenTo,SetIGOfChamber1InTransferScreenTo")
        expected.Add("Chamber5.ProcessTime", "SetProcessTimeOfChamber5InProcessScreenTo")
        ' expected.Add("IBEMaintainance.FinishProcessing", "ProcessRecipe_FinishProcessing")

        Assert.AreEqual("SetProcessTimeOfChamber5InProcessScreenTo", actual.Item("Chamber5.ProcessTime").ToString(), "AVPLib.ValueMessageEquipmentLib.GetMessageConfig did not return the expected value.")
        Assert.AreEqual("SetIGOfChamber1InProcessScreenTo, SetIGOfChamber1InCassettesScreenTo, SetIGOfChamber1InTransferScreenTo", actual.Item("Chamber5.WaferID").ToString(), "AVPLib.ValueMessageEquipmentLib.GetMessageConfig did not return the expected value.")

        ' Assert.AreEqual(expected.Item("IBEMaintainance.FinishProcessing"), actual.Item("IBEMaintainance.FinishProcessing"), "AVPLib.ValueMessageEquipmentLib.GetMessageConfig did not return the expected value.")

    End Sub
End Class
