'The following code was generated by Microsoft Visual Studio 2005.
'The test owner should check each test for validity.
Imports Microsoft.VisualStudio.TestTools.UnitTesting
Imports System
Imports System.Text
Imports System.Collections.Generic
Imports System.Xml

<TestClass()> _
Public Class VentPumdownLibUT

    Private testContextInstance As TestContext

    Public Property TestContext() As TestContext
        Get
            Return testContextInstance
        End Get
        Set(ByVal value As TestContext)
            testContextInstance = Value
        End Set
    End Property
#Region "Additional test attributes"
    '
    'You can use the following additional attributes as you write your tests:
    '
    'Use ClassInitialize to run code before running the first test in the class
    '
    '<ClassInitialize()>  _
    'Public Shared Sub MyClassInitialize(ByVal testContext As TestContext)
    'End Sub
    '
    'Use ClassCleanup to run code after all tests in a class have run
    '
    '<ClassCleanup()>  _
    'Public Shared Sub MyClassCleanup()
    'End Sub
    '
    'Use TestInitialize to run code before running each test
    '
    '<TestInitialize()>  _
    'Public Sub MyTestInitialize()
    'End Sub
    '
    'Use TestCleanup to run code after each test has run
    '
    '<TestCleanup()>  _
    'Public Sub MyTestCleanup()
    'End Sub
    '
#End Region

    Private Shared VentPumpdownConfigDoc As XmlDocument
    'Private Shared LLVentConfigNode As XmlNode
    'Private Shared LLPumpdownConfigNode As XmlNode
    'Private Shared TMVentConfigNode As XmlNode
    'Private Shared TMPumpdownConfigNode As XmlNode

    <ClassInitialize()> _
    Public Shared Sub VentPumdownLibInitialize(ByVal testContext As TestContext)
        '
        AVPLib.Log.initialize()
        'Create an XmlWriterSettings instance.
        Dim oSettings As XmlWriterSettings = New XmlWriterSettings()
        oSettings.Indent = True
        oSettings.OmitXmlDeclaration = True
        oSettings.Encoding = Encoding.ASCII
        Dim xmlFile As String = AppDomain.CurrentDomain.SetupInformation.ApplicationBase + "\ConfigurableVentPumpdown.xml"
        Dim writer As XmlWriter = XmlWriter.Create(xmlFile, oSettings)
        writer.WriteStartDocument(True)
        'VentPumpdownConfig
        writer.WriteStartElement("VentPumpdownConfig")

        '<LLVentConfig>
        writer.WriteStartElement(AVPLib.VentPumdownLib.EnumVentPumdownConfig.LLVentConfig.ToString())
        'IGOnOffWaitTime
        writer.WriteStartElement("Item")
        writer.WriteStartAttribute("Name")
        writer.WriteValue(AVPLib.VentPumdownLib.EnumLLVentConfig.IGOnOffWaitTime.ToString())
        writer.WriteEndAttribute()
        writer.WriteStartAttribute("Value")
        writer.WriteValue("2000")
        writer.WriteEndAttribute()
        writer.WriteEndElement()
        '
        'LLCGOnFastVentValveOpen
        writer.WriteStartElement("Item")
        writer.WriteStartAttribute("Name")
        writer.WriteValue(AVPLib.VentPumdownLib.EnumLLVentConfig.LLCGOnFastVentValveOpen.ToString())
        writer.WriteEndAttribute()
        writer.WriteStartAttribute("Value")
        writer.WriteValue("760")
        writer.WriteEndAttribute()
        writer.WriteEndElement()
        '
        'LLCGOnFastVentValveOpenWaitTime
        writer.WriteStartElement("Item")
        writer.WriteStartAttribute("Name")
        writer.WriteValue(AVPLib.VentPumdownLib.EnumLLVentConfig.LLCGOnFastVentValveOpenWaitTime.ToString())
        writer.WriteEndAttribute()
        writer.WriteStartAttribute("Value")
        writer.WriteValue("300000")
        writer.WriteEndAttribute()
        writer.WriteEndElement()
        '
        'LLCGOnSlowVentValveOpen
        writer.WriteStartElement("Item")
        writer.WriteStartAttribute("Name")
        writer.WriteValue(AVPLib.VentPumdownLib.EnumLLVentConfig.LLCGOnSlowVentValveOpen.ToString())
        writer.WriteEndAttribute()
        writer.WriteStartAttribute("Value")
        writer.WriteValue("150")
        writer.WriteEndAttribute()
        writer.WriteEndElement()
        '
        'LLCGOnSlowVentValveOpenWaitTime
        writer.WriteStartElement("Item")
        writer.WriteStartAttribute("Name")
        writer.WriteValue(AVPLib.VentPumdownLib.EnumLLVentConfig.LLCGOnSlowVentValveOpenWaitTime.ToString())
        writer.WriteEndAttribute()
        writer.WriteStartAttribute("Value")
        writer.WriteValue("180000")
        writer.WriteEndAttribute()
        writer.WriteEndElement()
        '
        'LLHivacValveOpenCloseWaitTime
        writer.WriteStartElement("Item")
        writer.WriteStartAttribute("Name")
        writer.WriteValue(AVPLib.VentPumdownLib.EnumLLVentConfig.LLHivacValveOpenCloseWaitTime.ToString())
        writer.WriteEndAttribute()
        writer.WriteStartAttribute("Value")
        writer.WriteValue("2000")
        writer.WriteEndAttribute()
        writer.WriteEndElement()
        '
        'LLMesaValveOpenCloseWaitTime
        writer.WriteStartElement("Item")
        writer.WriteStartAttribute("Name")
        writer.WriteValue(AVPLib.VentPumdownLib.EnumLLVentConfig.LLMesaValveOpenCloseWaitTime.ToString())
        writer.WriteEndAttribute()
        writer.WriteStartAttribute("Value")
        writer.WriteValue("2000")
        writer.WriteEndAttribute()
        writer.WriteEndElement()
        '
        writer.WriteEndElement()
        ' </LLVentConfig>

        '<LLPumpdownConfig>
        writer.WriteStartElement(AVPLib.VentPumdownLib.EnumVentPumdownConfig.LLPumpdownConfig.ToString())
        'IGOffWaitTime
        writer.WriteStartElement("Item")
        writer.WriteStartAttribute("Name")
        writer.WriteValue(AVPLib.VentPumdownLib.EnumLLPumpdownConfig.IGOffWaitTime.ToString())
        writer.WriteEndAttribute()
        writer.WriteStartAttribute("Value")
        writer.WriteValue("2000")
        writer.WriteEndAttribute()
        writer.WriteEndElement()
        'IGOnWaitTime
        writer.WriteStartElement("Item")
        writer.WriteStartAttribute("Name")
        writer.WriteValue(AVPLib.VentPumdownLib.EnumLLPumpdownConfig.IGOnWaitTime.ToString())
        writer.WriteEndAttribute()
        writer.WriteStartAttribute("Value")
        writer.WriteValue("2000")
        writer.WriteEndAttribute()
        writer.WriteEndElement()
        'LLCGOnFastRoughValveOpen
        writer.WriteStartElement("Item")
        writer.WriteStartAttribute("Name")
        writer.WriteValue(AVPLib.VentPumdownLib.EnumLLPumpdownConfig.LLCGOnFastRoughValveOpen.ToString())
        writer.WriteEndAttribute()
        writer.WriteStartAttribute("Value")
        writer.WriteValue("0.15")
        writer.WriteEndAttribute()
        writer.WriteEndElement()
        'LLCGOnFastRoughValveOpenWaitTime
        writer.WriteStartElement("Item")
        writer.WriteStartAttribute("Name")
        writer.WriteValue(AVPLib.VentPumdownLib.EnumLLPumpdownConfig.LLCGOnFastRoughValveOpenWaitTime.ToString())
        writer.WriteEndAttribute()
        writer.WriteStartAttribute("Value")
        writer.WriteValue("300000")
        writer.WriteEndAttribute()
        writer.WriteEndElement()
        'LLCGOnSlowRoughValveOpen
        writer.WriteStartElement("Item")
        writer.WriteStartAttribute("Name")
        writer.WriteValue(AVPLib.VentPumdownLib.EnumLLPumpdownConfig.LLCGOnSlowRoughValveOpen.ToString())
        writer.WriteEndAttribute()
        writer.WriteStartAttribute("Value")
        writer.WriteValue("350")
        writer.WriteEndAttribute()
        writer.WriteEndElement()
        'LLCGOnSlowRoughValveOpenWaitTime
        writer.WriteStartElement("Item")
        writer.WriteStartAttribute("Name")
        writer.WriteValue(AVPLib.VentPumdownLib.EnumLLPumpdownConfig.LLCGOnSlowRoughValveOpenWaitTime.ToString())
        writer.WriteEndAttribute()
        writer.WriteStartAttribute("Value")
        writer.WriteValue("120000")
        writer.WriteEndAttribute()
        writer.WriteEndElement()
        'LLHivacValveOpenCloseWaitTime
        writer.WriteStartElement("Item")
        writer.WriteStartAttribute("Name")
        writer.WriteValue(AVPLib.VentPumdownLib.EnumLLPumpdownConfig.LLHivacValveOpenCloseWaitTime.ToString())
        writer.WriteEndAttribute()
        writer.WriteStartAttribute("Value")
        writer.WriteValue("2000")
        writer.WriteEndAttribute()
        writer.WriteEndElement()
        'LLMesaValveOpenCloseWaitTime
        writer.WriteStartElement("Item")
        writer.WriteStartAttribute("Name")
        writer.WriteValue(AVPLib.VentPumdownLib.EnumLLPumpdownConfig.LLMesaValveOpenCloseWaitTime.ToString())
        writer.WriteEndAttribute()
        writer.WriteStartAttribute("Value")
        writer.WriteValue("2000")
        writer.WriteEndAttribute()
        writer.WriteEndElement()
        'LLSlowRoughValveOpenCloseWaitTime
        writer.WriteStartElement("Item")
        writer.WriteStartAttribute("Name")
        writer.WriteValue(AVPLib.VentPumdownLib.EnumLLPumpdownConfig.LLSlowRoughValveOpenCloseWaitTime.ToString())
        writer.WriteEndAttribute()
        writer.WriteStartAttribute("Value")
        writer.WriteValue("10000")
        writer.WriteEndAttribute()
        writer.WriteEndElement()
        'TMMechanicalPumpCGOnCloseAllSlowFastValves
        writer.WriteStartElement("Item")
        writer.WriteStartAttribute("Name")
        writer.WriteValue(AVPLib.VentPumdownLib.EnumLLPumpdownConfig.TMMechanicalPumpCGOnCloseAllSlowFastValves.ToString())
        writer.WriteEndAttribute()
        writer.WriteStartAttribute("Value")
        writer.WriteValue("0.1")
        writer.WriteEndAttribute()
        writer.WriteEndElement()
        'TMMechanicalPumpCGOnCloseSlowRoughValve
        writer.WriteStartElement("Item")
        writer.WriteStartAttribute("Name")
        writer.WriteValue(AVPLib.VentPumdownLib.EnumLLPumpdownConfig.TMMechanicalPumpCGOnCloseSlowRoughValve.ToString())
        writer.WriteEndAttribute()
        writer.WriteStartAttribute("Value")
        writer.WriteValue("0.1")
        writer.WriteEndAttribute()
        writer.WriteEndElement()
        'TMPressureOnFastRoughValveClose
        writer.WriteStartElement("Item")
        writer.WriteStartAttribute("Name")
        writer.WriteValue(AVPLib.VentPumdownLib.EnumLLPumpdownConfig.TMPressureOnFastRoughValveClose.ToString())
        writer.WriteEndAttribute()
        writer.WriteStartAttribute("Value")
        writer.WriteValue("15000")
        writer.WriteEndAttribute()
        writer.WriteEndElement()
        'WaitTimeAfterOpeningLLHivacValve
        writer.WriteStartElement("Item")
        writer.WriteStartAttribute("Name")
        writer.WriteValue(AVPLib.VentPumdownLib.EnumLLPumpdownConfig.WaitTimeAfterOpeningLLHivacValve.ToString())
        writer.WriteEndAttribute()
        writer.WriteStartAttribute("Value")
        writer.WriteValue("10000")
        writer.WriteEndAttribute()
        writer.WriteEndElement()
        '
        writer.WriteEndElement()
        ' </LLPumpdownConfig>

        ' <TMVentConfig>
        writer.WriteStartElement(AVPLib.VentPumdownLib.EnumVentPumdownConfig.TMVentConfig.ToString())
        'IGOnOffWaitTime
        writer.WriteStartElement("Item")
        writer.WriteStartAttribute("Name")
        writer.WriteValue(AVPLib.VentPumdownLib.EnumTMVentConfig.IGOnOffWaitTime.ToString())
        writer.WriteEndAttribute()
        writer.WriteStartAttribute("Value")
        writer.WriteValue("2000")
        writer.WriteEndAttribute()
        writer.WriteEndElement()
        'TMCGOnLLFastVentValvesOpen
        writer.WriteStartElement("Item")
        writer.WriteStartAttribute("Name")
        writer.WriteValue(AVPLib.VentPumdownLib.EnumTMVentConfig.TMCGOnLLFastVentValvesOpen.ToString())
        writer.WriteEndAttribute()
        writer.WriteStartAttribute("Value")
        writer.WriteValue("760")
        writer.WriteEndAttribute()
        writer.WriteEndElement()
        'TMCGOnLLFastVentValvesOpenWaitTime
        writer.WriteStartElement("Item")
        writer.WriteStartAttribute("Name")
        writer.WriteValue(AVPLib.VentPumdownLib.EnumTMVentConfig.TMCGOnLLFastVentValvesOpenWaitTime.ToString())
        writer.WriteEndAttribute()
        writer.WriteStartAttribute("Value")
        writer.WriteValue("300000")
        writer.WriteEndAttribute()
        writer.WriteEndElement()
        'TMHivacValveOpenCloseWaitTime
        writer.WriteStartElement("Item")
        writer.WriteStartAttribute("Name")
        writer.WriteValue(AVPLib.VentPumdownLib.EnumTMVentConfig.TMHivacValveOpenCloseWaitTime.ToString())
        writer.WriteEndAttribute()
        writer.WriteStartAttribute("Value")
        writer.WriteValue("2000")
        writer.WriteEndAttribute()
        writer.WriteEndElement()
        'WaitTimeAfterClosingAllMesaValves
        writer.WriteStartElement("Item")
        writer.WriteStartAttribute("Name")
        writer.WriteValue(AVPLib.VentPumdownLib.EnumTMVentConfig.WaitTimeAfterClosingAllMesaValves.ToString())
        writer.WriteEndAttribute()
        writer.WriteStartAttribute("Value")
        writer.WriteValue("5000")
        writer.WriteEndAttribute()
        writer.WriteEndElement()
        '
        writer.WriteEndElement()
        ' </TMVentConfig>

        ' <TMPumpdownConfig>
        writer.WriteStartElement(AVPLib.VentPumdownLib.EnumVentPumdownConfig.TMPumpdownConfig.ToString())
        'IGOffWaitTime
        writer.WriteStartElement("Item")
        writer.WriteStartAttribute("Name")
        writer.WriteValue(AVPLib.VentPumdownLib.EnumTMPumpdownConfig.IGOffWaitTime.ToString())
        writer.WriteEndAttribute()
        writer.WriteStartAttribute("Value")
        writer.WriteValue("2000")
        writer.WriteEndAttribute()
        writer.WriteEndElement()
        'IGOnWaitTime
        writer.WriteStartElement("Item")
        writer.WriteStartAttribute("Name")
        writer.WriteValue(AVPLib.VentPumdownLib.EnumTMPumpdownConfig.IGOnWaitTime.ToString())
        writer.WriteEndAttribute()
        writer.WriteStartAttribute("Value")
        writer.WriteValue("2000")
        writer.WriteEndAttribute()
        writer.WriteEndElement()
        'TMCGOnFastRoughValveOpen
        writer.WriteStartElement("Item")
        writer.WriteStartAttribute("Name")
        writer.WriteValue(AVPLib.VentPumdownLib.EnumTMPumpdownConfig.TMCGOnFastRoughValveOpen.ToString())
        writer.WriteEndAttribute()
        writer.WriteStartAttribute("Value")
        writer.WriteValue("0.15")
        writer.WriteEndAttribute()
        writer.WriteEndElement()
        'TMCGOnFastRoughValveOpenWaitTime
        writer.WriteStartElement("Item")
        writer.WriteStartAttribute("Name")
        writer.WriteValue(AVPLib.VentPumdownLib.EnumTMPumpdownConfig.TMCGOnFastRoughValveOpenWaitTime.ToString())
        writer.WriteEndAttribute()
        writer.WriteStartAttribute("Value")
        writer.WriteValue("300000")
        writer.WriteEndAttribute()
        writer.WriteEndElement()
        'TMHivacValveOpenCloseWaitTime
        writer.WriteStartElement("Item")
        writer.WriteStartAttribute("Name")
        writer.WriteValue(AVPLib.VentPumdownLib.EnumTMPumpdownConfig.TMHivacValveOpenCloseWaitTime.ToString())
        writer.WriteEndAttribute()
        writer.WriteStartAttribute("Value")
        writer.WriteValue("2000")
        writer.WriteEndAttribute()
        writer.WriteEndElement()
        'TMMechanicalPumpCGOnCloseVentRoughValves
        writer.WriteStartElement("Item")
        writer.WriteStartAttribute("Name")
        writer.WriteValue(AVPLib.VentPumdownLib.EnumTMPumpdownConfig.TMMechanicalPumpCGOnCloseVentRoughValves.ToString())
        writer.WriteEndAttribute()
        writer.WriteStartAttribute("Value")
        writer.WriteValue("0.1")
        writer.WriteEndAttribute()
        writer.WriteEndElement()
        'TMPressureOnFastRoughValveClose
        writer.WriteStartElement("Item")
        writer.WriteStartAttribute("Name")
        writer.WriteValue(AVPLib.VentPumdownLib.EnumTMPumpdownConfig.TMPressureOnFastRoughValveClose.ToString())
        writer.WriteEndAttribute()
        writer.WriteStartAttribute("Value")
        writer.WriteValue("15000")
        writer.WriteEndAttribute()
        writer.WriteEndElement()
        'WaitTimeAfterClosingAllMesaValves
        writer.WriteStartElement("Item")
        writer.WriteStartAttribute("Name")
        writer.WriteValue(AVPLib.VentPumdownLib.EnumTMPumpdownConfig.WaitTimeAfterClosingAllMesaValves.ToString())
        writer.WriteEndAttribute()
        writer.WriteStartAttribute("Value")
        writer.WriteValue("5000")
        writer.WriteEndAttribute()
        writer.WriteEndElement()
        'WaitTimeAfterOpeningTMHivacValve
        writer.WriteStartElement("Item")
        writer.WriteStartAttribute("Name")
        writer.WriteValue(AVPLib.VentPumdownLib.EnumTMPumpdownConfig.WaitTimeAfterOpeningTMHivacValve.ToString())
        writer.WriteEndAttribute()
        writer.WriteStartAttribute("Value")
        writer.WriteValue("10000")
        writer.WriteEndAttribute()
        writer.WriteEndElement()
        '
        writer.WriteEndElement()
        ' </TMPumpdownConfig>

        writer.WriteEndElement()
        writer.WriteEndDocument()
        '
        writer.Flush()
        writer.Close()

        VentPumpdownConfigDoc = New XmlDocument()
        VentPumpdownConfigDoc.Load(xmlFile)
    End Sub

    '<DeploymentItem("AVPLib.dll"), _
    ' TestMethod()> _
    'Public Sub InitLLVentConfig()
    '    Dim llVentConfigNode As XmlNode = Nothing 'TODO: Initialize to an appropriate value

    '    AVPLibTest.AVPLib_VentPumdownLibAccessor.InitLLVentConfig(LLVentConfigNode)

    'End Sub

    <TestMethod()> _
    Public Sub GetConfig()
        Dim ventPumpdownDoc As XmlDocument = VentPumpdownConfigDoc

        AVPLib.VentPumdownLib.GetConfig(ventPumpdownDoc)

        ' LLVentConfig.IGOnOffWaitTime
        Assert.AreEqual(AVPLib.VentPumdownLib.LLVentConfig.IGOnOffWaitTime, 2000)
        ' LLVentConfig.LLCGOnFastVentValveOpen
        Assert.AreEqual(Of Double)(AVPLib.VentPumdownLib.LLVentConfig.LLCGOnFastVentValveOpen, 760)
        ' LLVentConfig.LLCGOnFastVentValveOpenWaitTime
        Assert.AreEqual(AVPLib.VentPumdownLib.LLVentConfig.LLCGOnFastVentValveOpenWaitTime, 300000)
        ' LLVentConfig.LLCGOnSlowVentValveOpen
        Assert.AreEqual(Of Double)(AVPLib.VentPumdownLib.LLVentConfig.LLCGOnSlowVentValveOpen, 150)
        ' LLVentConfig.LLCGOnSlowVentValveOpenWaitTime
        Assert.AreEqual(AVPLib.VentPumdownLib.LLVentConfig.LLCGOnSlowVentValveOpenWaitTime, 180000)
        ' LLVentConfig.LLHivacValveOpenCloseWaitTime
        Assert.AreEqual(AVPLib.VentPumdownLib.LLVentConfig.LLHivacValveOpenCloseWaitTime, 2000)
        ' LLVentConfig.LLMesaValveOpenCloseWaitTime
        Assert.AreEqual(AVPLib.VentPumdownLib.LLVentConfig.LLMesaValveOpenCloseWaitTime, 2000)

        ' LLPumpdownConfig.IGOffWaitTime
        Assert.AreEqual(AVPLib.VentPumdownLib.LLPumpdownConfig.IGOffWaitTime, 2000)
        ' LLPumpdownConfig.IGOnWaitTime
        Assert.AreEqual(AVPLib.VentPumdownLib.LLPumpdownConfig.IGOnWaitTime, 2000)
        ' LLPumpdownConfig.LLCGOnFastRoughValveOpen
        Assert.AreEqual(Of Double)(AVPLib.VentPumdownLib.LLPumpdownConfig.LLCGOnFastRoughValveOpen, 0.15)
        ' LLPumpdownConfig.LLCGOnFastRoughValveOpenWaitTime
        Assert.AreEqual(AVPLib.VentPumdownLib.LLPumpdownConfig.LLCGOnFastRoughValveOpenWaitTime, 300000)
        ' LLPumpdownConfig.LLCGOnSlowRoughValveOpen
        Assert.AreEqual(Of Double)(AVPLib.VentPumdownLib.LLPumpdownConfig.LLCGOnSlowRoughValveOpen, 350)
        ' LLPumpdownConfig.LLCGOnSlowRoughValveOpenWaitTime
        Assert.AreEqual(AVPLib.VentPumdownLib.LLPumpdownConfig.LLCGOnSlowRoughValveOpenWaitTime, 120000)
        ' LLPumpdownConfig.LLHivacValveOpenCloseWaitTime
        Assert.AreEqual(AVPLib.VentPumdownLib.LLPumpdownConfig.LLHivacValveOpenCloseWaitTime, 2000)
        ' LLPumpdownConfig.LLMesaValveOpenCloseWaitTime
        Assert.AreEqual(AVPLib.VentPumdownLib.LLPumpdownConfig.LLMesaValveOpenCloseWaitTime, 2000)
        ' LLPumpdownConfig.LLSlowRoughValveOpenCloseWaitTime
        Assert.AreEqual(AVPLib.VentPumdownLib.LLPumpdownConfig.LLSlowRoughValveOpenCloseWaitTime, 10000)
        ' LLPumpdownConfig.TMMechanicalPumpCGOnCloseAllSlowFastValves
        Assert.AreEqual(Of Double)(AVPLib.VentPumdownLib.LLPumpdownConfig.TMMechanicalPumpCGOnCloseAllSlowFastValves, 0.1)
        ' LLPumpdownConfig.TMMechanicalPumpCGOnCloseSlowRoughValve
        Assert.AreEqual(Of Double)(AVPLib.VentPumdownLib.LLPumpdownConfig.TMMechanicalPumpCGOnCloseSlowRoughValve, 0.1)
        ' LLPumpdownConfig.TMPressureOnFastRoughValveClose
        Assert.AreEqual(Of Double)(AVPLib.VentPumdownLib.LLPumpdownConfig.TMPressureOnFastRoughValveClose, 15000)
        ' LLPumpdownConfig.WaitTimeAfterOpeningLLHivacValve
        Assert.AreEqual(AVPLib.VentPumdownLib.LLPumpdownConfig.WaitTimeAfterOpeningLLHivacValve, 10000)

        ' TMVentConfig.IGOnOffWaitTime
        Assert.AreEqual(AVPLib.VentPumdownLib.TMVentConfig.IGOnOffWaitTime, 2000)
        ' TMVentConfig.TMCGOnLLFastVentValvesOpen
        Assert.AreEqual(Of Double)(AVPLib.VentPumdownLib.TMVentConfig.TMCGOnLLFastVentValvesOpen, 760)
        ' TMVentConfig.TMCGOnLLFastVentValvesOpenWaitTime
        Assert.AreEqual(AVPLib.VentPumdownLib.TMVentConfig.TMCGOnLLFastVentValvesOpenWaitTime, 300000)
        ' TMVentConfig.TMHivacValveOpenCloseWaitTime
        Assert.AreEqual(AVPLib.VentPumdownLib.TMVentConfig.TMHivacValveOpenCloseWaitTime, 2000)
        ' TMVentConfig.WaitTimeAfterClosingAllMesaValves
        Assert.AreEqual(AVPLib.VentPumdownLib.TMVentConfig.WaitTimeAfterClosingAllMesaValves, 5000)

        ' TMPumpdownConfig.IGOffWaitTime
        Assert.AreEqual(AVPLib.VentPumdownLib.TMPumpdownConfig.IGOffWaitTime, 2000)
        ' TMPumpdownConfig.IGOnWaitTime
        Assert.AreEqual(AVPLib.VentPumdownLib.TMPumpdownConfig.IGOnWaitTime, 2000)
        ' TMPumpdownConfig.TMCGOnFastRoughValveOpen
        Assert.AreEqual(Of Double)(AVPLib.VentPumdownLib.TMPumpdownConfig.TMCGOnFastRoughValveOpen, 0.15)
        ' TMPumpdownConfig.TMCGOnFastRoughValveOpenWaitTime
        Assert.AreEqual(AVPLib.VentPumdownLib.TMPumpdownConfig.TMCGOnFastRoughValveOpenWaitTime, 300000)
        ' TMPumpdownConfig.TMHivacValveOpenCloseWaitTime
        Assert.AreEqual(AVPLib.VentPumdownLib.TMPumpdownConfig.TMHivacValveOpenCloseWaitTime, 2000)
        ' TMPumpdownConfig.TMMechanicalPumpCGOnCloseVentRoughValves
        Assert.AreEqual(AVPLib.VentPumdownLib.TMPumpdownConfig.TMMechanicalPumpCGOnCloseVentRoughValves, 0.1)
        ' TMPumpdownConfig.TMPressureOnFastRoughValveClose
        Assert.AreEqual(Of Double)(AVPLib.VentPumdownLib.TMPumpdownConfig.TMPressureOnFastRoughValveClose, 15000)
        ' TMPumpdownConfig.WaitTimeAfterClosingAllMesaValves
        Assert.AreEqual(AVPLib.VentPumdownLib.TMPumpdownConfig.WaitTimeAfterClosingAllMesaValves, 5000)
        ' TMPumpdownConfig.WaitTimeAfterOpeningTMHivacValve
        Assert.AreEqual(AVPLib.VentPumdownLib.TMPumpdownConfig.WaitTimeAfterOpeningTMHivacValve, 10000)

    End Sub
End Class
