Imports Microsoft.VisualStudio.TestTools.UnitTesting

'------------------------------------------------------------------------------
'<autogenerated>
'        This code was generated by Microsoft Visual Studio Team System 2005.
'
'        Changes to this file may cause incorrect behavior and will be lost if
'        the code is regenerated.
'</autogenerated>
'------------------------------------------------------------------------------

<System.Diagnostics.DebuggerStepThrough(), _
 System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")> _
Friend Class BaseAccessor

    Protected m_privateObject As Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject

    Protected Sub New(ByVal target As Object, ByVal type As Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType)
        MyBase.New()
        m_privateObject = New Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject(target, type)
    End Sub

    Protected Sub New(ByVal type As Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType)
        Me.New(Nothing, type)
    End Sub

    Friend Overridable ReadOnly Property Target() As Object
        Get
            Return m_privateObject.Target
        End Get
    End Property

    Public Overrides Function ToString() As String
        Return Me.Target.ToString
    End Function

    Public Overloads Overrides Function Equals(ByVal obj As Object) As Boolean
        If GetType(BaseAccessor).IsInstanceOfType(obj) Then
            obj = CType(obj, BaseAccessor).Target
        End If
        Return Me.Target.Equals(obj)
    End Function

    Public Overrides Function GetHashCode() As Integer
        Return Me.Target.GetHashCode
    End Function
End Class

<System.Diagnostics.DebuggerStepThrough(), _
 System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")> _
Friend Class AVPLib_VentPumdownLibAccessor
    Inherits BaseAccessor

    Protected Shared m_privateType As Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType = New Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType(GetType(Global.AVPLib.VentPumdownLib))

    Friend Sub New(ByVal target As Global.AVPLib.VentPumdownLib)
        MyBase.New(target, m_privateType)
    End Sub

    Friend Property c_Name() As String
        Get
            Dim ret As String = CType(m_privateObject.GetFieldOrProperty("c_Name"), String)
            Return ret
        End Get
        Set(ByVal value As String)
            m_privateObject.SetFieldOrProperty("c_Name", value)
        End Set
    End Property

    Friend Property c_Value() As String
        Get
            Dim ret As String = CType(m_privateObject.GetFieldOrProperty("c_Value"), String)
            Return ret
        End Get
        Set(ByVal value As String)
            m_privateObject.SetFieldOrProperty("c_Value", value)
        End Set
    End Property

    Friend Shared Sub InitLLVentConfig(ByVal llVentConfigNode As Global.System.Xml.XmlNode)
        Dim args() As Object = New Object() {llVentConfigNode}
        m_privateType.InvokeStatic("InitLLVentConfig", New System.Type() {GetType(Global.System.Xml.XmlNode)}, args)
    End Sub

    Friend Shared Sub InitLLPumpdownConfig(ByVal llPumpdownConfigNode As Global.System.Xml.XmlNode)
        Dim args() As Object = New Object() {llPumpdownConfigNode}
        m_privateType.InvokeStatic("InitLLPumpdownConfig", New System.Type() {GetType(Global.System.Xml.XmlNode)}, args)
    End Sub

    Friend Shared Sub InitTMVentConfig(ByVal tmVentConfigNode As Global.System.Xml.XmlNode)
        Dim args() As Object = New Object() {tmVentConfigNode}
        m_privateType.InvokeStatic("InitTMVentConfig", New System.Type() {GetType(Global.System.Xml.XmlNode)}, args)
    End Sub

    Friend Shared Sub InitTMPumpdownConfig(ByVal tmPumpdownConfigNode As Global.System.Xml.XmlNode)
        Dim args() As Object = New Object() {tmPumpdownConfigNode}
        m_privateType.InvokeStatic("InitTMPumpdownConfig", New System.Type() {GetType(Global.System.Xml.XmlNode)}, args)
    End Sub
End Class
<System.Diagnostics.DebuggerStepThrough(), _
 System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")> _
Friend Class AVPLib_DataManagerment_EquipmentManagerAccessor
    Inherits BaseAccessor

    Protected Shared m_privateType As Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType = New Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType(GetType(Global.AVPLib.DataManagerment.EquipmentManager))

    Friend Sub New(ByVal target As Global.AVPLib.DataManagerment.EquipmentManager)
        MyBase.New(target, m_privateType)
    End Sub

    Friend Shared Property m_htbEquipmentList() As Global.System.Collections.Hashtable
        Get
            Dim ret As Global.System.Collections.Hashtable = CType(m_privateType.GetStaticFieldOrProperty("m_htbEquipmentList"), Global.System.Collections.Hashtable)
            Return ret
        End Get
        Set(ByVal value As Global.System.Collections.Hashtable)
            m_privateType.SetStaticFieldOrProperty("m_htbEquipmentList", value)
        End Set
    End Property

    Friend Shared Property m_objLock() As Object
        Get
            Dim ret As Object = CType(m_privateType.GetStaticFieldOrProperty("m_objLock"), Object)
            Return ret
        End Get
        Set(ByVal value As Object)
            m_privateType.SetStaticFieldOrProperty("m_objLock", value)
        End Set
    End Property

    Friend Shared Sub LoadLock_WaferCountIncreased(ByVal sender As Object, ByVal wfc As Global.AVPLib.DataManagerment.WaferCountEventArgs)
        Dim args() As Object = New Object() {sender, wfc}
        m_privateType.InvokeStatic("LoadLock_WaferCountIncreased", New System.Type() {GetType(Object), GetType(Global.AVPLib.DataManagerment.WaferCountEventArgs)}, args)
    End Sub

    Friend Shared Sub RaiseWaferCountToGui(ByVal intSumWaferCount As Integer)
        Dim args() As Object = New Object() {intSumWaferCount}
        m_privateType.InvokeStatic("RaiseWaferCountToGui", New System.Type() {GetType(Integer)}, args)
    End Sub
End Class

<System.Diagnostics.DebuggerStepThrough(), _
 System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")> _
Friend Class AVPLib_DataManagerment_TransferModuleAccessor
    Inherits BaseAccessor

    Protected Shared m_privateType As Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType = New Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType(GetType(Global.AVPLib.DataManagerment.TransferModule))

    Friend Sub New(ByVal target As Global.AVPLib.DataManagerment.TransferModule)
        MyBase.New(target, m_privateType)
    End Sub

    Friend Property m_dblPressure() As Double
        Get
            Dim ret As Double = CType(m_privateObject.GetFieldOrProperty("m_dblPressure"), Double)
            Return ret
        End Get
        Set(ByVal value As Double)
            m_privateObject.SetFieldOrProperty("m_dblPressure", value)
        End Set
    End Property

    Friend Property m_dblIG() As Double
        Get
            Dim ret As Double = CType(m_privateObject.GetFieldOrProperty("m_dblIG"), Double)
            Return ret
        End Get
        Set(ByVal value As Double)
            m_privateObject.SetFieldOrProperty("m_dblIG", value)
        End Set
    End Property

    Friend Property m_dblCG() As Double
        Get
            Dim ret As Double = CType(m_privateObject.GetFieldOrProperty("m_dblCG"), Double)
            Return ret
        End Get
        Set(ByVal value As Double)
            m_privateObject.SetFieldOrProperty("m_dblCG", value)
        End Set
    End Property

    Friend Property m_enmIGStatus() As Global.AVPLib.DataManagerment.Equipment.WorkingStatuses
        Get
            Dim ret As Global.AVPLib.DataManagerment.Equipment.WorkingStatuses = CType(m_privateObject.GetFieldOrProperty("m_enmIGStatus"), Global.AVPLib.DataManagerment.Equipment.WorkingStatuses)
            Return ret
        End Get
        Set(ByVal value As Global.AVPLib.DataManagerment.Equipment.WorkingStatuses)
            m_privateObject.SetFieldOrProperty("m_enmIGStatus", value)
        End Set
    End Property

    Friend Property m_enmFastRoughValveStatus() As Global.AVPLib.DataManagerment.Equipment.WorkingStatuses
        Get
            Dim ret As Global.AVPLib.DataManagerment.Equipment.WorkingStatuses = CType(m_privateObject.GetFieldOrProperty("m_enmFastRoughValveStatus"), Global.AVPLib.DataManagerment.Equipment.WorkingStatuses)
            Return ret
        End Get
        Set(ByVal value As Global.AVPLib.DataManagerment.Equipment.WorkingStatuses)
            m_privateObject.SetFieldOrProperty("m_enmFastRoughValveStatus", value)
        End Set
    End Property

    Friend Property m_enmFastVentValveStatus() As Global.AVPLib.DataManagerment.Equipment.WorkingStatuses
        Get
            Dim ret As Global.AVPLib.DataManagerment.Equipment.WorkingStatuses = CType(m_privateObject.GetFieldOrProperty("m_enmFastVentValveStatus"), Global.AVPLib.DataManagerment.Equipment.WorkingStatuses)
            Return ret
        End Get
        Set(ByVal value As Global.AVPLib.DataManagerment.Equipment.WorkingStatuses)
            m_privateObject.SetFieldOrProperty("m_enmFastVentValveStatus", value)
        End Set
    End Property

    Friend Property m_enmHiVacValveStatus() As Global.AVPLib.DataManagerment.Equipment.WorkingStatuses
        Get
            Dim ret As Global.AVPLib.DataManagerment.Equipment.WorkingStatuses = CType(m_privateObject.GetFieldOrProperty("m_enmHiVacValveStatus"), Global.AVPLib.DataManagerment.Equipment.WorkingStatuses)
            Return ret
        End Get
        Set(ByVal value As Global.AVPLib.DataManagerment.Equipment.WorkingStatuses)
            m_privateObject.SetFieldOrProperty("m_enmHiVacValveStatus", value)
        End Set
    End Property

    Friend Property m_enmControlStatus() As Global.AVPLib.DataManagerment.Equipment.ControlStatuses
        Get
            Dim ret As Global.AVPLib.DataManagerment.Equipment.ControlStatuses = CType(m_privateObject.GetFieldOrProperty("m_enmControlStatus"), Global.AVPLib.DataManagerment.Equipment.ControlStatuses)
            Return ret
        End Get
        Set(ByVal value As Global.AVPLib.DataManagerment.Equipment.ControlStatuses)
            m_privateObject.SetFieldOrProperty("m_enmControlStatus", value)
        End Set
    End Property

    Friend Property m_enmAutoVentStatus() As Global.AVPLib.DataManagerment.Equipment.WorkingStatuses
        Get
            Dim ret As Global.AVPLib.DataManagerment.Equipment.WorkingStatuses = CType(m_privateObject.GetFieldOrProperty("m_enmAutoVentStatus"), Global.AVPLib.DataManagerment.Equipment.WorkingStatuses)
            Return ret
        End Get
        Set(ByVal value As Global.AVPLib.DataManagerment.Equipment.WorkingStatuses)
            m_privateObject.SetFieldOrProperty("m_enmAutoVentStatus", value)
        End Set
    End Property

    Friend Property m_enmPumpDownStatus() As Global.AVPLib.DataManagerment.Equipment.WorkingStatuses
        Get
            Dim ret As Global.AVPLib.DataManagerment.Equipment.WorkingStatuses = CType(m_privateObject.GetFieldOrProperty("m_enmPumpDownStatus"), Global.AVPLib.DataManagerment.Equipment.WorkingStatuses)
            Return ret
        End Get
        Set(ByVal value As Global.AVPLib.DataManagerment.Equipment.WorkingStatuses)
            m_privateObject.SetFieldOrProperty("m_enmPumpDownStatus", value)
        End Set
    End Property

    Friend Sub UpdatePressure()
        Dim args(-1) As Object
        m_privateObject.Invoke("UpdatePressure", New System.Type(-1) {}, args)
    End Sub
End Class















<System.Diagnostics.DebuggerStepThrough(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")>  _
Friend Class AVPLib_ChamberLibAccessor
    Inherits BaseAccessor
    
    Protected Shared m_privateType As Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType = New Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType(GetType(Global.AVPLib.ChamberLib))
    
    Friend Sub New(ByVal target As Global.AVPLib.ChamberLib)
        MyBase.New(target, m_privateType)
    End Sub
    
    Friend Shared Function GetListChamberName(ByVal Chamber As String) As Global.System.Collections.ArrayList
        Dim args() As Object = New Object() {Chamber}
        Dim ret As Global.System.Collections.ArrayList = CType(m_privateType.InvokeStatic("GetListChamberName", New System.Type() {GetType(String)}, args),Global.System.Collections.ArrayList)
        Return ret
    End Function
    
    Friend Shared Function GetListChamberDoc(ByVal Chamber As String) As Global.System.Collections.ArrayList
        Dim args() As Object = New Object() {Chamber}
        Dim ret As Global.System.Collections.ArrayList = CType(m_privateType.InvokeStatic("GetListChamberDoc", New System.Type() {GetType(String)}, args),Global.System.Collections.ArrayList)
        Return ret
    End Function
    
    Friend Shared Function GetListGroupParameters(ByVal ChamberParameterDoc As Global.System.Xml.XmlDocument) As Global.System.Collections.ArrayList
        Dim args() As Object = New Object() {ChamberParameterDoc}
        Dim ret As Global.System.Collections.ArrayList = CType(m_privateType.InvokeStatic("GetListGroupParameters", New System.Type() {GetType(Global.System.Xml.XmlDocument)}, args),Global.System.Collections.ArrayList)
        Return ret
    End Function
    
    Friend Shared Function GetListGroupParameterValues(ByVal ChamberParameterValueDoc As Global.System.Xml.XmlDocument) As Global.System.Collections.ArrayList
        Dim args() As Object = New Object() {ChamberParameterValueDoc}
        Dim ret As Global.System.Collections.ArrayList = CType(m_privateType.InvokeStatic("GetListGroupParameterValues", New System.Type() {GetType(Global.System.Xml.XmlDocument)}, args),Global.System.Collections.ArrayList)
        Return ret
    End Function
    
    Friend Shared Function GetChamberDescription(ByVal ChamberParameterValueDoc As Global.System.Xml.XmlDocument) As String
        Dim args() As Object = New Object() {ChamberParameterValueDoc}
        Dim ret As String = CType(m_privateType.InvokeStatic("GetChamberDescription", New System.Type() {GetType(Global.System.Xml.XmlDocument)}, args),String)
        Return ret
    End Function
    
    Friend Shared Function CreateChamberStep(ByVal ChamberDoc As Global.System.Xml.XmlDocument, ByVal ChamberStep As Global.AVPLib.DBChamberStep) As Global.System.Xml.XmlNode
        Dim args() As Object = New Object() {ChamberDoc, ChamberStep}
        Dim ret As Global.System.Xml.XmlNode = CType(m_privateType.InvokeStatic("CreateChamberStep", New System.Type() {GetType(Global.System.Xml.XmlDocument), GetType(Global.AVPLib.DBChamberStep)}, args),Global.System.Xml.XmlNode)
        Return ret
    End Function
    
    Friend Shared Function CreateGroupParameterValue(ByVal ChamberDoc As Global.System.Xml.XmlDocument, ByVal GroupParameterValue As Global.AVPLib.DBGroupParameterValue) As Global.System.Xml.XmlNode
        Dim args() As Object = New Object() {ChamberDoc, GroupParameterValue}
        Dim ret As Global.System.Xml.XmlNode = CType(m_privateType.InvokeStatic("CreateGroupParameterValue", New System.Type() {GetType(Global.System.Xml.XmlDocument), GetType(Global.AVPLib.DBGroupParameterValue)}, args),Global.System.Xml.XmlNode)
        Return ret
    End Function
End Class

<System.Diagnostics.DebuggerStepThrough(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")>  _
Friend Class AVPLib_ContainerDataAccessor
    Inherits BaseAccessor
    
    Protected Shared m_privateType As Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType = New Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType(GetType(Global.AVPLib.ContainerData))
    
    Friend Sub New(ByVal target As Global.AVPLib.ContainerData)
        MyBase.New(target, m_privateType)
    End Sub
    
    Friend Shared Property TypeUser() As String
        Get
            Dim ret As String = CType(m_privateType.GetStaticFieldOrProperty("TypeUser"),String)
            Return ret
        End Get
        Set
            m_privateType.SetStaticFieldOrProperty("TypeUser", value)
        End Set
    End Property
    
    Friend Shared Property TypeAlarm() As String
        Get
            Dim ret As String = CType(m_privateType.GetStaticFieldOrProperty("TypeAlarm"),String)
            Return ret
        End Get
        Set
            m_privateType.SetStaticFieldOrProperty("TypeAlarm", value)
        End Set
    End Property
    
    Friend Shared Property TypeEvent() As String
        Get
            Dim ret As String = CType(m_privateType.GetStaticFieldOrProperty("TypeEvent"),String)
            Return ret
        End Get
        Set
            m_privateType.SetStaticFieldOrProperty("TypeEvent", value)
        End Set
    End Property
    
    Friend Shared Property m_UserLogin() As Global.AVPLib.DBUser
        Get
            Dim ret As Global.AVPLib.DBUser = CType(m_privateType.GetStaticFieldOrProperty("m_UserLogin"),Global.AVPLib.DBUser)
            Return ret
        End Get
        Set
            m_privateType.SetStaticFieldOrProperty("m_UserLogin", value)
        End Set
    End Property
    
    Friend Shared Property m_UserMap() As Global.System.Collections.Hashtable
        Get
            Dim ret As Global.System.Collections.Hashtable = CType(m_privateType.GetStaticFieldOrProperty("m_UserMap"),Global.System.Collections.Hashtable)
            Return ret
        End Get
        Set
            m_privateType.SetStaticFieldOrProperty("m_UserMap", value)
        End Set
    End Property
    
    Friend Shared Property m_ListUser() As Global.System.Collections.ArrayList
        Get
            Dim ret As Global.System.Collections.ArrayList = CType(m_privateType.GetStaticFieldOrProperty("m_ListUser"),Global.System.Collections.ArrayList)
            Return ret
        End Get
        Set
            m_privateType.SetStaticFieldOrProperty("m_ListUser", value)
        End Set
    End Property
    
    Friend Shared Property m_ListGroup() As Global.System.Collections.ArrayList
        Get
            Dim ret As Global.System.Collections.ArrayList = CType(m_privateType.GetStaticFieldOrProperty("m_ListGroup"),Global.System.Collections.ArrayList)
            Return ret
        End Get
        Set
            m_privateType.SetStaticFieldOrProperty("m_ListGroup", value)
        End Set
    End Property
    
    Friend Shared Property m_ChamberMap() As Global.System.Collections.Hashtable
        Get
            Dim ret As Global.System.Collections.Hashtable = CType(m_privateType.GetStaticFieldOrProperty("m_ChamberMap"),Global.System.Collections.Hashtable)
            Return ret
        End Get
        Set
            m_privateType.SetStaticFieldOrProperty("m_ChamberMap", value)
        End Set
    End Property
    
    Friend Shared Property m_ListRecipe() As Global.System.Collections.ArrayList
        Get
            Dim ret As Global.System.Collections.ArrayList = CType(m_privateType.GetStaticFieldOrProperty("m_ListRecipe"),Global.System.Collections.ArrayList)
            Return ret
        End Get
        Set
            m_privateType.SetStaticFieldOrProperty("m_ListRecipe", value)
        End Set
    End Property
    
    
    Friend Shared Property m_ListSequenceName() As Global.System.Collections.ArrayList
        Get
            Dim ret As Global.System.Collections.ArrayList = CType(m_privateType.GetStaticFieldOrProperty("m_ListSequenceName"),Global.System.Collections.ArrayList)
            Return ret
        End Get
        Set
            m_privateType.SetStaticFieldOrProperty("m_ListSequenceName", value)
        End Set
    End Property
    
    Friend Shared Property m_DataTable_Log() As Global.System.Data.DataTable
        Get
            Dim ret As Global.System.Data.DataTable = CType(m_privateType.GetStaticFieldOrProperty("m_DataTable_Log"),Global.System.Data.DataTable)
            Return ret
        End Get
        Set
            m_privateType.SetStaticFieldOrProperty("m_DataTable_Log", value)
        End Set
    End Property
    
    Friend Shared Property m_ComboItemMap() As Global.System.Collections.Hashtable
        Get
            Dim ret As Global.System.Collections.Hashtable = CType(m_privateType.GetStaticFieldOrProperty("m_ComboItemMap"),Global.System.Collections.Hashtable)
            Return ret
        End Get
        Set
            m_privateType.SetStaticFieldOrProperty("m_ComboItemMap", value)
        End Set
    End Property
    
    Friend Shared Property m_MessageGuiBusinessMap() As Global.System.Collections.Hashtable
        Get
            Dim ret As Global.System.Collections.Hashtable = CType(m_privateType.GetStaticFieldOrProperty("m_MessageGuiBusinessMap"),Global.System.Collections.Hashtable)
            Return ret
        End Get
        Set
            m_privateType.SetStaticFieldOrProperty("m_MessageGuiBusinessMap", value)
        End Set
    End Property
    
    Friend Shared Property m_MessageConfig() As Global.System.Collections.Hashtable
        Get
            Dim ret As Global.System.Collections.Hashtable = CType(m_privateType.GetStaticFieldOrProperty("m_MessageConfig"),Global.System.Collections.Hashtable)
            Return ret
        End Get
        Set
            m_privateType.SetStaticFieldOrProperty("m_MessageConfig", value)
        End Set
    End Property
    
    Friend Shared Property m_ValueMessageConfig() As Global.System.Collections.Hashtable
        Get
            Dim ret As Global.System.Collections.Hashtable = CType(m_privateType.GetStaticFieldOrProperty("m_ValueMessageConfig"),Global.System.Collections.Hashtable)
            Return ret
        End Get
        Set
            m_privateType.SetStaticFieldOrProperty("m_ValueMessageConfig", value)
        End Set
    End Property
    
    Friend Shared Property m_ErrorMessageConfig() As Global.System.Collections.Hashtable
        Get
            Dim ret As Global.System.Collections.Hashtable = CType(m_privateType.GetStaticFieldOrProperty("m_ErrorMessageConfig"),Global.System.Collections.Hashtable)
            Return ret
        End Get
        Set
            m_privateType.SetStaticFieldOrProperty("m_ErrorMessageConfig", value)
        End Set
    End Property
    
    Friend Shared Property m_PollingConfig() As Global.System.Collections.Hashtable
        Get
            Dim ret As Global.System.Collections.Hashtable = CType(m_privateType.GetStaticFieldOrProperty("m_PollingConfig"),Global.System.Collections.Hashtable)
            Return ret
        End Get
        Set
            m_privateType.SetStaticFieldOrProperty("m_PollingConfig", value)
        End Set
    End Property
    
    Friend Shared Property m_TimeoutConfig() As Global.System.Collections.Hashtable
        Get
            Dim ret As Global.System.Collections.Hashtable = CType(m_privateType.GetStaticFieldOrProperty("m_TimeoutConfig"),Global.System.Collections.Hashtable)
            Return ret
        End Get
        Set
            m_privateType.SetStaticFieldOrProperty("m_TimeoutConfig", value)
        End Set
    End Property
    
    Friend Shared Property m_IBEMaintenanceMap() As Global.System.Collections.Hashtable
        Get
            Dim ret As Global.System.Collections.Hashtable = CType(m_privateType.GetStaticFieldOrProperty("m_IBEMaintenanceMap"),Global.System.Collections.Hashtable)
            Return ret
        End Get
        Set
            m_privateType.SetStaticFieldOrProperty("m_IBEMaintenanceMap", value)
        End Set
    End Property
    
    Friend Shared Property m_InitConfig() As Global.System.Collections.Hashtable
        Get
            Dim ret As Global.System.Collections.Hashtable = CType(m_privateType.GetStaticFieldOrProperty("m_InitConfig"),Global.System.Collections.Hashtable)
            Return ret
        End Get
        Set
            m_privateType.SetStaticFieldOrProperty("m_InitConfig", value)
        End Set
    End Property
    
    Friend Shared Property m_PathMap() As Global.System.Collections.Hashtable
        Get
            Dim ret As Global.System.Collections.Hashtable = CType(m_privateType.GetStaticFieldOrProperty("m_PathMap"),Global.System.Collections.Hashtable)
            Return ret
        End Get
        Set
            m_privateType.SetStaticFieldOrProperty("m_PathMap", value)
        End Set
    End Property
    
    Friend Shared Property m_RobotConfigMap() As Global.System.Collections.Hashtable
        Get
            Dim ret As Global.System.Collections.Hashtable = CType(m_privateType.GetStaticFieldOrProperty("m_RobotConfigMap"),Global.System.Collections.Hashtable)
            Return ret
        End Get
        Set
            m_privateType.SetStaticFieldOrProperty("m_RobotConfigMap", value)
        End Set
    End Property
    
    Friend Shared Property m_RobotPressureConfigMap() As Global.System.Collections.Hashtable
        Get
            Dim ret As Global.System.Collections.Hashtable = CType(m_privateType.GetStaticFieldOrProperty("m_RobotPressureConfigMap"),Global.System.Collections.Hashtable)
            Return ret
        End Get
        Set
            m_privateType.SetStaticFieldOrProperty("m_RobotPressureConfigMap", value)
        End Set
    End Property
    
    Friend Shared Property m_PumdownConfigMapLL() As Global.System.Collections.Hashtable
        Get
            Dim ret As Global.System.Collections.Hashtable = CType(m_privateType.GetStaticFieldOrProperty("m_PumdownConfigMapLL"),Global.System.Collections.Hashtable)
            Return ret
        End Get
        Set
            m_privateType.SetStaticFieldOrProperty("m_PumdownConfigMapLL", value)
        End Set
    End Property
    
    Friend Shared Property m_PumdownConfigMapTM() As Global.System.Collections.Hashtable
        Get
            Dim ret As Global.System.Collections.Hashtable = CType(m_privateType.GetStaticFieldOrProperty("m_PumdownConfigMapTM"),Global.System.Collections.Hashtable)
            Return ret
        End Get
        Set
            m_privateType.SetStaticFieldOrProperty("m_PumdownConfigMapTM", value)
        End Set
    End Property
    
    Friend Shared Property m_VentConfigMapLL() As Global.System.Collections.Hashtable
        Get
            Dim ret As Global.System.Collections.Hashtable = CType(m_privateType.GetStaticFieldOrProperty("m_VentConfigMapLL"),Global.System.Collections.Hashtable)
            Return ret
        End Get
        Set
            m_privateType.SetStaticFieldOrProperty("m_VentConfigMapLL", value)
        End Set
    End Property
    
    Friend Shared Property m_VentConfigMapTM() As Global.System.Collections.Hashtable
        Get
            Dim ret As Global.System.Collections.Hashtable = CType(m_privateType.GetStaticFieldOrProperty("m_VentConfigMapTM"),Global.System.Collections.Hashtable)
            Return ret
        End Get
        Set
            m_privateType.SetStaticFieldOrProperty("m_VentConfigMapTM", value)
        End Set
    End Property
    
    Friend Shared Property m_MessageTextMap() As Global.System.Collections.Hashtable
        Get
            Dim ret As Global.System.Collections.Hashtable = CType(m_privateType.GetStaticFieldOrProperty("m_MessageTextMap"),Global.System.Collections.Hashtable)
            Return ret
        End Get
        Set
            m_privateType.SetStaticFieldOrProperty("m_MessageTextMap", value)
        End Set
    End Property
    
    Friend Shared Property m_MessageTextDoc() As Global.System.Xml.XmlDocument
        Get
            Dim ret As Global.System.Xml.XmlDocument = CType(m_privateType.GetStaticFieldOrProperty("m_MessageTextDoc"),Global.System.Xml.XmlDocument)
            Return ret
        End Get
        Set
            m_privateType.SetStaticFieldOrProperty("m_MessageTextDoc", value)
        End Set
    End Property
    
    Friend Shared Function ChamberDB(ByVal m_Chamber As Global.AVPLib.DBChamber) As Global.System.Data.DataTable
        Dim args() As Object = New Object() {m_Chamber}
        Dim ret As Global.System.Data.DataTable = CType(m_privateType.InvokeStatic("ChamberDB", New System.Type() {GetType(Global.AVPLib.DBChamber)}, args),Global.System.Data.DataTable)
        Return ret
    End Function
    
    Friend Shared Function GetRecipeListAll() As Global.System.Collections.ArrayList
        Dim args(-1) As Object
        Dim ret As Global.System.Collections.ArrayList = CType(m_privateType.InvokeStatic("GetRecipeListAll", New System.Type(-1) {}, args),Global.System.Collections.ArrayList)
        Return ret
    End Function
    
    Friend Shared Sub ConfigureVentPumpdown()
        Dim args(-1) As Object
        m_privateType.InvokeStatic("ConfigureVentPumpdown", New System.Type(-1) {}, args)
    End Sub
    
    Friend Shared Sub MessageTextStart()
        Dim args(-1) As Object
        m_privateType.InvokeStatic("MessageTextStart", New System.Type(-1) {}, args)
    End Sub
    
    Friend Shared Function AddLoop(ByVal i As Integer, ByVal loopitem As Global.AVPLib.DataManagerment.WaferflowLoop, ByVal wfFlowName As String) As Boolean
        Dim args() As Object = New Object() {i, loopitem, wfFlowName}
        Dim ret As Boolean = CType(m_privateType.InvokeStatic("AddLoop", New System.Type() {GetType(Integer), GetType(Global.AVPLib.DataManagerment.WaferflowLoop), GetType(String)}, args),Boolean)
        Return ret
    End Function
    
    Friend Shared Function AddStep(ByVal i As Integer, ByVal stepitem As Global.AVPLib.DataManagerment.WaferflowStep, ByVal wfFlowName As String) As Boolean
        Dim args() As Object = New Object() {i, stepitem, wfFlowName}
        Dim ret As Boolean = CType(m_privateType.InvokeStatic("AddStep", New System.Type() {GetType(Integer), GetType(Global.AVPLib.DataManagerment.WaferflowStep), GetType(String)}, args),Boolean)
        Return ret
    End Function
    
    Friend Shared Function SelectedWaferNodes(ByVal xdoc As Global.System.Xml.XmlDocument, ByVal nodename As String) As Global.System.Xml.XmlNode
        Dim args() As Object = New Object() {xdoc, nodename}
        Dim ret As Global.System.Xml.XmlNode = CType(m_privateType.InvokeStatic("SelectedWaferNodes", New System.Type() {GetType(Global.System.Xml.XmlDocument), GetType(String)}, args),Global.System.Xml.XmlNode)
        Return ret
    End Function
    
    Friend Shared Function UpdateStep(ByVal stepitem As Global.AVPLib.DataManagerment.WaferflowStep, ByVal wfFlowitem As String) As Boolean
        Dim args() As Object = New Object() {stepitem, wfFlowitem}
        Dim ret As Boolean = CType(m_privateType.InvokeStatic("UpdateStep", New System.Type() {GetType(Global.AVPLib.DataManagerment.WaferflowStep), GetType(Global.AVPLib.DataManagerment.WaferFlow)}, args), Boolean)
        Return ret
    End Function
    
    Friend Shared Function UpdateLoop(ByVal loopitem As Global.AVPLib.DataManagerment.WaferflowLoop, ByVal wfFlowitem As String) As Boolean
        Dim args() As Object = New Object() {loopitem, wfFlowitem}
        Dim ret As Boolean = CType(m_privateType.InvokeStatic("UpdateLoop", New System.Type() {GetType(Global.AVPLib.DataManagerment.WaferflowLoop), GetType(Global.AVPLib.DataManagerment.WaferFlow)}, args), Boolean)
        Return ret
    End Function
End Class
