Namespace XMLResources
Public Class Chamber5
Public Const XMLText as String = _
"<RecipeDef>" & _
"  <ParameterList Id=""1"" isGroup=""1"" Group=""Version_Control"" GroupName=""Version_Control"" ShowInUI=""False"">" & _
"    <Parameter>" & _
"      <SeqNo>1</SeqNo>" & _
"      <Name>(c)1999-2001 Veeco Instruments Inc.</Name>" & _
"      <Description>(c)1999-2001 Veeco Instruments Inc.</Description>" & _
"      <Default></Default>" & _
"      <Unit>String</Unit>" & _
"      <ShowInUI>False</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>2</SeqNo>" & _
"      <Name>IBD Process File Version 15.00</Name>" & _
"      <Description>IBD Process File Version 15.00</Description>" & _
"      <Default></Default>" & _
"      <Unit>String</Unit>" & _
"      <ShowInUI>False</ShowInUI>" & _
"    </Parameter>" & _
"  </ParameterList>" & _
"  <ParameterList Id=""2"" isGroup=""1"" Group=""EtchBeamParameters"" GroupName=""EtchBeamParameters"" ShowInUI=""True"">" & _
"    <Parameter>" & _
"      <SeqNo>1</SeqNo>" & _
"      <Name>Beam_On</Name>" & _
"      <Description>Beam_On</Description>" & _
"      <Default>False</Default>" & _
"      <Unit>Boolean</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>2</SeqNo>" & _
"      <Name>Neutralizer_On</Name>" & _
"      <Description>Neutralizer_On</Description>" & _
"      <Default>False</Default>" & _
"      <Unit>Boolean</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>3</SeqNo>" & _
"      <Name>Beam_Voltage</Name>" & _
"      <Description>Beam_Voltage</Description>" & _
"      <Min>0</Min>" & _
"      <Max>1000</Max>" & _
"      <Default>0</Default>" & _
"      <Unit>V</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>4</SeqNo>" & _
"      <Name>Beam_Current</Name>" & _
"      <Description>Beam_Current</Description>" & _
"      <Min>0</Min>" & _
"      <Max>1000</Max>" & _
"      <Default>0</Default>" & _
"      <Unit>A</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>5</SeqNo>" & _
"      <Name>Incident_RF_Power</Name>" & _
"      <Description>Incident_RF_Power</Description>" & _
"      <Min>0</Min>" & _
"      <Max>1000</Max>" & _
"      <Default>0</Default>" & _
"      <Unit>W</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>6</SeqNo>" & _
"      <Name>Suppresser_Voltage</Name>" & _
"      <Description>Suppresser_Voltage</Description>" & _
"      <Min>0</Min>" & _
"      <Max>1000</Max>" & _
"      <Default>0</Default>" & _
"      <Unit>V</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>7</SeqNo>" & _
"      <Name>PBN_FLOWRATE</Name>" & _
"      <Description>PBN_FLOWRATE</Description>" & _
"      <Min>0</Min>" & _
"      <Max>100000</Max>" & _
"      <Default>0</Default>" & _
"      <Unit>sccm</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>8</SeqNo>" & _
"      <Name>K</Name>" & _
"      <Description>K</Description>" & _
"      <Min>0</Min>" & _
"      <Max>100000</Max>" & _
"      <Default>0</Default>" & _
"      <Unit>Number</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>9</SeqNo>" & _
"      <Name>Continuous_Beam</Name>" & _
"      <Description>Continuous_Beam</Description>" & _
"      <Default>False</Default>" & _
"      <Unit>Boolean</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>10</SeqNo>" & _
"      <Name>CAIBE_Step</Name>" & _
"      <Description>CAIBE_Step</Description>" & _
"      <Default>False</Default>" & _
"      <Unit>Boolean</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>11</SeqNo>" & _
"      <Name>UseStepRF</Name>" & _
"      <Description>UseStepRF</Description>" & _
"      <Default>False</Default>" & _
"      <Unit>Boolean</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"  </ParameterList>" & _
"  <ParameterList Id=""3"" isGroup=""1"" Group=""DepositionBeamParameters"" GroupName=""DepositionBeamParameters"" ShowInUI=""False"">" & _
"    <Parameter>" & _
"      <SeqNo>1</SeqNo>" & _
"      <Name>Beam_On</Name>" & _
"      <Description>Beam_On</Description>" & _
"      <Default>False</Default>" & _
"      <Unit>Boolean</Unit>" & _
"      <ShowInUI>False</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>2</SeqNo>" & _
"      <Name>Neutralizer_On</Name>" & _
"      <Description>Neutralizer_On</Description>" & _
"      <Default>False</Default>" & _
"      <Unit>Boolean</Unit>" & _
"      <ShowInUI>False</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>3</SeqNo>" & _
"      <Name>Beam_Voltage</Name>" & _
"      <Description>Beam_Voltage</Description>" & _
"      <Min>0</Min>" & _
"      <Max>1000</Max>" & _
"      <Default>0</Default>" & _
"      <Unit>V</Unit>" & _
"      <ShowInUI>False</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>4</SeqNo>" & _
"      <Name>Beam_Current</Name>" & _
"      <Description>Beam_Current</Description>" & _
"      <Min>0</Min>" & _
"      <Max>1000</Max>" & _
"      <Default>0</Default>" & _
"      <Unit>A</Unit>" & _
"      <ShowInUI>False</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>5</SeqNo>" & _
"      <Name>Incident_RF_Power</Name>" & _
"      <Description>Incident_RF_Power</Description>" & _
"      <Min>0</Min>" & _
"      <Max>1000</Max>" & _
"      <Default>0</Default>" & _
"      <Unit>W</Unit>" & _
"      <ShowInUI>False</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>6</SeqNo>" & _
"      <Name>Suppresser_Voltage</Name>" & _
"      <Description>Suppresser_Voltage</Description>" & _
"      <Min>0</Min>" & _
"      <Max>1000</Max>" & _
"      <Default>0</Default>" & _
"      <Unit>V</Unit>" & _
"      <ShowInUI>False</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>7</SeqNo>" & _
"      <Name>PBN_FLOWRATE</Name>" & _
"      <Description>PBN_FLOWRATE</Description>" & _
"      <Min>0</Min>" & _
"      <Max>100000</Max>" & _
"      <Default>0</Default>" & _
"      <Unit>sccm</Unit>" & _
"      <ShowInUI>False</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>8</SeqNo>" & _
"      <Name>K</Name>" & _
"      <Description>K</Description>" & _
"      <Min>0</Min>" & _
"      <Max>100000</Max>" & _
"      <Default>0</Default>" & _
"      <Unit>Number</Unit>" & _
"      <ShowInUI>False</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>9</SeqNo>" & _
"      <Name>Continuous_Beam</Name>" & _
"      <Description>Continuous_Beam</Description>" & _
"      <Default>False</Default>" & _
"      <Unit>Boolean</Unit>" & _
"      <ShowInUI>False</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>10</SeqNo>" & _
"      <Name>UseStepRF</Name>" & _
"      <Description>UseStepRF</Description>" & _
"      <Default>False</Default>" & _
"      <Unit>Boolean</Unit>" & _
"      <ShowInUI>False</ShowInUI>" & _
"    </Parameter>" & _
"  </ParameterList>" & _
"  <ParameterList Id=""4"" isGroup=""1"" Group=""EtchGasParameters"" GroupName=""EtchGasParameters"" ShowInUI=""True"">" & _
"    <Parameter>" & _
"      <SeqNo>1</SeqNo>" & _
"      <Name>Value_1</Name>" & _
"      <Description>Value_1</Description>" & _
"      <Min>0</Min>" & _
"      <Max>10000</Max>" & _
"      <Default>0</Default>" & _
"      <Unit>Number</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>2</SeqNo>" & _
"      <Name>Value_2</Name>" & _
"      <Description>Value_2</Description>" & _
"      <Min>0</Min>" & _
"      <Max>10000</Max>" & _
"      <Default>0</Default>" & _
"      <Unit>Number</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>3</SeqNo>" & _
"      <Name>Value_3</Name>" & _
"      <Description>Value_3</Description>" & _
"      <Min>0</Min>" & _
"      <Max>10000</Max>" & _
"      <Default>0</Default>" & _
"      <Unit>Number</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>4</SeqNo>" & _
"      <Name>Value_4</Name>" & _
"      <Description>Value_4</Description>" & _
"      <Min>0</Min>" & _
"      <Max>10000</Max>" & _
"      <Default>0</Default>" & _
"      <Unit>Number</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>5</SeqNo>" & _
"      <Name>Value_5</Name>" & _
"      <Description>Value_5</Description>" & _
"      <Min>0</Min>" & _
"      <Max>10000</Max>" & _
"      <Default>0</Default>" & _
"      <Unit>Number</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"  </ParameterList>" & _
"  <ParameterList Id=""5"" isGroup=""1"" Group=""DepositionGasParameters"" GroupName=""DepositionGasParameters"" ShowInUI=""False"">" & _
"    <Parameter>" & _
"      <SeqNo>1</SeqNo>" & _
"      <Name>Value_1</Name>" & _
"      <Description>Value_1</Description>" & _
"      <Min>0</Min>" & _
"      <Max>10000</Max>" & _
"      <Default>0</Default>" & _
"      <Unit>Number</Unit>" & _
"      <ShowInUI>False</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>2</SeqNo>" & _
"      <Name>Value_2</Name>" & _
"      <Description>Value_2</Description>" & _
"      <Min>0</Min>" & _
"      <Max>10000</Max>" & _
"      <Default>0</Default>" & _
"      <Unit>Number</Unit>" & _
"      <ShowInUI>False</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>3</SeqNo>" & _
"      <Name>Value_3</Name>" & _
"      <Description>Value_3</Description>" & _
"      <Min>0</Min>" & _
"      <Max>10000</Max>" & _
"      <Default>0</Default>" & _
"      <Unit>Number</Unit>" & _
"      <ShowInUI>False</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>4</SeqNo>" & _
"      <Name>Value_4</Name>" & _
"      <Description>Value_4</Description>" & _
"      <Min>0</Min>" & _
"      <Max>10000</Max>" & _
"      <Default>0</Default>" & _
"      <Unit>Number</Unit>" & _
"      <ShowInUI>False</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>5</SeqNo>" & _
"      <Name>Value_5</Name>" & _
"      <Description>Value_5</Description>" & _
"      <Min>0</Min>" & _
"      <Max>10000</Max>" & _
"      <Default>0</Default>" & _
"      <Unit>Number</Unit>" & _
"      <ShowInUI>False</ShowInUI>" & _
"    </Parameter>" & _
"  </ParameterList>" & _
"  <ParameterList Id=""6"" isGroup=""1"" Group=""MagneticChuck"" GroupName=""MagneticChuck"" ShowInUI=""True"">" & _
"    <Parameter>" & _
"      <SeqNo>1</SeqNo>" & _
"      <Name>Power_On</Name>" & _
"      <Description>Power_On</Description>" & _
"      <Default>False</Default>" & _
"      <Unit>Boolean</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>2</SeqNo>" & _
"      <Name>Phase_90</Name>" & _
"      <Description>Phase_90</Description>" & _
"      <Default>False</Default>" & _
"      <Unit>Boolean</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>3</SeqNo>" & _
"      <Name>Square_Wave</Name>" & _
"      <Description>Square_Wave</Description>" & _
"      <Default>False</Default>" & _
"      <Unit>Boolean</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"  </ParameterList>" & _
"  <ParameterList Id=""7"" isGroup=""1"" Group=""FaultTolerance"" GroupName=""FaultTolerance"" ShowInUI=""True"">" & _
"    <Parameter>" & _
"      <SeqNo>1</SeqNo>" & _
"      <Name>Active</Name>" & _
"      <Description>Active</Description>" & _
"      <Default>False</Default>" & _
"      <Unit>Boolean</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>2</SeqNo>" & _
"      <Name>AbortOnError</Name>" & _
"      <Description>AbortOnError</Description>" & _
"      <Default>False</Default>" & _
"      <Unit>Boolean</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"  </ParameterList>" & _
"  <ParameterList Id=""8"" isGroup=""1"" Group=""HotChuck"" GroupName=""HotChuck"" ShowInUI=""True"">" & _
"    <Parameter>" & _
"      <SeqNo>1</SeqNo>" & _
"      <Name>Active</Name>" & _
"      <Description>Active</Description>" & _
"      <Default>False</Default>" & _
"      <Unit>Boolean</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>2</SeqNo>" & _
"      <Name>WaitForTemperature</Name>" & _
"      <Description>WaitForTemperature</Description>" & _
"      <Default>False</Default>" & _
"      <Unit>Boolean</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>3</SeqNo>" & _
"      <Name>Temperature</Name>" & _
"      <Description>Temperature</Description>" & _
"      <Min>0</Min>" & _
"      <Max>10000</Max>" & _
"      <Default>0</Default>" & _
"      <Unit>K</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>4</SeqNo>" & _
"      <Name>TimeInSeconds</Name>" & _
"      <Description>TimeInSeconds</Description>" & _
"      <Min>0</Min>" & _
"      <Max>10000</Max>" & _
"      <Default>0</Default>" & _
"      <Unit>sec</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"  </ParameterList>" & _
"  <ParameterList Id=""9"" isGroup=""1"" Group=""Control"" GroupName=""Control"" ShowInUI=""True"">" & _
"    <Parameter>" & _
"      <SeqNo>1</SeqNo>" & _
"      <Name>Process_Ends_By</Name>" & _
"      <Description>Process_Ends_By</Description>" & _
"      <Min></Min>" & _
"      <Max></Max>" & _
"      <Default>0</Default>" & _
"      <Unit>Number</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>2</SeqNo>" & _
"      <Name>Endpoint_Script_Name</Name>" & _
"      <Description>Endpoint_Script_Name</Description>" & _
"      <Default>LongScriptFileName</Default>" & _
"      <Unit>String</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>3</SeqNo>" & _
"      <Name>UseElectroStaticShutter</Name>" & _
"      <Description>UseElectroStaticShutter</Description>" & _
"      <Default>False</Default>" & _
"      <Unit>Boolean</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>4</SeqNo>" & _
"      <Name>UseEtchRateCorrection</Name>" & _
"      <Description>UseEtchRateCorrection</Description>" & _
"      <Default>False</Default>" & _
"      <Unit>Boolean</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>5</SeqNo>" & _
"      <Name>Etch_Rate_Correction_Power_Group</Name>" & _
"      <Description>Etch_Rate_Correction_Power_Group</Description>" & _
"      <Min></Min>" & _
"      <Max></Max>" & _
"      <Default>0</Default>" & _
"      <Unit>Number</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>6</SeqNo>" & _
"      <Name>Etch_Time_Hour</Name>" & _
"      <Description>Etch_Time_Hour</Description>" & _
"      <Min>0</Min>" & _
"      <Max></Max>" & _
"      <Default>0</Default>" & _
"      <Unit>hour</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>7</SeqNo>" & _
"      <Name>Etch_Time_Min</Name>" & _
"      <Description>Etch_Time_Min</Description>" & _
"      <Min>0</Min>" & _
"      <Max></Max>" & _
"      <Default>0</Default>" & _
"      <Unit>min</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>8</SeqNo>" & _
"      <Name>Etch_Time_Sec</Name>" & _
"      <Description>Etch_Time_Sec</Description>" & _
"      <Min>0</Min>" & _
"      <Max></Max>" & _
"      <Default>0</Default>" & _
"      <Unit>sec</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>9</SeqNo>" & _
"      <Name>Etch_Time_MilliSec</Name>" & _
"      <Description>Etch_Time_MilliSec</Description>" & _
"      <Min>0</Min>" & _
"      <Max></Max>" & _
"      <Default>0</Default>" & _
"      <Unit>millisec</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>10</SeqNo>" & _
"      <Name>Ion_Charge</Name>" & _
"      <Description>Ion_Charge</Description>" & _
"      <Min></Min>" & _
"      <Max></Max>" & _
"      <Default>0</Default>" & _
"      <Unit>Number</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>11</SeqNo>" & _
"      <Name>Process_Pressure_High</Name>" & _
"      <Description>Process_Pressure_High</Description>" & _
"      <Min>0</Min>" & _
"      <Max>10000</Max>" & _
"      <Default>0</Default>" & _
"      <Unit>mTorr</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>12</SeqNo>" & _
"      <Name>Process_Pressure_Low</Name>" & _
"      <Description>Process_Pressure_Low</Description>" & _
"      <Min>0</Min>" & _
"      <Max>10000</Max>" & _
"      <Default>0</Default>" & _
"      <Unit>mTorr</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>13</SeqNo>" & _
"      <Name>Fixture_Angle</Name>" & _
"      <Description>Fixture_Angle</Description>" & _
"      <Min></Min>" & _
"      <Max></Max>" & _
"      <Default>-888</Default>" & _
"      <Unit>Deg</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>14</SeqNo>" & _
"      <Name>Target_Side</Name>" & _
"      <Description>Target_Side</Description>" & _
"      <Min></Min>" & _
"      <Max></Max>" & _
"      <Default>0</Default>" & _
"      <Unit>Number</Unit>" & _
"      <ShowInUI>False</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>15</SeqNo>" & _
"      <Name>Target_Angle</Name>" & _
"      <Description>Target_Angle</Description>" & _
"      <Min>0</Min>" & _
"      <Max>360</Max>" & _
"      <Default>40</Default>" & _
"      <Unit>Deg</Unit>" & _
"      <ShowInUI>False</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>16</SeqNo>" & _
"      <Name>FlowCool_Flowrate</Name>" & _
"      <Description>FlowCool_Flowrate</Description>" & _
"      <Min>0</Min>" & _
"      <Max>100000</Max>" & _
"      <Default>0</Default>" & _
"      <Unit>sccm</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>17</SeqNo>" & _
"      <Name>Open_Etch_Shutter_At_Start</Name>" & _
"      <Description>Open_Etch_Shutter_At_Start</Description>" & _
"      <Default>True</Default>" & _
"      <Unit>Boolean</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>18</SeqNo>" & _
"      <Name>Open_Etch_Shutter_At_Beam</Name>" & _
"      <Description>Open_Etch_Shutter_At_Beam</Description>" & _
"      <Default>True</Default>" & _
"      <Unit>Boolean</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>19</SeqNo>" & _
"      <Name>Close_Etch_Shutter_At_End</Name>" & _
"      <Description>Close_Etch_Shutter_At_End</Description>" & _
"      <Default>True</Default>" & _
"      <Unit>Boolean</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>20</SeqNo>" & _
"      <Name>Open_Depo_Shutter_At_Start</Name>" & _
"      <Description>Open_Depo_Shutter_At_Start</Description>" & _
"      <Default>True</Default>" & _
"      <Unit>Boolean</Unit>" & _
"      <ShowInUI>False</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>21</SeqNo>" & _
"      <Name>Open_Depo_Shutter_At_Beam</Name>" & _
"      <Description>Open_Depo_Shutter_At_Beam</Description>" & _
"      <Default>True</Default>" & _
"      <Unit>Boolean</Unit>" & _
"      <ShowInUI>False</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>22</SeqNo>" & _
"      <Name>Close_Depo_Shutter_At_End</Name>" & _
"      <Description>Close_Depo_Shutter_At_End</Description>" & _
"      <Default>True</Default>" & _
"      <Unit>Boolean</Unit>" & _
"      <ShowInUI>False</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>23</SeqNo>" & _
"      <Name>Open_Target_Shutter_At_Start</Name>" & _
"      <Description>Open_Target_Shutter_At_Start</Description>" & _
"      <Default>True</Default>" & _
"      <Unit>Boolean</Unit>" & _
"      <ShowInUI>False</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>24</SeqNo>" & _
"      <Name>Open_Target_Shutter_At_Beam</Name>" & _
"      <Description>Open_Target_Shutter_At_Beam</Description>" & _
"      <Default>True</Default>" & _
"      <Unit>Boolean</Unit>" & _
"      <ShowInUI>False</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>25</SeqNo>" & _
"      <Name>Close_Target_Shutter_At_End</Name>" & _
"      <Description>Close_Target_Shutter_At_End</Description>" & _
"      <Default>True</Default>" & _
"      <Unit>Boolean</Unit>" & _
"      <ShowInUI>False</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>26</SeqNo>" & _
"      <Name>Open_Fixture_Shutter_At_Start</Name>" & _
"      <Description>Open_Fixture_Shutter_At_Start</Description>" & _
"      <Default>True</Default>" & _
"      <Unit>Boolean</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>27</SeqNo>" & _
"      <Name>Open_Fixture_Shutter_At_Beam</Name>" & _
"      <Description>Open_Fixture_Shutter_At_Beam</Description>" & _
"      <Default>True</Default>" & _
"      <Unit>Boolean</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>28</SeqNo>" & _
"      <Name>Close_Fixture_Shutter_At_End</Name>" & _
"      <Description>Close_Fixture_Shutter_At_End</Description>" & _
"      <Default>True</Default>" & _
"      <Unit>Boolean</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>29</SeqNo>" & _
"      <Name>OpenTargetShield</Name>" & _
"      <Description>OpenTargetShield</Description>" & _
"      <Default>False</Default>" & _
"      <Unit>Boolean</Unit>" & _
"      <ShowInUI>False</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>30</SeqNo>" & _
"      <Name>OpenCryoGate</Name>" & _
"      <Description>OpenCryoGate</Description>" & _
"      <Default>False</Default>" & _
"      <Unit>Boolean</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>31</SeqNo>" & _
"      <Name>UseRGA</Name>" & _
"      <Description>UseRGA</Description>" & _
"      <Default>False</Default>" & _
"      <Unit>Boolean</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>32</SeqNo>" & _
"      <Name>WaitForGEMStepTime</Name>" & _
"      <Description>WaitForGEMStepTime</Description>" & _
"      <Default>False</Default>" & _
"      <Unit>Boolean</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"  </ParameterList>" & _
"  <ParameterList Id=""10"" isGroup=""1"" Group=""FixtureServo"" GroupName=""FixtureServo"" ShowInUI=""True"">" & _
"    <Parameter>" & _
"      <SeqNo>1</SeqNo>" & _
"      <Name>Fixture_Rotate_Continious</Name>" & _
"      <Description>Fixture_Rotate_Continious</Description>" & _
"      <Default>False</Default>" & _
"      <Unit>Boolean</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>2</SeqNo>" & _
"      <Name>Fixture_Rotate_Sweep</Name>" & _
"      <Description>Fixture_Rotate_Sweep</Description>" & _
"      <Default>False</Default>" & _
"      <Unit>Boolean</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>3</SeqNo>" & _
"      <Name>Fixture_Rotate_Static</Name>" & _
"      <Description>Fixture_Rotate_Static</Description>" & _
"      <Default>False</Default>" & _
"      <Unit>Boolean</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>4</SeqNo>" & _
"      <Name>Sweep_Start_Angle</Name>" & _
"      <Description>Sweep_Start_Angle</Description>" & _
"      <Min>0</Min>" & _
"      <Max>360</Max>" & _
"      <Default>0</Default>" & _
"      <Unit>Deg</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>5</SeqNo>" & _
"      <Name>Sweep_End_Angle</Name>" & _
"      <Description>Sweep_End_Angle</Description>" & _
"      <Min>0</Min>" & _
"      <Max>360</Max>" & _
"      <Default>0</Default>" & _
"      <Unit>Deg</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>6</SeqNo>" & _
"      <Name>Static_Angle</Name>" & _
"      <Description>Static_Angle</Description>" & _
"      <Min>0</Min>" & _
"      <Max>360</Max>" & _
"      <Default>0</Default>" & _
"      <Unit>Deg</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>7</SeqNo>" & _
"      <Name>Fixture_Rotation_Speed</Name>" & _
"      <Description>Fixture_Rotation_Speed</Description>" & _
"      <Min>0</Min>" & _
"      <Max>100000</Max>" & _
"      <Default>0.0</Default>" & _
"      <Unit>rpm</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"  </ParameterList>" & _
"  <ParameterList Id=""11"" isGroup=""1"" Group=""DataTracing"" GroupName=""DataTracing"" ShowInUI=""True"">" & _
"    <Parameter>" & _
"      <SeqNo>1</SeqNo>" & _
"      <Name>TracingEnabled</Name>" & _
"      <Description>Enable Tracing</Description>" & _
"      <Default>False</Default>" & _
"      <Unit>Boolean</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"    <Parameter>" & _
"      <SeqNo>2</SeqNo>" & _
"      <Name>Interval</Name>" & _
"      <Description>Interval</Description>" & _
"      <Min>0</Min>" & _
"      <Max>10000</Max>" & _
"      <Default>5</Default>" & _
"      <Unit>sec</Unit>" & _
"      <ShowInUI>True</ShowInUI>" & _
"    </Parameter>" & _
"  </ParameterList>" & _
"</RecipeDef>"
End Class
End Namespace
