Namespace XMLResources
Public Class PVD5TSystemConfig
Public Const XMLText as String = _
"<SystemConfiguration>" & _
"  <Modules>" & _
"    <Chamber1>" & _
"		<MessageText>" & _
"		  <Key>Chamber1.PVD5T.TargetPowerSupply.txtForwardPowerRightMin</Key>" & _
"		  <Value>0</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber1.PVD5T.TargetPowerSupply.txtForwardPowerRightMax</Key>" & _
"		  <Value>10</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber1.PVD5T.BiasPowerSupply.txtForwardPowerRightMin</Key>" & _
"		  <Value>0</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber1.PVD5T.BiasPowerSupply.txtForwardPowerRightMax</Key>" & _
"		  <Value>10</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber1.PVD5T.BiasPowerSupply.txtVoltageRightMax</Key>" & _
"		  <Value>50000</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber1.PVD5T.BiasPowerSupply.txtVoltageRightMin</Key>" & _
"		  <Value>0</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber1.PVD5T.TargetPowerSupply.txtC1RightMax</Key>" & _
"		  <Value>50000</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber1.PVD5T.TargetPowerSupply.txtC1RightMin</Key>" & _
"		  <Value>0</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber1.PVD5T.TargetPowerSupply.txtC2RightMax</Key>" & _
"		  <Value>50000</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber1.PVD5T.TargetPowerSupply.txtC2RightMin</Key>" & _
"		  <Value>0</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber1.PVD5T.TargetPowerSupply.txtPresetsRightMax</Key>" & _
"		  <Value>50000</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber1.PVD5T.TargetPowerSupply.txtPresetsRightMin</Key>" & _
"		  <Value>0</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber1.PVD5T.TargetPowerSupply.txtDCForwardPowerRightMax</Key>" & _
"		  <Value>5000</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber1.PVD5T.TargetPowerSupply.txtDCForwardPowerRightMin</Key>" & _
"		  <Value>0</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber1.PVD5T.TargetPowerSupply.txtPulseFrequencyRightMax</Key>" & _
"		  <Value>50000</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber1.PVD5T.TargetPowerSupply.txtPulseFrequencyRightMin</Key>" & _
"		  <Value>0</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber1.PVD5T.TargetPowerSupply.txtPulseWidthRightMax</Key>" & _
"		  <Value>50000</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber1.PVD5T.TargetPowerSupply.txtPulseWidthRightMin</Key>" & _
"		  <Value>0</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber1.PVD5T.TargetPowerSupply.txtRampTimeRightMax</Key>" & _
"		  <Value>50000</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber1.PVD5T.TargetPowerSupply.txtRampTimeRightMin</Key>" & _
"		  <Value>0</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber1.PVD5T.BiasPowerSupply.txtC1RightMax</Key>" & _
"		  <Value>50000</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber1.PVD5T.BiasPowerSupply.txtC1RightMin</Key>" & _
"		  <Value>0</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber1.PVD5T.BiasPowerSupply.txtC2RightMax</Key>" & _
"		  <Value>50000</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber1.PVD5T.BiasPowerSupply.txtC2RightMin</Key>" & _
"		  <Value>0</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber1.PVD5T.BiasPowerSupply.txtPresetsRightMax</Key>" & _
"		  <Value>50000</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber1.PVD5T.BiasPowerSupply.txtPresetsRightMin</Key>" & _
"		  <Value>0</Value>" & _
"		</MessageText>" & _
"    <MessageText>" & _
"      <Key>Chamber1.PVD5T.txtRotateRightMax</Key>" & _
"      <Value>50000</Value>" & _
"    </MessageText>" & _
"    <MessageText>" & _
"      <Key>Chamber1.PVD5T.txtRotateRightMin</Key>" & _
"      <Value>0</Value>" & _
"    </MessageText>" & _
"    <MessageText>" & _
"      <Key>Chamber1.PVD5T.txtTablePosRightMax</Key>" & _
"      <Value>50000</Value>" & _
"    </MessageText>" & _
"    <MessageText>" & _
"      <Key>Chamber1.PVD5T.txtTablePosRightMin</Key>" & _
"      <Value>0</Value>" & _
"    </MessageText>" & _
"    </Chamber1>" & _
"	" & _
"    <Chamber2>" & _
"		<MessageText>" & _
"		  <Key>Chamber2.PVD5T.TargetPowerSupply.txtForwardPowerRightMin</Key>" & _
"		  <Value>0</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber2.PVD5T.TargetPowerSupply.txtForwardPowerRightMax</Key>" & _
"		  <Value>10</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber2.PVD5T.BiasPowerSupply.txtForwardPowerRightMin</Key>" & _
"		  <Value>0</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber2.PVD5T.BiasPowerSupply.txtForwardPowerRightMax</Key>" & _
"		  <Value>10</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber2.PVD5T.BiasPowerSupply.txtVoltageRightMax</Key>" & _
"		  <Value>50000</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber2.PVD5T.BiasPowerSupply.txtVoltageRightMin</Key>" & _
"		  <Value>0</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber2.PVD5T.TargetPowerSupply.txtC1RightMax</Key>" & _
"		  <Value>50000</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber2.PVD5T.TargetPowerSupply.txtC1RightMin</Key>" & _
"		  <Value>0</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber2.PVD5T.TargetPowerSupply.txtC2RightMax</Key>" & _
"		  <Value>50000</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber2.PVD5T.TargetPowerSupply.txtC2RightMin</Key>" & _
"		  <Value>0</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber2.PVD5T.TargetPowerSupply.txtPresetsRightMax</Key>" & _
"		  <Value>50000</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber2.PVD5T.TargetPowerSupply.txtPresetsRightMin</Key>" & _
"		  <Value>0</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber2.PVD5T.TargetPowerSupply.txtDCForwardPowerRightMax</Key>" & _
"		  <Value>5000</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber2.PVD5T.TargetPowerSupply.txtDCForwardPowerRightMin</Key>" & _
"		  <Value>0</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber2.PVD5T.TargetPowerSupply.txtPulseFrequencyRightMax</Key>" & _
"		  <Value>50000</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber2.PVD5T.TargetPowerSupply.txtPulseFrequencyRightMin</Key>" & _
"		  <Value>0</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber2.PVD5T.TargetPowerSupply.txtPulseWidthRightMax</Key>" & _
"		  <Value>50000</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber2.PVD5T.TargetPowerSupply.txtPulseWidthRightMin</Key>" & _
"		  <Value>0</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber2.PVD5T.TargetPowerSupply.txtRampTimeRightMax</Key>" & _
"		  <Value>50000</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber2.PVD5T.TargetPowerSupply.txtRampTimeRightMin</Key>" & _
"		  <Value>0</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber2.PVD5T.BiasPowerSupply.txtC1RightMax</Key>" & _
"		  <Value>50000</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber2.PVD5T.BiasPowerSupply.txtC1RightMin</Key>" & _
"		  <Value>0</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber2.PVD5T.BiasPowerSupply.txtC2RightMax</Key>" & _
"		  <Value>50000</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber2.PVD5T.BiasPowerSupply.txtC2RightMin</Key>" & _
"		  <Value>0</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber2.PVD5T.BiasPowerSupply.txtPresetsRightMax</Key>" & _
"		  <Value>50000</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber2.PVD5T.BiasPowerSupply.txtPresetsRightMin</Key>" & _
"		  <Value>0</Value>" & _
"		</MessageText>" & _
"    <MessageText>" & _
"      <Key>Chamber2.PVD5T.txtRotateRightMax</Key>" & _
"      <Value>50000</Value>" & _
"    </MessageText>" & _
"    <MessageText>" & _
"      <Key>Chamber2.PVD5T.txtRotateRightMin</Key>" & _
"      <Value>0</Value>" & _
"    </MessageText>" & _
"    <MessageText>" & _
"      <Key>Chamber2.PVD5T.txtTablePosRightMax</Key>" & _
"      <Value>50000</Value>" & _
"    </MessageText>" & _
"    <MessageText>" & _
"      <Key>Chamber2.PVD5T.txtTablePosRightMin</Key>" & _
"      <Value>0</Value>" & _
"    </MessageText>" & _
"    </Chamber2>" & _
"	" & _
"    <Chamber3>" & _
"		<MessageText>" & _
"		  <Key>Chamber3.PVD5T.TargetPowerSupply.txtForwardPowerRightMin</Key>" & _
"		  <Value>0</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber3.PVD5T.TargetPowerSupply.txtForwardPowerRightMax</Key>" & _
"		  <Value>10</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber3.PVD5T.BiasPowerSupply.txtForwardPowerRightMin</Key>" & _
"		  <Value>0</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber3.PVD5T.BiasPowerSupply.txtForwardPowerRightMax</Key>" & _
"		  <Value>10</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber3.PVD5T.BiasPowerSupply.txtVoltageRightMax</Key>" & _
"		  <Value>50000</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber3.PVD5T.BiasPowerSupply.txtVoltageRightMin</Key>" & _
"		  <Value>0</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber3.PVD5T.TargetPowerSupply.txtC1RightMax</Key>" & _
"		  <Value>50000</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber3.PVD5T.TargetPowerSupply.txtC1RightMin</Key>" & _
"		  <Value>0</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber3.PVD5T.TargetPowerSupply.txtC2RightMax</Key>" & _
"		  <Value>50000</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber3.PVD5T.TargetPowerSupply.txtC2RightMin</Key>" & _
"		  <Value>0</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber3.PVD5T.TargetPowerSupply.txtPresetsRightMax</Key>" & _
"		  <Value>50000</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber3.PVD5T.TargetPowerSupply.txtPresetsRightMin</Key>" & _
"		  <Value>0</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber3.PVD5T.TargetPowerSupply.txtDCForwardPowerRightMax</Key>" & _
"		  <Value>5000</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber3.PVD5T.TargetPowerSupply.txtDCForwardPowerRightMin</Key>" & _
"		  <Value>0</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber3.PVD5T.TargetPowerSupply.txtPulseFrequencyRightMax</Key>" & _
"		  <Value>50000</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber3.PVD5T.TargetPowerSupply.txtPulseFrequencyRightMin</Key>" & _
"		  <Value>0</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber3.PVD5T.TargetPowerSupply.txtPulseWidthRightMax</Key>" & _
"		  <Value>50000</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber3.PVD5T.TargetPowerSupply.txtPulseWidthRightMin</Key>" & _
"		  <Value>0</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber3.PVD5T.TargetPowerSupply.txtRampTimeRightMax</Key>" & _
"		  <Value>50000</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber3.PVD5T.TargetPowerSupply.txtRampTimeRightMin</Key>" & _
"		  <Value>0</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber3.PVD5T.BiasPowerSupply.txtC1RightMax</Key>" & _
"		  <Value>50000</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber3.PVD5T.BiasPowerSupply.txtC1RightMin</Key>" & _
"		  <Value>0</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber3.PVD5T.BiasPowerSupply.txtC2RightMax</Key>" & _
"		  <Value>50000</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber3.PVD5T.BiasPowerSupply.txtC2RightMin</Key>" & _
"		  <Value>0</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber3.PVD5T.BiasPowerSupply.txtPresetsRightMax</Key>" & _
"		  <Value>50000</Value>" & _
"		</MessageText>" & _
"		<MessageText>" & _
"		  <Key>Chamber3.PVD5T.BiasPowerSupply.txtPresetsRightMin</Key>" & _
"		  <Value>0</Value>" & _
"		</MessageText>" & _
"    <MessageText>" & _
"      <Key>Chamber3.PVD5T.txtRotateRightMax</Key>" & _
"      <Value>50000</Value>" & _
"    </MessageText>" & _
"    <MessageText>" & _
"      <Key>Chamber3.PVD5T.txtRotateRightMin</Key>" & _
"      <Value>0</Value>" & _
"    </MessageText>" & _
"    <MessageText>" & _
"      <Key>Chamber3.PVD5T.txtTablePosRightMax</Key>" & _
"      <Value>50000</Value>" & _
"    </MessageText>" & _
"    <MessageText>" & _
"      <Key>Chamber3.PVD5T.txtTablePosRightMin</Key>" & _
"      <Value>0</Value>" & _
"    </MessageText>" & _
"    </Chamber3>" & _
"  </Modules>" & _
"  " & _
"  <UserMessageTexts> " & _
"    <MessageText>" & _
"      <Key>PVD5T.TextboxClick</Key>" & _
"      <Value>Would you like to change {0} value to?</Value>" & _
"    </MessageText>" & _
"    <MessageText>" & _
"      <Key>PVD5T.btnAuto.Off</Key>" & _
"      <Value>Would you like to change to Auto?</Value>" & _
"    </MessageText>" & _
"    <MessageText>" & _
"      <Key>PVD5T.btnAuto.On</Key>" & _
"      <Value>Would you like to change to Manual?</Value>" & _
"    </MessageText>" & _
"    <MessageText>" & _
"      <Key>PVD5T.btnAuto.Unknow</Key>" & _
"      <Value>Would you like to change to Auto/Manual?</Value>" & _
"    </MessageText>" & _
"    <MessageText>" & _
"      <Key>PVD5T.btnContact.Off</Key>" & _
"      <Value>Would you like to change to Ground?</Value>" & _
"    </MessageText>" & _
"    <MessageText>" & _
"      <Key>PVD5T.btnContact.On</Key>" & _
"      <Value>Would you like to change to Float?</Value>" & _
"    </MessageText>" & _
"    <MessageText>" & _
"      <Key>PVD5T.TableControl.btnUP.Off</Key>" & _
"      <Value>Would you like to Up?</Value>" & _
"    </MessageText>" & _
"    <MessageText>" & _
"      <Key>PVD5T.TableControl.btnDOWN.Off</Key>" & _
"      <Value>Would you like to Down?</Value>" & _
"    </MessageText>" & _
"    <MessageText>" & _
"      <Key>PVD5T.TableControl.btnUP.On</Key>" & _
"      <Value>Would you like to abort Up?</Value>" & _
"    </MessageText>" & _
"    <MessageText>" & _
"      <Key>PVD5T.TableControl.btnDOWN.On</Key>" & _
"      <Value>Would you like to abort Down?</Value>" & _
"    </MessageText>" & _
"    <MessageText>" & _
"      <Key>PVD5T.TableControl.btnHOME.Off</Key>" & _
"      <Value>Would you like to start Home All?</Value>" & _
"    </MessageText>" & _
"    <MessageText>" & _
"      <Key>PVD5T.TableControl.btnHOME.On</Key>" & _
"      <Value>Would you like to start Home All?</Value>" & _
"    </MessageText>" & _
"    <MessageText>" & _
"      <Key>PVD5T.TableControl.btnHOME.Unknow</Key>" & _
"      <Value>Would you like to stop Home All?</Value>" & _
"    </MessageText>" & _
"    <MessageText>" & _
"      <Key>PVD5T.TableControl.btnRotate.Off</Key>" & _
"      <Value>Would you like to Start Rotate?</Value>" & _
"    </MessageText>" & _
"    <MessageText>" & _
"      <Key>PVD5T.TableControl.btnRotate.On</Key>" & _
"      <Value>Would you like to Stop Rotate?</Value>" & _
"    </MessageText>" & _
"    <MessageText>" & _
"      <Key>PVD5T.TableControl.btnHomeTable</Key>" & _
"      <Value>Would you like to do Table Home ?</Value>" & _
"    </MessageText>" & _
"    <MessageText>" & _
"      <Key>PVD5T.TableControl.btnUP</Key>" & _
"      <Value>Would you like to do Table Up ?</Value>" & _
"    </MessageText>" & _
"    <MessageText>" & _
"      <Key>PVD5T.TableControl.btnDOWN</Key>" & _
"      <Value>Would you like to do Table Down ?</Value>" & _
"    </MessageText>" & _
"    <MessageText>" & _
"      <Key>PVD5T.TableControl.btnLiftUp</Key>" & _
"      <Value>Would you like to do Lift Up ?</Value>" & _
"    </MessageText>" & _
"    <MessageText>" & _
"      <Key>PVD5T.TableControl.btnLiftDown</Key>" & _
"      <Value>Would you like to do Lift Down ?</Value>" & _
"    </MessageText>" & _
"    <MessageText>" & _
"      <Key>PVD5T.TableControl.cbxGoTo</Key>" & _
"      <Value>Would you like to Go To {0}?</Value>" & _
"    </MessageText>" & _
"  </UserMessageTexts>" & _
"</SystemConfiguration>"
End Class
End Namespace
