Namespace XMLResources
Public Class User
Public Const XMLText as String = _
"<Users>" & _
"  <User>" & _
"    <Username>OPERATOR</Username>" & _
"    <Password>123</Password>" & _
"    <Group>2</Group>" & _
"    <Disable>0</Disable>" & _
"    <AccessList>" & _
"      <Access Permit=""0"" Code=""001"" Screen=""Maintaince screens"" />" & _
"      <Access Permit=""1"" Code=""002"" Screen=""Recipe Editors"" />" & _
"      <Access Permit=""0"" Code=""003"" Screen=""Return And Resume Wafer"" />" & _
"      <Access Permit=""1"" Code=""004"" Screen=""System Setup"" />" & _
"      <Access Permit=""0"" Code=""005"" Screen=""User Account Setup"" />" & _
"      <Access Permit=""0"" Code=""006"" Screen=""Reset Wafers Count"" />" & _
"      <Access Permit=""0"" Code=""008"" Screen=""Exit AVP Software"" />" & _
"      <Access Permit=""0"" Code=""009"" Screen=""Clear Alarm"" />" & _
"      <Access Permit=""0"" Code=""013"" Screen=""Make All Online, Clear All Wafer"" />" & _
"      <Access Permit=""0"" Code=""014"" Screen=""GEMControl screens"" />" & _
"    </AccessList>" & _
"    <RecipePrivilege>" & _
"      <Recipe Type=""PVD4"" Name=""Chamber1"">" & _
"	   <ParameterList Group=""LoopInfomation"">" & _
"          <Parameter>" & _
"            <Name>LoopMode</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>LoopCount</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"        <ParameterList Group=""Gasses"">" & _
"          <Parameter>" & _
"            <Name>Gas1</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas2</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas3</Name>" & _
"            <RW>False</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas4</Name>" & _
"            <RW>False</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas5</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>UseGasDistribution</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"        <ParameterList Group=""ProcessControl"">" & _
"          <Parameter>" & _
"            <Name>ControlMode</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Revolution</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>ProcessTimeSeconds</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>StaticPostion</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>ProcessStartPressure</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>ProcessVATMode</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>ProcessVATPosition</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>ProcessPressure</Name>" & _
"            <RW>False</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>PowerDown</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>LogIntervalSecond</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"        <ParameterList Group=""RFTargetPower"">" & _
"          <Parameter>" & _
"            <Name>TargetSelection</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetPower</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetRampTime</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetC1</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetC2</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetMatchingMode</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetShutterOpen</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"        <ParameterList Group=""DCTargetPower"">" & _
"          <Parameter>" & _
"            <Name>TargetSelection</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetPower</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetRampTime</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetPulseFrequency</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetPulseWidth</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetShutterOpen</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"        <ParameterList Group=""SubstratePower"">" & _
"          <Parameter>" & _
"            <Name>ControlMode</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>BiasPower</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>BiasVoltage</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>SubGrounded</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"        <ParameterList Group=""MotionControl"">" & _
"          <Parameter>" & _
"            <Name>TableRotationSpeed</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TableHeight</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"      </Recipe>" & _
"      <Recipe Type=""IBE"" Name=""Chamber2"">" & _
"        <ParameterList Group=""EtchBeamParameters"">" & _
"          <Parameter>" & _
"            <Name>Beam_On</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Neutralizer_On</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Beam_Voltage</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Beam_Current</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Incident_RF_Power</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Suppresser_Voltage</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>PBN_FLOWRATE</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>K_Factor</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Continuous_Beam</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>UseStepRF</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"        <ParameterList Group=""EtchGasParameters"">" & _
"          <Parameter>" & _
"            <Name>Gas1</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas2</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas3</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas4</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas5</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"        <ParameterList Group=""Control"">" & _
"          <Parameter>" & _
"            <Name>Process_Ends_By</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Endpoint_Script_Name</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>UseElectroStaticShutter</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>UseEtchRateCorrection</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Etch_Rate_Correction_Power_Group</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Etch_Time_Sec</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Etch_Percentage_PSR</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Process_Pressure_High</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Process_Pressure_Low</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Fixture_Angle</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>FlowCool_Flowrate</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Open_Etch_Shutter_At_Start</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Open_Etch_Shutter_At_Beam</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Close_Etch_Shutter_At_End</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>OpenCryoGate</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"        <ParameterList Group=""FixtureServo"">" & _
"          <Parameter>" & _
"            <Name>Fixture_Rotate</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Sweep_Start_Angle</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Sweep_End_Angle</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Static_Angle</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Fixture_Rotation_Speed</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"        <ParameterList Group=""DataTracing"">" & _
"          <Parameter>" & _
"            <Name>TracingEnabled</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Interval</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"      </Recipe>" & _
"      <Recipe Type=""PVD"" Name=""Chamber3"">" & _
"        <ParameterList Group=""Gases"">" & _
"          <Parameter>" & _
"            <Name>Gas1</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas2</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas3</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas4</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas5</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"        <ParameterList Group=""ProcessControl"">" & _
"          <Parameter>" & _
"            <Name>ProcessTime</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>RampTime</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>ProcessPressure</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>ProcessStartPressure</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetPower</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Pulse</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetC1</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetC2</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetMatchingMode</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>OpenShutter</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>ChuckHeight</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>BiasPower</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>BiasVoltage</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>BiasC1</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>BiasC2</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>BiasMatchingMode</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>BiasC1C2FromRecipe</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>BiasControl</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>PowerDown</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>MagnetState</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>MagCurrent</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>MagnetDutyCycle</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>MagFrequency</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>IsStabilize</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>RecipeComments</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"      </Recipe>" & _
"      <Recipe Type=""Aligner"" Name=""Aligner"" />" & _
"    </RecipePrivilege>" & _
"  </User>" & _
"  <User>" & _
"    <Username>ADMIN</Username>" & _
"    <Password>123</Password>" & _
"    <Group>1</Group>" & _
"    <Disable>0</Disable>" & _
"    <AccessList>" & _
"      <Access Permit=""1"" Code=""001"" Screen=""Maintaince screens"" />" & _
"      <Access Permit=""1"" Code=""002"" Screen=""Recipe Editors"" />" & _
"      <Access Permit=""1"" Code=""003"" Screen=""Return And Resume Wafer"" />" & _
"      <Access Permit=""1"" Code=""004"" Screen=""System Setup"" />" & _
"      <Access Permit=""1"" Code=""005"" Screen=""User Account Setup"" />" & _
"      <Access Permit=""1"" Code=""006"" Screen=""Reset Wafers Count"" />" & _
"      <Access Permit=""1"" Code=""008"" Screen=""Exit AVP Software"" />" & _
"      <Access Permit=""1"" Code=""009"" Screen=""Clear Alarm"" />" & _
"      <Access Permit=""1"" Code=""013"" Screen=""Make All Online, Clear All Wafer"" />" & _
"      <Access Permit=""1"" Code=""014"" Screen=""GEMControl screens"" />" & _
"    </AccessList>" & _
"    <RecipePrivilege>" & _
"      <Recipe Type=""PVD4"" Name=""Chamber1"">" & _
"        <ParameterList Group=""Gasses"">" & _
"          <Parameter>" & _
"            <Name>Gas1</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas2</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas3</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas4</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas5</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>UseGasDistribution</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"        <ParameterList Group=""ProcessControl"">" & _
"          <Parameter>" & _
"            <Name>ControlMode</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Revolution</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>ProcessTimeSeconds</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>StaticPostion</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>ProcessStartPressure</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>ProcessVATMode</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>ProcessVATPosition</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>ProcessPressure</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>PowerDown</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>LogIntervalSecond</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"        <ParameterList Group=""RFTargetPower"">" & _
"          <Parameter>" & _
"            <Name>TargetSelection</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetPower</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetRampTime</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetC1</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetC2</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetMatchingMode</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetShutterOpen</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"        <ParameterList Group=""DCTargetPower"">" & _
"          <Parameter>" & _
"            <Name>TargetSelection</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetPower</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetRampTime</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetPulseFrequency</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetPulseWidth</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetShutterOpen</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"        <ParameterList Group=""SubstratePower"">" & _
"          <Parameter>" & _
"            <Name>ControlMode</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>BiasPower</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>BiasVoltage</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>SubGrounded</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"        <ParameterList Group=""MotionControl"">" & _
"          <Parameter>" & _
"            <Name>TableRotationSpeed</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TableHeight</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"      </Recipe>" & _
"      <Recipe Type=""IBE"" Name=""Chamber2"">" & _
"        <ParameterList Group=""EtchBeamParameters"">" & _
"          <Parameter>" & _
"            <Name>Beam_On</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Neutralizer_On</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Beam_Voltage</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Beam_Current</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Incident_RF_Power</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Suppresser_Voltage</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>PBN_FLOWRATE</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>K_Factor</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Continuous_Beam</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>UseStepRF</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"        <ParameterList Group=""EtchGasParameters"">" & _
"          <Parameter>" & _
"            <Name>Gas1</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas2</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas3</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas4</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas5</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"        <ParameterList Group=""Control"">" & _
"          <Parameter>" & _
"            <Name>Process_Ends_By</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Endpoint_Script_Name</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>UseElectroStaticShutter</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>UseEtchRateCorrection</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Etch_Rate_Correction_Power_Group</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Etch_Time_Sec</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Etch_Percentage_PSR</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Process_Pressure_High</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Process_Pressure_Low</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Fixture_Angle</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>FlowCool_Flowrate</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Open_Etch_Shutter_At_Start</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Open_Etch_Shutter_At_Beam</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Close_Etch_Shutter_At_End</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>OpenCryoGate</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"        <ParameterList Group=""FixtureServo"">" & _
"          <Parameter>" & _
"            <Name>Fixture_Rotate</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Sweep_Start_Angle</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Sweep_End_Angle</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Static_Angle</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Fixture_Rotation_Speed</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"        <ParameterList Group=""DataTracing"">" & _
"          <Parameter>" & _
"            <Name>TracingEnabled</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Interval</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"      </Recipe>" & _
"      <Recipe Type=""PVD"" Name=""Chamber3"">" & _
"        <ParameterList Group=""Gases"">" & _
"          <Parameter>" & _
"            <Name>Gas1</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas2</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas3</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas4</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas5</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"        <ParameterList Group=""ProcessControl"">" & _
"          <Parameter>" & _
"            <Name>ProcessTime</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>RampTime</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>ProcessPressure</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>ProcessStartPressure</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetPower</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Pulse</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetC1</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetC2</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetMatchingMode</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>OpenShutter</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>ChuckHeight</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>BiasPower</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>BiasVoltage</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>BiasC1</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>BiasC2</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>BiasMatchingMode</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>BiasC1C2FromRecipe</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>BiasControl</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>PowerDown</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>MagnetState</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>MagCurrent</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>MagnetDutyCycle</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>MagFrequency</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>IsStabilize</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>RecipeComments</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"      </Recipe>" & _
"      <Recipe Type=""Aligner"" Name=""Aligner"" />" & _
"    </RecipePrivilege>" & _
"  </User>" & _
"  <User>" & _
"    <Username>DEFAULT_DO_NOT_READ_IN_GUI</Username>" & _
"    <Password>123</Password>" & _
"    <Group>2</Group>" & _
"    <Disable>0</Disable>" & _
"    <AccessList>" & _
"      <Access Permit=""1"" Code=""001"" DefaultFor=""Maint"" Screen=""Maintaince screens"" />" & _
"      <Access Permit=""1"" Code=""002"" DefaultFor=""Engineer,Maint"" Screen=""Recipe Editors"" />" & _
"      <Access Permit=""1"" Code=""003"" DefaultFor=""Engineer,Maint"" Screen=""Return And Resume Wafer"" />" & _
"      <Access Permit=""1"" Code=""004"" DefaultFor=""Maint"" Screen=""System Setup"" />" & _
"      <Access Permit=""1"" Code=""005"" DefaultFor="""" Screen=""User Account Setup"" />" & _
"      <Access Permit=""1"" Code=""006"" DefaultFor=""Maint"" Screen=""Reset Wafers Count"" />" & _
"      <Access Permit=""1"" Code=""008"" DefaultFor=""Maint"" Screen=""Exit AVP Software"" />" & _
"      <Access Permit=""1"" Code=""009"" DefaultFor=""Engineer,Maint"" Screen=""Clear Alarm"" />" & _
"      <Access Permit=""1"" Code=""013"" DefaultFor=""Engineer,Maint"" Screen=""Make All Online, Clear All Wafer"" />" & _
"      <Access Permit=""1"" Code=""014"" DefaultFor=""Engineer,Maint"" Screen=""GEMControl screens"" />" & _
"    </AccessList>" & _
"    <RecipePrivilege>" & _
"      <Recipe Type=""PVD"">" & _
"        <ParameterList Group=""Gases"">" & _
"          <Parameter>" & _
"            <Name>Gas1</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas2</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas3</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas4</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas5</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"        <ParameterList Group=""ProcessControl"">" & _
"          <Parameter>" & _
"            <Name>ProcessTime</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>RampTime</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>ProcessPressure</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>OpenShutter</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>ChuckHeight</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>BiasPower</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>BiasVoltage</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>PowerDown</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>BiasControl</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>BiasMatchingMode</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>BiasC1C2FromRecipe</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>BiasC1</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>BiasC2</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetPower</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>MagnetState</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>MagCurrent</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>MagFrequency</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>IsStabilize</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>MagnetDutyCycle</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Pulse</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>PulseFrequency</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>PulseWidth</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetC1</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetC2</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"      </Recipe>" & _
"      <Recipe Type=""IBE"">" & _
"        <ParameterList Group=""EtchBeamParameters"">" & _
"          <Parameter>" & _
"            <Name>Beam_On</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Neutralizer_On</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Beam_Voltage</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Beam_Current</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Incident_RF_Power</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Suppresser_Voltage</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>PBN_FLOWRATE</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>K</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Continuous_Beam</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>CAIBE_Step</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>UseStepRF</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"        <ParameterList Group=""EtchGasParameters"">" & _
"          <Parameter>" & _
"            <Name>Value_1</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Value_2</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Value_3</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Value_4</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Value_5</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"        <ParameterList Group=""MagneticChuck"">" & _
"          <Parameter>" & _
"            <Name>Power_On</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Phase_90</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Square_Wave</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"        <ParameterList Group=""FaultTolerance"">" & _
"          <Parameter>" & _
"            <Name>Active</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>AbortOnError</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"        <ParameterList Group=""HotChuck"">" & _
"          <Parameter>" & _
"            <Name>Active</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>WaitForTemperature</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Temperature</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TimeInSeconds</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"        <ParameterList Group=""Control"">" & _
"          <Parameter>" & _
"            <Name>Process_Ends_By</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Endpoint_Script_Name</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>UseElectroStaticShutter</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>UseEtchRateCorrection</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Etch_Rate_Correction_Power_Group</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Etch_Time_Hour</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Etch_Time_Min</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Etch_Time_Sec</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Etch_Time_MilliSec</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Ion_Charge</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Process_Pressure_High</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Process_Pressure_Low</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Fixture_Angle</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>FlowCool_Flowrate</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Open_Etch_Shutter_At_Start</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Open_Etch_Shutter_At_Beam</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Close_Etch_Shutter_At_End</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Open_Fixture_Shutter_At_Start</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Open_Fixture_Shutter_At_Beam</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Close_Fixture_Shutter_At_End</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>OpenCryoGate</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>UseRGA</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>WaitForGEMStepTime</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"        <ParameterList Group=""FixtureServo"">" & _
"          <Parameter>" & _
"            <Name>Fixture_Rotate_Continious</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Fixture_Rotate_Sweep</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Fixture_Rotate_Static</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Sweep_Start_Angle</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Sweep_End_Angle</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Static_Angle</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Fixture_Rotation_Speed</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"        <ParameterList Group=""DataTracing"">" & _
"          <Parameter>" & _
"            <Name>TracingEnabled</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Interval</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"      </Recipe>" & _
"      <Recipe Type=""PVD4"">" & _
"        <ParameterList Group=""Gasses"">" & _
"          <Parameter>" & _
"            <Name>Gas1</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas2</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas3</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas4</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas5</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>UseGasDistribution</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"		  <Parameter>" & _
"            <Name>UseSecondaryGasOnly</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"        <ParameterList Group=""ProcessControl"">" & _
"          <Parameter>" & _
"            <Name>ControlMode</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Revolution</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>ProcessTimeSeconds</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>StaticPostion</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>ProcessStartPressure</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>ProcessVATMode</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>ProcessVATPosition</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>ProcessPressure</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>PowerDown</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>LogIntervalSecond</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"        <ParameterList Group=""RFTargetPower"">" & _
"          <Parameter>" & _
"            <Name>TargetSelection</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetPower</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetRampTime</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetVoltageMin</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"		  <Parameter>" & _
"            <Name>TargetVoltageMax</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetC1</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetC2</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetMatchingMode</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetShutterOpen</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"        <ParameterList Group=""DCTargetPower"">" & _
"          <Parameter>" & _
"            <Name>TargetSelection</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetPower</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetRampTime</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetPulseFrequency</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetPulseWidth</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetShutterOpen</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"        <ParameterList Group=""SubstratePower"">" & _
"          <Parameter>" & _
"            <Name>ControlMode</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>BiasPower</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>BiasVoltage</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>SubGrounded</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"        <ParameterList Group=""MotionControl"">" & _
"          <Parameter>" & _
"            <Name>TableRotationSpeed</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TableHeight</Name>" & _
"            <RW DefaultFor=""Engineer"">True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"	    <ParameterList Group=""FilMetricControl"">" & _
"          <Parameter>" & _
"            <Name>RecipeName</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>WaferThickness</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"		  <Parameter>" & _
"            <Name>DelayTimes</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"      </Recipe>" & _
"    </RecipePrivilege>" & _
"  </User>" & _
"  <User>" & _
"    <Username>ROOT</Username>" & _
"    <Password>root@AVP</Password>" & _
"    <Group>1</Group>" & _
"    <Disable>0</Disable>" & _
"    <AccessList>" & _
"      <Access Permit=""1"" Code=""001"" Screen=""Maintaince screens"" />" & _
"      <Access Permit=""1"" Code=""002"" Screen=""Recipe Editors"" />" & _
"      <Access Permit=""1"" Code=""003"" Screen=""Return And Resume Wafer"" />" & _
"      <Access Permit=""1"" Code=""004"" Screen=""System Setup"" />" & _
"      <Access Permit=""1"" Code=""005"" Screen=""User Account Setup"" />" & _
"      <Access Permit=""1"" Code=""006"" Screen=""Reset Wafers Count"" />" & _
"      <Access Permit=""1"" Code=""008"" Screen=""Exit AVP Software"" />" & _
"      <Access Permit=""1"" Code=""009"" Screen=""Clear Alarm"" />" & _
"      <Access Permit=""1"" Code=""013"" Screen=""Make All Online, Clear All Wafer"" />" & _
"      <Access Permit=""1"" Code=""014"" Screen=""GEMControl screens"" />" & _
"    </AccessList>" & _
"    <RecipePrivilege>" & _
"      <Recipe Type=""IBE"" Name=""Chamber1"">" & _
"        <ParameterList Group=""EtchBeamParameters"">" & _
"          <Parameter>" & _
"            <Name>Beam_On</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Neutralizer_On</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Beam_Voltage</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Beam_Current</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Incident_RF_Power</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Suppresser_Voltage</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>PBN_FLOWRATE</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>K_Factor</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Continuous_Beam</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>UseStepRF</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"        <ParameterList Group=""EtchGasParameters"">" & _
"          <Parameter>" & _
"            <Name>Gas1</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas2</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas3</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas4</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas5</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"        <ParameterList Group=""Control"">" & _
"          <Parameter>" & _
"            <Name>Process_Ends_By</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Endpoint_Script_Name</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>UseElectroStaticShutter</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>UseEtchRateCorrection</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Etch_Rate_Correction_Power_Group</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Etch_Time_Hour</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Etch_Time_Min</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Etch_Time_Sec</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Etch_Time_MilliSec</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Process_Pressure_High</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Process_Pressure_Low</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Fixture_Angle</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>FlowCool_Flowrate</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Open_Etch_Shutter_At_Start</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Open_Etch_Shutter_At_Beam</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Close_Etch_Shutter_At_End</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>OpenCryoGate</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"        <ParameterList Group=""FixtureServo"">" & _
"          <Parameter>" & _
"            <Name>Fixture_Rotate</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Sweep_Start_Angle</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Sweep_End_Angle</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Static_Angle</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Fixture_Rotation_Speed</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"        <ParameterList Group=""DataTracing"">" & _
"          <Parameter>" & _
"            <Name>TracingEnabled</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Interval</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"      </Recipe>" & _
"      <Recipe Type=""IBE"" Name=""Chamber2"">" & _
"        <ParameterList Group=""EtchBeamParameters"">" & _
"          <Parameter>" & _
"            <Name>Beam_On</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Neutralizer_On</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Beam_Voltage</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Beam_Current</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Incident_RF_Power</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Suppresser_Voltage</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>PBN_FLOWRATE</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>K_Factor</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Continuous_Beam</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>UseStepRF</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"        <ParameterList Group=""EtchGasParameters"">" & _
"          <Parameter>" & _
"            <Name>Gas1</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas2</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas3</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas4</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas5</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"        <ParameterList Group=""Control"">" & _
"          <Parameter>" & _
"            <Name>Process_Ends_By</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Endpoint_Script_Name</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>UseElectroStaticShutter</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>UseEtchRateCorrection</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Etch_Rate_Correction_Power_Group</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Etch_Time_Hour</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Etch_Time_Min</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Etch_Time_Sec</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Etch_Time_MilliSec</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Process_Pressure_High</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Process_Pressure_Low</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Fixture_Angle</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>FlowCool_Flowrate</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Open_Etch_Shutter_At_Start</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Open_Etch_Shutter_At_Beam</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Close_Etch_Shutter_At_End</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>OpenCryoGate</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"        <ParameterList Group=""FixtureServo"">" & _
"          <Parameter>" & _
"            <Name>Fixture_Rotate</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Sweep_Start_Angle</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Sweep_End_Angle</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Static_Angle</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Fixture_Rotation_Speed</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"        <ParameterList Group=""DataTracing"">" & _
"          <Parameter>" & _
"            <Name>TracingEnabled</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Interval</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"      </Recipe>" & _
"      <Recipe Type=""PVD"" Name=""Chamber3"">" & _
"        <ParameterList Group=""Gases"">" & _
"          <Parameter>" & _
"            <Name>Gas1</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas2</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas3</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas4</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Gas5</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"        <ParameterList Group=""ProcessControl"">" & _
"          <Parameter>" & _
"            <Name>ProcessTime</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>RampTime</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>ProcessPressure</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>ProcessStartPressure</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetPower</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetC1</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetC2</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>TargetMatchingMode</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>OpenShutter</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>Pulse</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>PulseFrequency</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>PulseWidth</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>ChuckHeight</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>BiasPower</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>BiasVoltage</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>BiasC1</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>BiasC2</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>BiasMatchingMode</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>BiasC1C2FromRecipe</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>BiasControl</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>PowerDown</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>MagnetState</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>MagCurrent</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>MagnetDutyCycle</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>MagFrequency</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>IsStabilize</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"          <Parameter>" & _
"            <Name>RecipeComments</Name>" & _
"            <RW>True</RW>" & _
"          </Parameter>" & _
"        </ParameterList>" & _
"      </Recipe>" & _
"    </RecipePrivilege>" & _
"  </User>" & _
"</Users>"
End Class
End Namespace
